
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
public sealed partial class ActivityHolidayFeast_Act : Luban.BeanBase
{
    public ActivityHolidayFeast_Act(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        MainType = _buf.ReadInt();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);SubTypes = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); SubTypes[__index0] = __e0;}}
        OpenTime = _buf.ReadString();
        EndTime = _buf.ReadString();
        OpenTimeCN = _buf.ReadString();
        EndTimeCN = _buf.ReadString();
        Feast_TitleId = _buf.ReadString();
        Feast_Title_OffsetX = _buf.ReadFloat();
        Feast_Title_OffsetY = _buf.ReadFloat();
        Activity_Bgm = _buf.ReadInt();
        EntryType = _buf.ReadInt();
        IsFixed = _buf.ReadInt();
        Feast_HelperTitleId = _buf.ReadString();
        Feast_HelperDescId = _buf.ReadString();
    }

    public static ActivityHolidayFeast_Act DeserializeActivityHolidayFeast_Act(ByteBuf _buf)
    {
        return new ActivityHolidayFeast_Act(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 主活动类型
    /// </summary>
    public readonly int MainType;
    /// <summary>
    /// 子活动，按照按钮顺序设置
    /// </summary>
    public readonly int[] SubTypes;
    /// <summary>
    /// 开启时间<br/>绝对时间
    /// </summary>
    public readonly string OpenTime;
    /// <summary>
    /// 结束时间<br/>绝对时间
    /// </summary>
    public readonly string EndTime;
    /// <summary>
    /// 开启时间<br/>绝对时间
    /// </summary>
    public readonly string OpenTimeCN;
    /// <summary>
    /// 结束时间<br/>绝对时间
    /// </summary>
    public readonly string EndTimeCN;
    /// <summary>
    /// 活动盛宴标题名Id
    /// </summary>
    public readonly string Feast_TitleId;
    /// <summary>
    /// 标题名偏移
    /// </summary>
    public readonly float Feast_Title_OffsetX;
    /// <summary>
    /// 标题名偏移
    /// </summary>
    public readonly float Feast_Title_OffsetY;
    /// <summary>
    /// 活动bgm
    /// </summary>
    public readonly int Activity_Bgm;
    /// <summary>
    /// 入口位置类型<br/>1：顶部固定<br/>2：底部固定<br/>默认：中间收纳
    /// </summary>
    public readonly int EntryType;
    /// <summary>
    /// 是否固定
    /// </summary>
    public readonly int IsFixed;
    /// <summary>
    /// 活动盛宴说明标题Id
    /// </summary>
    public readonly string Feast_HelperTitleId;
    /// <summary>
    /// 活动盛宴说明内容
    /// </summary>
    public readonly string Feast_HelperDescId;
   
    public const int __ID__ = -493306003;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "MainType:" + MainType + ","
        + "SubTypes:" + Luban.StringUtil.CollectionToString(SubTypes) + ","
        + "OpenTime:" + OpenTime + ","
        + "EndTime:" + EndTime + ","
        + "OpenTimeCN:" + OpenTimeCN + ","
        + "EndTimeCN:" + EndTimeCN + ","
        + "Feast_TitleId:" + Feast_TitleId + ","
        + "Feast_Title_OffsetX:" + Feast_Title_OffsetX + ","
        + "Feast_Title_OffsetY:" + Feast_Title_OffsetY + ","
        + "Activity_Bgm:" + Activity_Bgm + ","
        + "EntryType:" + EntryType + ","
        + "IsFixed:" + IsFixed + ","
        + "Feast_HelperTitleId:" + Feast_HelperTitleId + ","
        + "Feast_HelperDescId:" + Feast_HelperDescId + ","
        + "}";
    }
}

}

