
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
public sealed partial class ActivityDan_MonoTheme : Luban.BeanBase
{
    public ActivityDan_MonoTheme(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        Grid_AtlasId = _buf.ReadInt();
        Grid_StartAtlasId = _buf.ReadInt();
        Grid_StartSprite = _buf.ReadString();
        Grid_TrainSprite = _buf.ReadString();
        Grid_SpaBgSprite = _buf.ReadString();
        TipTitleId_Star = _buf.ReadString();
        TipDescId_Star = _buf.ReadString();
        TipTitleId_Spa = _buf.ReadString();
        TipDescId_Spa = _buf.ReadString();
        Main_Scene = _buf.ReadInt();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Main_SceneBorder = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); Main_SceneBorder[__index0] = __e0;}}
        Main_Grid = _buf.ReadInt();
        Task_Banner = _buf.ReadInt();
        PassPreView_Bg = _buf.ReadInt();
        Pass_Banner = _buf.ReadInt();
        Pass_Bg = _buf.ReadInt();
        Pass_RewardTop = _buf.ReadInt();
        Pass_TopLeft = _buf.ReadInt();
        Pass_TopRight = _buf.ReadInt();
        Pass_RewardLeft = _buf.ReadInt();
        Pass_RewardRight = _buf.ReadInt();
        Pass_RewardBottom = _buf.ReadInt();
        Pass_LightColor = _buf.ReadString();
        Pass_StarColor = _buf.ReadString();
    }

    public static ActivityDan_MonoTheme DeserializeActivityDan_MonoTheme(ByteBuf _buf)
    {
        return new ActivityDan_MonoTheme(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 默认格子图集
    /// </summary>
    public readonly int Grid_AtlasId;
    /// <summary>
    /// 开始格子图集
    /// </summary>
    public readonly int Grid_StartAtlasId;
    /// <summary>
    /// 开始格子图
    /// </summary>
    public readonly string Grid_StartSprite;
    /// <summary>
    /// 火车格子图
    /// </summary>
    public readonly string Grid_TrainSprite;
    /// <summary>
    /// 温泉格子图
    /// </summary>
    public readonly string Grid_SpaBgSprite;
    /// <summary>
    /// 点击提示标题语言Id<br/>只需配置特定事件格
    /// </summary>
    public readonly string TipTitleId_Star;
    /// <summary>
    /// 点击提示内容语言Id<br/>只需配置特定事件格
    /// </summary>
    public readonly string TipDescId_Star;
    /// <summary>
    /// 点击提示标题语言Id<br/>只需配置特定事件格
    /// </summary>
    public readonly string TipTitleId_Spa;
    /// <summary>
    /// 点击提示内容语言Id<br/>只需配置特定事件格
    /// </summary>
    public readonly string TipDescId_Spa;
    /// <summary>
    /// 场景图
    /// </summary>
    public readonly int Main_Scene;
    /// <summary>
    /// 场景图适配边距
    /// </summary>
    public readonly int[] Main_SceneBorder;
    /// <summary>
    /// 格子图
    /// </summary>
    public readonly int Main_Grid;
    /// <summary>
    /// 任务banner图
    /// </summary>
    public readonly int Task_Banner;
    /// <summary>
    /// 通行证预览背景图
    /// </summary>
    public readonly int PassPreView_Bg;
    /// <summary>
    /// 通行证banner图
    /// </summary>
    public readonly int Pass_Banner;
    /// <summary>
    /// 通行证背景图
    /// </summary>
    public readonly int Pass_Bg;
    /// <summary>
    /// 通行证奖励顶部图
    /// </summary>
    public readonly int Pass_RewardTop;
    /// <summary>
    /// 通行证奖励顶部左图
    /// </summary>
    public readonly int Pass_TopLeft;
    /// <summary>
    /// 通行证奖励顶部右图
    /// </summary>
    public readonly int Pass_TopRight;
    /// <summary>
    /// 通行证奖励左部图
    /// </summary>
    public readonly int Pass_RewardLeft;
    /// <summary>
    /// 通行证奖励右部图
    /// </summary>
    public readonly int Pass_RewardRight;
    /// <summary>
    /// 通行证奖励底部图
    /// </summary>
    public readonly int Pass_RewardBottom;
    /// <summary>
    /// 通行光颜色
    /// </summary>
    public readonly string Pass_LightColor;
    /// <summary>
    /// 通行证星星颜色
    /// </summary>
    public readonly string Pass_StarColor;
   
    public const int __ID__ = -891684247;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Grid_AtlasId:" + Grid_AtlasId + ","
        + "Grid_StartAtlasId:" + Grid_StartAtlasId + ","
        + "Grid_StartSprite:" + Grid_StartSprite + ","
        + "Grid_TrainSprite:" + Grid_TrainSprite + ","
        + "Grid_SpaBgSprite:" + Grid_SpaBgSprite + ","
        + "TipTitleId_Star:" + TipTitleId_Star + ","
        + "TipDescId_Star:" + TipDescId_Star + ","
        + "TipTitleId_Spa:" + TipTitleId_Spa + ","
        + "TipDescId_Spa:" + TipDescId_Spa + ","
        + "Main_Scene:" + Main_Scene + ","
        + "Main_SceneBorder:" + Luban.StringUtil.CollectionToString(Main_SceneBorder) + ","
        + "Main_Grid:" + Main_Grid + ","
        + "Task_Banner:" + Task_Banner + ","
        + "PassPreView_Bg:" + PassPreView_Bg + ","
        + "Pass_Banner:" + Pass_Banner + ","
        + "Pass_Bg:" + Pass_Bg + ","
        + "Pass_RewardTop:" + Pass_RewardTop + ","
        + "Pass_TopLeft:" + Pass_TopLeft + ","
        + "Pass_TopRight:" + Pass_TopRight + ","
        + "Pass_RewardLeft:" + Pass_RewardLeft + ","
        + "Pass_RewardRight:" + Pass_RewardRight + ","
        + "Pass_RewardBottom:" + Pass_RewardBottom + ","
        + "Pass_LightColor:" + Pass_LightColor + ","
        + "Pass_StarColor:" + Pass_StarColor + ","
        + "}";
    }
}

}

