
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
public sealed partial class Attribute_AttrText : Luban.BeanBase
{
    public Attribute_AttrText(ByteBuf _buf) 
    {
        ID = _buf.ReadString();
        linkID = _buf.ReadInt();
        noShowPercent = _buf.ReadInt();
        IsPower = _buf.ReadInt();
        Value = _buf.ReadFloat();
        LanguageId = _buf.ReadString();
        SortID = _buf.ReadInt();
        DisplayType = _buf.ReadInt();
        iconAtlasID = _buf.ReadInt();
        iconName = _buf.ReadString();
        desLanguage = _buf.ReadString();
    }

    public static Attribute_AttrText DeserializeAttribute_AttrText(ByteBuf _buf)
    {
        return new Attribute_AttrText(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly string ID;
    /// <summary>
    /// 属性关联id<br/>（id随意分配，但不可重复）
    /// </summary>
    public readonly int linkID;
    /// <summary>
    /// 不显示百分号(0:显示 1:不显示）
    /// </summary>
    public readonly int noShowPercent;
    /// <summary>
    /// 是否计算战力
    /// </summary>
    public readonly int IsPower;
    /// <summary>
    /// 战力值
    /// </summary>
    public readonly float Value;
    /// <summary>
    /// 属性名文本读取language表（无参数）
    /// </summary>
    public readonly string LanguageId;
    /// <summary>
    /// 属性列表排序
    /// </summary>
    public readonly int SortID;
    /// <summary>
    /// 属性列表<br/>1基础2高级
    /// </summary>
    public readonly int DisplayType;
    /// <summary>
    /// icon图集id<br/>0代表没有
    /// </summary>
    public readonly int iconAtlasID;
    /// <summary>
    /// icon图集中sprite的名称
    /// </summary>
    public readonly string iconName;
    /// <summary>
    /// tip描述对应的多语言
    /// </summary>
    public readonly string desLanguage;
   
    public const int __ID__ = 687933761;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "linkID:" + linkID + ","
        + "noShowPercent:" + noShowPercent + ","
        + "IsPower:" + IsPower + ","
        + "Value:" + Value + ","
        + "LanguageId:" + LanguageId + ","
        + "SortID:" + SortID + ","
        + "DisplayType:" + DisplayType + ","
        + "iconAtlasID:" + iconAtlasID + ","
        + "iconName:" + iconName + ","
        + "desLanguage:" + desLanguage + ","
        + "}";
    }
}

}

