
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
public sealed partial class ChainPacks_ChainType : Luban.BeanBase
{
    public ChainPacks_ChainType(ByteBuf _buf) 
    {
        id = _buf.ReadInt();
        sort = _buf.ReadInt();
        sprite_Banner = _buf.ReadString();
        atlasId_Title = _buf.ReadInt();
        sprite_Title = _buf.ReadString();
        sprite_Bg = _buf.ReadString();
        sprite_Bg_Mask = _buf.ReadString();
        sprite_NodeBg_Current = _buf.ReadString();
        sprite_NodeBg_Other = _buf.ReadString();
        CVLangId = _buf.ReadString();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);systemLangNone = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); systemLangNone[__index0] = __e0;}}
    }

    public static ChainPacks_ChainType DeserializeChainPacks_ChainType(ByteBuf _buf)
    {
        return new ChainPacks_ChainType(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 排序<br/>小的在前
    /// </summary>
    public readonly int sort;
    /// <summary>
    /// banner图片
    /// </summary>
    public readonly string sprite_Banner;
    /// <summary>
    /// 标题图集Id
    /// </summary>
    public readonly int atlasId_Title;
    /// <summary>
    /// 标题图片
    /// </summary>
    public readonly string sprite_Title;
    /// <summary>
    /// 背景图片
    /// </summary>
    public readonly string sprite_Bg;
    /// <summary>
    /// 背景遮罩
    /// </summary>
    public readonly string sprite_Bg_Mask;
    /// <summary>
    /// 当前节点背景图片
    /// </summary>
    public readonly string sprite_NodeBg_Current;
    /// <summary>
    /// 非当前节点背景图片
    /// </summary>
    public readonly string sprite_NodeBg_Other;
    /// <summary>
    /// 版权相关的描述
    /// </summary>
    public readonly string CVLangId;
    /// <summary>
    /// 哪几种系统语言不显示
    /// </summary>
    public readonly string[] systemLangNone;
   
    public const int __ID__ = 398006293;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "sort:" + sort + ","
        + "sprite_Banner:" + sprite_Banner + ","
        + "atlasId_Title:" + atlasId_Title + ","
        + "sprite_Title:" + sprite_Title + ","
        + "sprite_Bg:" + sprite_Bg + ","
        + "sprite_Bg_Mask:" + sprite_Bg_Mask + ","
        + "sprite_NodeBg_Current:" + sprite_NodeBg_Current + ","
        + "sprite_NodeBg_Other:" + sprite_NodeBg_Other + ","
        + "CVLangId:" + CVLangId + ","
        + "systemLangNone:" + Luban.StringUtil.CollectionToString(systemLangNone) + ","
        + "}";
    }
}

}

