
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
public sealed partial class ChapterHard_chapterHardSelectSkill : Luban.BeanBase
{
    public ChapterHard_chapterHardSelectSkill(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        type = _buf.ReadInt();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);selectSkill = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); selectSkill[__index0] = __e0;}}
    }

    public static ChapterHard_chapterHardSelectSkill DeserializeChapterHard_chapterHardSelectSkill(ByteBuf _buf)
    {
        return new ChapterHard_chapterHardSelectSkill(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 类型<br/>1-单次3选1<br/>2-选X轮
    /// </summary>
    public readonly int type;
    /// <summary>
    /// 出几个技能|选几个|选几轮|技能池
    /// </summary>
    public readonly string[] selectSkill;
   
    public const int __ID__ = 477394468;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "type:" + type + ","
        + "selectSkill:" + Luban.StringUtil.CollectionToString(selectSkill) + ","
        + "}";
    }
}

}

