
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
public sealed partial class ChapterMiniGame_paySlotReward : Luban.BeanBase
{
    public ChapterMiniGame_paySlotReward(ByteBuf _buf) 
    {
        id = _buf.ReadInt();
        groupId = _buf.ReadInt();
        weight = _buf.ReadInt();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);param = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); param[__index0] = __e0;}}
        atlas = _buf.ReadInt();
        icon = _buf.ReadString();
    }

    public static ChapterMiniGame_paySlotReward DeserializeChapterMiniGame_paySlotReward(ByteBuf _buf)
    {
        return new ChapterMiniGame_paySlotReward(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 奖励组id
    /// </summary>
    public readonly int groupId;
    /// <summary>
    /// 权重
    /// </summary>
    public readonly int weight;
    /// <summary>
    /// 参数<br/>奖励类型|奖励|数量
    /// </summary>
    public readonly string[] param;
    /// <summary>
    /// 图集
    /// </summary>
    public readonly int atlas;
    /// <summary>
    /// 图片
    /// </summary>
    public readonly string icon;
   
    public const int __ID__ = 1769480524;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "groupId:" + groupId + ","
        + "weight:" + weight + ","
        + "param:" + Luban.StringUtil.CollectionToString(param) + ","
        + "atlas:" + atlas + ","
        + "icon:" + icon + ","
        + "}";
    }
}

}

