
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
public sealed partial class ChapterActivity_RankActivity : Luban.BeanBase
{
    public ChapterActivity_RankActivity(ByteBuf _buf) 
    {
        id = _buf.ReadInt();
        name = _buf.ReadString();
        unlockScore = _buf.ReadInt();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);parameter = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); parameter[__index0] = __e0;}}
        atlasID = _buf.ReadInt();
        itemIcon = _buf.ReadString();
        itemNameId = _buf.ReadString();
        bg = _buf.ReadString();
        openTime = _buf.ReadString();
        endTime = _buf.ReadString();
        group = _buf.ReadInt();
        rankID = _buf.ReadInt();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);rewardShow = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); rewardShow[__index0] = __e0;}}
        robotNum = _buf.ReadInt();
        robotScore = _buf.ReadString();
    }

    public static ChapterActivity_RankActivity DeserializeChapterActivity_RankActivity(ByteBuf _buf)
    {
        return new ChapterActivity_RankActivity(_buf);
    }

    /// <summary>
    /// 编号
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 活动名称多语言
    /// </summary>
    public readonly string name;
    /// <summary>
    /// 解锁分数
    /// </summary>
    public readonly int unlockScore;
    /// <summary>
    /// 活动事件参数
    /// </summary>
    public readonly string[] parameter;
    /// <summary>
    /// 图集名称
    /// </summary>
    public readonly int atlasID;
    /// <summary>
    /// 活动道具图标
    /// </summary>
    public readonly string itemIcon;
    /// <summary>
    /// 活动道具多语言ID
    /// </summary>
    public readonly string itemNameId;
    /// <summary>
    /// 背景图
    /// </summary>
    public readonly string bg;
    /// <summary>
    /// 开始时间
    /// </summary>
    public readonly string openTime;
    /// <summary>
    /// 结束时间
    /// </summary>
    public readonly string endTime;
    /// <summary>
    /// 对应条目组
    /// </summary>
    public readonly int group;
    /// <summary>
    /// 排行榜ID<br/>排行榜活动用
    /// </summary>
    public readonly int rankID;
    /// <summary>
    /// 大奖预览<br/>客户端用
    /// </summary>
    public readonly string[] rewardShow;
    /// <summary>
    /// 排行榜机器人数量
    /// </summary>
    public readonly int robotNum;
    /// <summary>
    /// 机器人积分范围
    /// </summary>
    public readonly string robotScore;
   
    public const int __ID__ = -280642434;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "name:" + name + ","
        + "unlockScore:" + unlockScore + ","
        + "parameter:" + Luban.StringUtil.CollectionToString(parameter) + ","
        + "atlasID:" + atlasID + ","
        + "itemIcon:" + itemIcon + ","
        + "itemNameId:" + itemNameId + ","
        + "bg:" + bg + ","
        + "openTime:" + openTime + ","
        + "endTime:" + endTime + ","
        + "group:" + group + ","
        + "rankID:" + rankID + ","
        + "rewardShow:" + Luban.StringUtil.CollectionToString(rewardShow) + ","
        + "robotNum:" + robotNum + ","
        + "robotScore:" + robotScore + ","
        + "}";
    }
}

}

