
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
public sealed partial class DailyLevel_dailyLevelBase : Luban.BeanBase
{
    public DailyLevel_dailyLevelBase(ByteBuf _buf) 
    {
        id = _buf.ReadInt();
        StartTime = _buf.ReadString();
        EndTime = _buf.ReadString();
        resetTime = _buf.ReadInt();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);entrys = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); entrys[__index0] = __e0;}}
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);chapterID = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); chapterID[__index0] = __e0;}}
        freeCnt = _buf.ReadInt();
        buyCnt = _buf.ReadInt();
        buyDiamonds = _buf.ReadInt();
        banner = _buf.ReadString();
        mailId = _buf.ReadString();
        rankMailId = _buf.ReadString();
    }

    public static DailyLevel_dailyLevelBase DeserializeDailyLevel_dailyLevelBase(ByteBuf _buf)
    {
        return new DailyLevel_dailyLevelBase(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 活动<br/>开启时间戳
    /// </summary>
    public readonly string StartTime;
    /// <summary>
    /// 结束时间戳
    /// </summary>
    public readonly string EndTime;
    /// <summary>
    /// 重置次数重置时间（秒）<br/>2天
    /// </summary>
    public readonly int resetTime;
    /// <summary>
    /// 词条|<br/>第一期|……
    /// </summary>
    public readonly string[] entrys;
    /// <summary>
    /// 引用主线ID<br/>从第1个循环<br/>主线相关的都读Chapter表
    /// </summary>
    public readonly int[] chapterID;
    /// <summary>
    /// 免费次数
    /// </summary>
    public readonly int freeCnt;
    /// <summary>
    /// 可购买次数(0不可购买)
    /// </summary>
    public readonly int buyCnt;
    /// <summary>
    /// 购买次数需要的宝石数量
    /// </summary>
    public readonly int buyDiamonds;
    /// <summary>
    /// banner
    /// </summary>
    public readonly string banner;
    /// <summary>
    /// 奖励补发邮件
    /// </summary>
    public readonly string mailId;
    /// <summary>
    /// 段位奖励邮件
    /// </summary>
    public readonly string rankMailId;
   
    public const int __ID__ = -1291843568;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "StartTime:" + StartTime + ","
        + "EndTime:" + EndTime + ","
        + "resetTime:" + resetTime + ","
        + "entrys:" + Luban.StringUtil.CollectionToString(entrys) + ","
        + "chapterID:" + Luban.StringUtil.CollectionToString(chapterID) + ","
        + "freeCnt:" + freeCnt + ","
        + "buyCnt:" + buyCnt + ","
        + "buyDiamonds:" + buyDiamonds + ","
        + "banner:" + banner + ","
        + "mailId:" + mailId + ","
        + "rankMailId:" + rankMailId + ","
        + "}";
    }
}

}

