
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
public sealed partial class EventFishing_fishArea : Luban.BeanBase
{
    public EventFishing_fishArea(ByteBuf _buf) 
    {
        id = _buf.ReadInt();
        nameId = _buf.ReadString();
        path = _buf.ReadString();
    }

    public static EventFishing_fishArea DeserializeEventFishing_fishArea(ByteBuf _buf)
    {
        return new EventFishing_fishArea(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 名字多语言
    /// </summary>
    public readonly string nameId;
    /// <summary>
    /// 地图资源
    /// </summary>
    public readonly string path;
   
    public const int __ID__ = -2017432652;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "nameId:" + nameId + ","
        + "path:" + path + ","
        + "}";
    }
}

}

