
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
public sealed partial class Guild_guildEvent : Luban.BeanBase
{
    public Guild_guildEvent(ByteBuf _buf) 
    {
        id = _buf.ReadInt();
        name = _buf.ReadInt();
        eventLanguage = _buf.ReadInt();
        eventAtlas = _buf.ReadString();
        eventShow = _buf.ReadString();
        eventSort = _buf.ReadInt();
    }

    public static Guild_guildEvent DeserializeGuild_guildEvent(ByteBuf _buf)
    {
        return new Guild_guildEvent(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 活动名称多语言
    /// </summary>
    public readonly int name;
    /// <summary>
    /// 描述文本
    /// </summary>
    public readonly int eventLanguage;
    /// <summary>
    /// 图集
    /// </summary>
    public readonly string eventAtlas;
    /// <summary>
    /// 入口图片
    /// </summary>
    public readonly string eventShow;
    /// <summary>
    /// 排序
    /// </summary>
    public readonly int eventSort;
   
    public const int __ID__ = -835371437;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "name:" + name + ","
        + "eventLanguage:" + eventLanguage + ","
        + "eventAtlas:" + eventAtlas + ","
        + "eventShow:" + eventShow + ","
        + "eventSort:" + eventSort + ","
        + "}";
    }
}

}

