
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
public sealed partial class IntegralShop_data : Luban.BeanBase
{
    public IntegralShop_data(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        NameID = _buf.ReadString();
        currencyID = _buf.ReadInt();
        LevelRequirements = _buf.ReadInt();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);RefreshCost = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); RefreshCost[__index0] = __e0;}}
    }

    public static IntegralShop_data DeserializeIntegralShop_data(ByteBuf _buf)
    {
        return new IntegralShop_data(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 商店名称多语言
    /// </summary>
    public readonly string NameID;
    /// <summary>
    /// 货币类型
    /// </summary>
    public readonly int currencyID;
    /// <summary>
    /// 解锁关卡
    /// </summary>
    public readonly int LevelRequirements;
    /// <summary>
    /// 手动刷新消耗钻石
    /// </summary>
    public readonly int[] RefreshCost;
   
    public const int __ID__ = -1735957785;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "NameID:" + NameID + ","
        + "currencyID:" + currencyID + ","
        + "LevelRequirements:" + LevelRequirements + ","
        + "RefreshCost:" + Luban.StringUtil.CollectionToString(RefreshCost) + ","
        + "}";
    }
}

}

