
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
public sealed partial class Item_battle : Luban.BeanBase
{
    public Item_battle(ByteBuf _buf) 
    {
        id = _buf.ReadInt();
        className = _buf.ReadString();
        parameter = _buf.ReadInt();
        prefabId = _buf.ReadInt();
    }

    public static Item_battle DeserializeItem_battle(ByteBuf _buf)
    {
        return new Item_battle(_buf);
    }

    /// <summary>
    /// 必须有的ID
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 类名
    /// </summary>
    public readonly string className;
    /// <summary>
    /// 数值<br/>比如：经验值
    /// </summary>
    public readonly int parameter;
    /// <summary>
    /// 战斗中掉落的道具id<br/>看GameArt_Battle表格
    /// </summary>
    public readonly int prefabId;
   
    public const int __ID__ = 781610820;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "className:" + className + ","
        + "parameter:" + parameter + ","
        + "prefabId:" + prefabId + ","
        + "}";
    }
}

}

