
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
public sealed partial class Mining_oreRes : Luban.BeanBase
{
    public Mining_oreRes(ByteBuf _buf) 
    {
        id = _buf.ReadInt();
        atlas = _buf.ReadInt();
        icon = _buf.ReadString();
        languageId = _buf.ReadString();
        desId = _buf.ReadString();
        model = _buf.ReadInt();
        uptimes = _buf.ReadInt();
        knock = _buf.ReadInt();
        isShowknock = _buf.ReadInt();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);qualityRandom = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); qualityRandom[__index0] = __e0;}}
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);iconOffset = new float[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { float __e0;__e0 = _buf.ReadFloat(); iconOffset[__index0] = __e0;}}
        iconScale = _buf.ReadFloat();
    }

    public static Mining_oreRes DeserializeMining_oreRes(ByteBuf _buf)
    {
        return new Mining_oreRes(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 图集
    /// </summary>
    public readonly int atlas;
    /// <summary>
    /// icon
    /// </summary>
    public readonly string icon;
    /// <summary>
    /// 名字多语言id
    /// </summary>
    public readonly string languageId;
    /// <summary>
    /// 描述多语言id
    /// </summary>
    public readonly string desId;
    /// <summary>
    /// 模型id
    /// </summary>
    public readonly int model;
    /// <summary>
    /// 可升级次数
    /// </summary>
    public readonly int uptimes;
    /// <summary>
    /// 敲击次数
    /// </summary>
    public readonly int knock;
    /// <summary>
    /// 是否显示敲击次数
    /// </summary>
    public readonly int isShowknock;
    /// <summary>
    /// 初始品质<br/>（品质1,权重|...)
    /// </summary>
    public readonly string[] qualityRandom;
    /// <summary>
    /// 宝藏icon相对格子形状的起始位置的偏移<br/>(格子从左上角开始，第一个为起始位置）
    /// </summary>
    public readonly float[] iconOffset;
    /// <summary>
    /// 宝藏icon缩放
    /// </summary>
    public readonly float iconScale;
   
    public const int __ID__ = -134592243;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "atlas:" + atlas + ","
        + "icon:" + icon + ","
        + "languageId:" + languageId + ","
        + "desId:" + desId + ","
        + "model:" + model + ","
        + "uptimes:" + uptimes + ","
        + "knock:" + knock + ","
        + "isShowknock:" + isShowknock + ","
        + "qualityRandom:" + Luban.StringUtil.CollectionToString(qualityRandom) + ","
        + "iconOffset:" + Luban.StringUtil.CollectionToString(iconOffset) + ","
        + "iconScale:" + iconScale + ","
        + "}";
    }
}

}

