
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
public sealed partial class MythicDungeon_mythicBookShow : Luban.BeanBase
{
    public MythicDungeon_mythicBookShow(ByteBuf _buf) 
    {
        id = _buf.ReadInt();
        nameId = _buf.ReadString();
        detailNameId = _buf.ReadString();
        atlasId = _buf.ReadInt();
        spriteName = _buf.ReadString();
        itemBg = _buf.ReadString();
        quaAtlasId = _buf.ReadInt();
        quaSpriteName = _buf.ReadString();
    }

    public static MythicDungeon_mythicBookShow DeserializeMythicDungeon_mythicBookShow(ByteBuf _buf)
    {
        return new MythicDungeon_mythicBookShow(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 组名
    /// </summary>
    public readonly string nameId;
    /// <summary>
    /// 详情名称
    /// </summary>
    public readonly string detailNameId;
    /// <summary>
    /// 图集id
    /// </summary>
    public readonly int atlasId;
    /// <summary>
    /// 图标id
    /// </summary>
    public readonly string spriteName;
    /// <summary>
    /// item背景图标
    /// </summary>
    public readonly string itemBg;
    /// <summary>
    /// 品质图集id
    /// </summary>
    public readonly int quaAtlasId;
    /// <summary>
    /// 品质图标id
    /// </summary>
    public readonly string quaSpriteName;
   
    public const int __ID__ = -1818196737;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "nameId:" + nameId + ","
        + "detailNameId:" + detailNameId + ","
        + "atlasId:" + atlasId + ","
        + "spriteName:" + spriteName + ","
        + "itemBg:" + itemBg + ","
        + "quaAtlasId:" + quaAtlasId + ","
        + "quaSpriteName:" + quaSpriteName + ","
        + "}";
    }
}

}

