
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
public sealed partial class ProbabilityDisplay_Probability : Luban.BeanBase
{
    public ProbabilityDisplay_Probability(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        DisplayType = _buf.ReadInt();
        Title = _buf.ReadString();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);probabilities = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); probabilities[__index0] = __e0;}}
        ItemLabel = _buf.ReadString();
        StrLabel = _buf.ReadString();
        probabilitiesStr = _buf.ReadString();
    }

    public static ProbabilityDisplay_Probability DeserializeProbabilityDisplay_Probability(ByteBuf _buf)
    {
        return new ProbabilityDisplay_Probability(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 展示样式:<br/>1 - 展示图标数量及概率<br/>2- 排列道具图标数量及文字描述
    /// </summary>
    public readonly int DisplayType;
    /// <summary>
    /// UI标题
    /// </summary>
    public readonly string Title;
    /// <summary>
    /// 展示概率<br/>道具ID,道具数量,概率千分比|…
    /// </summary>
    public readonly string[] probabilities;
    /// <summary>
    /// 道具列表标题的文本多语言ID<br/>[仅类型2]
    /// </summary>
    public readonly string ItemLabel;
    /// <summary>
    /// 文本标题的多语言ID<br/>[仅类型2]
    /// </summary>
    public readonly string StrLabel;
    /// <summary>
    /// 概率公示文本的多语言ID<br/>[仅类型2]
    /// </summary>
    public readonly string probabilitiesStr;
   
    public const int __ID__ = -1536507453;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "DisplayType:" + DisplayType + ","
        + "Title:" + Title + ","
        + "probabilities:" + Luban.StringUtil.CollectionToString(probabilities) + ","
        + "ItemLabel:" + ItemLabel + ","
        + "StrLabel:" + StrLabel + ","
        + "probabilitiesStr:" + probabilitiesStr + ","
        + "}";
    }
}

}

