
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
public sealed partial class Sociality_Report : Luban.BeanBase
{
    public Sociality_Report(ByteBuf _buf) 
    {
        id = _buf.ReadInt();
        type = _buf.ReadInt();
        atlasID = _buf.ReadInt();
        bgName = _buf.ReadString();
        iconBgName = _buf.ReadString();
        iconName = _buf.ReadString();
        titleLanguage = _buf.ReadString();
        contentLanguage = _buf.ReadString();
        playBack = _buf.ReadInt();
    }

    public static Sociality_Report DeserializeSociality_Report(ByteBuf _buf)
    {
        return new Sociality_Report(_buf);
    }

    /// <summary>
    /// 内容ID
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 类型（1.征服战 2.竞技场）
    /// </summary>
    public readonly int type;
    /// <summary>
    /// 图集ID
    /// </summary>
    public readonly int atlasID;
    /// <summary>
    /// 底版图片
    /// </summary>
    public readonly string bgName;
    /// <summary>
    /// icon背景图片
    /// </summary>
    public readonly string iconBgName;
    /// <summary>
    /// icon图片
    /// </summary>
    public readonly string iconName;
    /// <summary>
    /// 标题多语言
    /// </summary>
    public readonly string titleLanguage;
    /// <summary>
    /// 内容多语言
    /// </summary>
    public readonly string contentLanguage;
    /// <summary>
    /// 是否具备回放
    /// </summary>
    public readonly int playBack;
   
    public const int __ID__ = -1385374382;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "type:" + type + ","
        + "atlasID:" + atlasID + ","
        + "bgName:" + bgName + ","
        + "iconBgName:" + iconBgName + ","
        + "iconName:" + iconName + ","
        + "titleLanguage:" + titleLanguage + ","
        + "contentLanguage:" + contentLanguage + ","
        + "playBack:" + playBack + ","
        + "}";
    }
}

}

