
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
/// <summary>
/// Generated from ActivityTurntable.xlsx sheet TurntableQuest
/// </summary>
public partial class TbActivityTurntable_TurntableQuest
{
    private readonly System.Collections.Generic.Dictionary<int, ActivityTurntable_TurntableQuest> _dataMap;
    private readonly System.Collections.Generic.List<ActivityTurntable_TurntableQuest> _dataList;
    
    public TbActivityTurntable_TurntableQuest(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ActivityTurntable_TurntableQuest>();
        _dataList = new System.Collections.Generic.List<ActivityTurntable_TurntableQuest>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            ActivityTurntable_TurntableQuest _v;
            _v = global::HotFix.Cfg.ActivityTurntable_TurntableQuest.DeserializeActivityTurntable_TurntableQuest(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ActivityTurntable_TurntableQuest> DataMap => _dataMap;
    public System.Collections.Generic.List<ActivityTurntable_TurntableQuest> DataList => _dataList;

    public ActivityTurntable_TurntableQuest GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ActivityTurntable_TurntableQuest Get(int key) => _dataMap[key];
    public ActivityTurntable_TurntableQuest this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

