
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
/// <summary>
/// Generated from ActivityDan.xlsx sheet MonoBattlepassReward
/// </summary>
public partial class TbActivityDan_MonoBattlepassReward
{
    private readonly System.Collections.Generic.Dictionary<int, ActivityDan_MonoBattlepassReward> _dataMap;
    private readonly System.Collections.Generic.List<ActivityDan_MonoBattlepassReward> _dataList;
    
    public TbActivityDan_MonoBattlepassReward(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ActivityDan_MonoBattlepassReward>();
        _dataList = new System.Collections.Generic.List<ActivityDan_MonoBattlepassReward>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            ActivityDan_MonoBattlepassReward _v;
            _v = global::HotFix.Cfg.ActivityDan_MonoBattlepassReward.DeserializeActivityDan_MonoBattlepassReward(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ActivityDan_MonoBattlepassReward> DataMap => _dataMap;
    public System.Collections.Generic.List<ActivityDan_MonoBattlepassReward> DataList => _dataList;

    public ActivityDan_MonoBattlepassReward GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ActivityDan_MonoBattlepassReward Get(int key) => _dataMap[key];
    public ActivityDan_MonoBattlepassReward this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

