
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
/// <summary>
/// Generated from ArtSkill.xlsx sheet Skill
/// </summary>
public partial class TbArtSkill_Skill
{
    private readonly System.Collections.Generic.Dictionary<int, ArtSkill_Skill> _dataMap;
    private readonly System.Collections.Generic.List<ArtSkill_Skill> _dataList;
    
    public TbArtSkill_Skill(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ArtSkill_Skill>();
        _dataList = new System.Collections.Generic.List<ArtSkill_Skill>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            ArtSkill_Skill _v;
            _v = global::HotFix.Cfg.ArtSkill_Skill.DeserializeArtSkill_Skill(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ArtSkill_Skill> DataMap => _dataMap;
    public System.Collections.Generic.List<ArtSkill_Skill> DataList => _dataList;

    public ArtSkill_Skill GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ArtSkill_Skill Get(int key) => _dataMap[key];
    public ArtSkill_Skill this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

