
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
/// <summary>
/// Generated from Capsule.xlsx sheet GashaponBox
/// </summary>
public partial class TbCapsule_GashaponBox
{
    private readonly System.Collections.Generic.Dictionary<int, Capsule_GashaponBox> _dataMap;
    private readonly System.Collections.Generic.List<Capsule_GashaponBox> _dataList;
    
    public TbCapsule_GashaponBox(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Capsule_GashaponBox>();
        _dataList = new System.Collections.Generic.List<Capsule_GashaponBox>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Capsule_GashaponBox _v;
            _v = global::HotFix.Cfg.Capsule_GashaponBox.DeserializeCapsule_GashaponBox(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Capsule_GashaponBox> DataMap => _dataMap;
    public System.Collections.Generic.List<Capsule_GashaponBox> DataList => _dataList;

    public Capsule_GashaponBox GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Capsule_GashaponBox Get(int key) => _dataMap[key];
    public Capsule_GashaponBox this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

