
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
/// <summary>
/// Generated from DailyLevel.xlsx sheet dailyLevelConfig
/// </summary>
public partial class TbDailyLevel_dailyLevelConfig
{
    private readonly System.Collections.Generic.Dictionary<int, DailyLevel_dailyLevelConfig> _dataMap;
    private readonly System.Collections.Generic.List<DailyLevel_dailyLevelConfig> _dataList;
    
    public TbDailyLevel_dailyLevelConfig(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, DailyLevel_dailyLevelConfig>();
        _dataList = new System.Collections.Generic.List<DailyLevel_dailyLevelConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            DailyLevel_dailyLevelConfig _v;
            _v = global::HotFix.Cfg.DailyLevel_dailyLevelConfig.DeserializeDailyLevel_dailyLevelConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DailyLevel_dailyLevelConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<DailyLevel_dailyLevelConfig> DataList => _dataList;

    public DailyLevel_dailyLevelConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DailyLevel_dailyLevelConfig Get(int key) => _dataMap[key];
    public DailyLevel_dailyLevelConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

