
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
/// <summary>
/// Generated from EventFishing.xlsx sheet fishRod
/// </summary>
public partial class TbEventFishing_fishRod
{
    private readonly System.Collections.Generic.Dictionary<int, EventFishing_fishRod> _dataMap;
    private readonly System.Collections.Generic.List<EventFishing_fishRod> _dataList;
    
    public TbEventFishing_fishRod(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, EventFishing_fishRod>();
        _dataList = new System.Collections.Generic.List<EventFishing_fishRod>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            EventFishing_fishRod _v;
            _v = global::HotFix.Cfg.EventFishing_fishRod.DeserializeEventFishing_fishRod(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, EventFishing_fishRod> DataMap => _dataMap;
    public System.Collections.Generic.List<EventFishing_fishRod> DataList => _dataList;

    public EventFishing_fishRod GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public EventFishing_fishRod Get(int key) => _dataMap[key];
    public EventFishing_fishRod this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

