
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
/// <summary>
/// Generated from EventDive.xlsx sheet DiveInitialGrid
/// </summary>
public partial class TbEventDive_DiveInitialGrid
{
    private readonly System.Collections.Generic.Dictionary<int, EventDive_DiveInitialGrid> _dataMap;
    private readonly System.Collections.Generic.List<EventDive_DiveInitialGrid> _dataList;
    
    public TbEventDive_DiveInitialGrid(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, EventDive_DiveInitialGrid>();
        _dataList = new System.Collections.Generic.List<EventDive_DiveInitialGrid>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            EventDive_DiveInitialGrid _v;
            _v = global::HotFix.Cfg.EventDive_DiveInitialGrid.DeserializeEventDive_DiveInitialGrid(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, EventDive_DiveInitialGrid> DataMap => _dataMap;
    public System.Collections.Generic.List<EventDive_DiveInitialGrid> DataList => _dataList;

    public EventDive_DiveInitialGrid GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public EventDive_DiveInitialGrid Get(int key) => _dataMap[key];
    public EventDive_DiveInitialGrid this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

