
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
/// <summary>
/// Generated from Fishing.xlsx sheet fish
/// </summary>
public partial class TbFishing_fish
{
    private readonly System.Collections.Generic.Dictionary<int, Fishing_fish> _dataMap;
    private readonly System.Collections.Generic.List<Fishing_fish> _dataList;
    
    public TbFishing_fish(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Fishing_fish>();
        _dataList = new System.Collections.Generic.List<Fishing_fish>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Fishing_fish _v;
            _v = global::HotFix.Cfg.Fishing_fish.DeserializeFishing_fish(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Fishing_fish> DataMap => _dataMap;
    public System.Collections.Generic.List<Fishing_fish> DataList => _dataList;

    public Fishing_fish GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Fishing_fish Get(int key) => _dataMap[key];
    public Fishing_fish this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

