
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
/// <summary>
/// Generated from Fishing.xlsx sheet fishing
/// </summary>
public partial class TbFishing_fishing
{
    private readonly System.Collections.Generic.Dictionary<int, Fishing_fishing> _dataMap;
    private readonly System.Collections.Generic.List<Fishing_fishing> _dataList;
    
    public TbFishing_fishing(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Fishing_fishing>();
        _dataList = new System.Collections.Generic.List<Fishing_fishing>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Fishing_fishing _v;
            _v = global::HotFix.Cfg.Fishing_fishing.DeserializeFishing_fishing(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Fishing_fishing> DataMap => _dataMap;
    public System.Collections.Generic.List<Fishing_fishing> DataList => _dataList;

    public Fishing_fishing GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Fishing_fishing Get(int key) => _dataMap[key];
    public Fishing_fishing this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

