
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
/// <summary>
/// Generated from GuildBOSS.xlsx sheet guildBossStep
/// </summary>
public partial class TbGuildBOSS_guildBossStep
{
    private readonly System.Collections.Generic.Dictionary<int, GuildBOSS_guildBossStep> _dataMap;
    private readonly System.Collections.Generic.List<GuildBOSS_guildBossStep> _dataList;
    
    public TbGuildBOSS_guildBossStep(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, GuildBOSS_guildBossStep>();
        _dataList = new System.Collections.Generic.List<GuildBOSS_guildBossStep>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            GuildBOSS_guildBossStep _v;
            _v = global::HotFix.Cfg.GuildBOSS_guildBossStep.DeserializeGuildBOSS_guildBossStep(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.BossLevel, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, GuildBOSS_guildBossStep> DataMap => _dataMap;
    public System.Collections.Generic.List<GuildBOSS_guildBossStep> DataList => _dataList;

    public GuildBOSS_guildBossStep GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GuildBOSS_guildBossStep Get(int key) => _dataMap[key];
    public GuildBOSS_guildBossStep this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

