
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
/// <summary>
/// Generated from MythicDungeon.xlsx sheet battleUpgrade
/// </summary>
public partial class TbMythicDungeon_battleUpgrade
{
    private readonly System.Collections.Generic.Dictionary<int, MythicDungeon_battleUpgrade> _dataMap;
    private readonly System.Collections.Generic.List<MythicDungeon_battleUpgrade> _dataList;
    
    public TbMythicDungeon_battleUpgrade(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, MythicDungeon_battleUpgrade>();
        _dataList = new System.Collections.Generic.List<MythicDungeon_battleUpgrade>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            MythicDungeon_battleUpgrade _v;
            _v = global::HotFix.Cfg.MythicDungeon_battleUpgrade.DeserializeMythicDungeon_battleUpgrade(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, MythicDungeon_battleUpgrade> DataMap => _dataMap;
    public System.Collections.Generic.List<MythicDungeon_battleUpgrade> DataList => _dataList;

    public MythicDungeon_battleUpgrade GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public MythicDungeon_battleUpgrade Get(int key) => _dataMap[key];
    public MythicDungeon_battleUpgrade this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

