
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
/// <summary>
/// Generated from ProbabilityDisplay.xlsx sheet Probability
/// </summary>
public partial class TbProbabilityDisplay_Probability
{
    private readonly System.Collections.Generic.Dictionary<int, ProbabilityDisplay_Probability> _dataMap;
    private readonly System.Collections.Generic.List<ProbabilityDisplay_Probability> _dataList;
    
    public TbProbabilityDisplay_Probability(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ProbabilityDisplay_Probability>();
        _dataList = new System.Collections.Generic.List<ProbabilityDisplay_Probability>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            ProbabilityDisplay_Probability _v;
            _v = global::HotFix.Cfg.ProbabilityDisplay_Probability.DeserializeProbabilityDisplay_Probability(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ProbabilityDisplay_Probability> DataMap => _dataMap;
    public System.Collections.Generic.List<ProbabilityDisplay_Probability> DataList => _dataList;

    public ProbabilityDisplay_Probability GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ProbabilityDisplay_Probability Get(int key) => _dataMap[key];
    public ProbabilityDisplay_Probability this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

