
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
/// <summary>
/// Generated from SevenDay.xlsx sheet SevenDayPay
/// </summary>
public partial class TbSevenDay_SevenDayPay
{
    private readonly System.Collections.Generic.Dictionary<int, SevenDay_SevenDayPay> _dataMap;
    private readonly System.Collections.Generic.List<SevenDay_SevenDayPay> _dataList;
    
    public TbSevenDay_SevenDayPay(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, SevenDay_SevenDayPay>();
        _dataList = new System.Collections.Generic.List<SevenDay_SevenDayPay>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            SevenDay_SevenDayPay _v;
            _v = global::HotFix.Cfg.SevenDay_SevenDayPay.DeserializeSevenDay_SevenDayPay(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, SevenDay_SevenDayPay> DataMap => _dataMap;
    public System.Collections.Generic.List<SevenDay_SevenDayPay> DataList => _dataList;

    public SevenDay_SevenDayPay GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SevenDay_SevenDayPay Get(int key) => _dataMap[key];
    public SevenDay_SevenDayPay this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

