
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
/// <summary>
/// Generated from Shop.xlsx sheet Shop
/// </summary>
public partial class TbShop_Shop
{
    private readonly System.Collections.Generic.Dictionary<int, Shop_Shop> _dataMap;
    private readonly System.Collections.Generic.List<Shop_Shop> _dataList;
    
    public TbShop_Shop(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Shop_Shop>();
        _dataList = new System.Collections.Generic.List<Shop_Shop>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Shop_Shop _v;
            _v = global::HotFix.Cfg.Shop_Shop.DeserializeShop_Shop(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Shop_Shop> DataMap => _dataMap;
    public System.Collections.Generic.List<Shop_Shop> DataList => _dataList;

    public Shop_Shop GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Shop_Shop Get(int key) => _dataMap[key];
    public Shop_Shop this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

