
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
/// <summary>
/// Generated from TalentLegacy.xlsx sheet talentLegacyEffect
/// </summary>
public partial class TbTalentLegacy_talentLegacyEffect
{
    private readonly System.Collections.Generic.Dictionary<int, TalentLegacy_talentLegacyEffect> _dataMap;
    private readonly System.Collections.Generic.List<TalentLegacy_talentLegacyEffect> _dataList;
    
    public TbTalentLegacy_talentLegacyEffect(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, TalentLegacy_talentLegacyEffect>();
        _dataList = new System.Collections.Generic.List<TalentLegacy_talentLegacyEffect>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            TalentLegacy_talentLegacyEffect _v;
            _v = global::HotFix.Cfg.TalentLegacy_talentLegacyEffect.DeserializeTalentLegacy_talentLegacyEffect(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, TalentLegacy_talentLegacyEffect> DataMap => _dataMap;
    public System.Collections.Generic.List<TalentLegacy_talentLegacyEffect> DataList => _dataList;

    public TalentLegacy_talentLegacyEffect GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TalentLegacy_talentLegacyEffect Get(int key) => _dataMap[key];
    public TalentLegacy_talentLegacyEffect this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

