
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
/// <summary>
/// Generated from TalentLegacy.xlsx sheet legacySkill
/// </summary>
public partial class TbTalentLegacy_legacySkill
{
    private readonly System.Collections.Generic.Dictionary<int, TalentLegacy_legacySkill> _dataMap;
    private readonly System.Collections.Generic.List<TalentLegacy_legacySkill> _dataList;
    
    public TbTalentLegacy_legacySkill(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, TalentLegacy_legacySkill>();
        _dataList = new System.Collections.Generic.List<TalentLegacy_legacySkill>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            TalentLegacy_legacySkill _v;
            _v = global::HotFix.Cfg.TalentLegacy_legacySkill.DeserializeTalentLegacy_legacySkill(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, TalentLegacy_legacySkill> DataMap => _dataMap;
    public System.Collections.Generic.List<TalentLegacy_legacySkill> DataList => _dataList;

    public TalentLegacy_legacySkill GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TalentLegacy_legacySkill Get(int key) => _dataMap[key];
    public TalentLegacy_legacySkill this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

