
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
/// <summary>
/// Generated from WorldBoss.xlsx sheet RankReward
/// </summary>
public partial class TbWorldBoss_RankReward
{
    private readonly System.Collections.Generic.Dictionary<int, WorldBoss_RankReward> _dataMap;
    private readonly System.Collections.Generic.List<WorldBoss_RankReward> _dataList;
    
    public TbWorldBoss_RankReward(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, WorldBoss_RankReward>();
        _dataList = new System.Collections.Generic.List<WorldBoss_RankReward>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            WorldBoss_RankReward _v;
            _v = global::HotFix.Cfg.WorldBoss_RankReward.DeserializeWorldBoss_RankReward(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, WorldBoss_RankReward> DataMap => _dataMap;
    public System.Collections.Generic.List<WorldBoss_RankReward> DataList => _dataList;

    public WorldBoss_RankReward GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public WorldBoss_RankReward Get(int key) => _dataMap[key];
    public WorldBoss_RankReward this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

