
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class ActivityDan_MonopolyPay : Luban.BeanBase
{
    public ActivityDan_MonopolyPay(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ID = (int)_obj.GetValue("ID");
        PurchaseId = (int)_obj.GetValue("PurchaseId");
        AdId = (int)_obj.GetValue("AdId");
        { var __json0 = _obj.GetValue("Price"); int _n0 = (__json0 as JArray).Count; Price = new string[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  Price[__index0++] = __v0; }   }
        ObjName = (string)_obj.GetValue("ObjName");
        objToplimit = (int)_obj.GetValue("objToplimit");
        { var __json0 = _obj.GetValue("ObjGoods"); int _n0 = (__json0 as JArray).Count; ObjGoods = new string[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  ObjGoods[__index0++] = __v0; }   }
        group = (int)_obj.GetValue("group");
    }

    public static ActivityDan_MonopolyPay DeserializeActivityDan_MonopolyPay(JToken _buf)
    {
        return new ActivityDan_MonopolyPay(_buf);
    }

    /// <summary>
    /// 编号
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 支付ID<br/>不配则直接领取
    /// </summary>
    public readonly int PurchaseId;
    /// <summary>
    /// 广告ID
    /// </summary>
    public readonly int AdId;
    /// <summary>
    /// 宝石购买
    /// </summary>
    public readonly string[] Price;
    /// <summary>
    /// 目标名称（多语言）
    /// </summary>
    public readonly string ObjName;
    /// <summary>
    /// 限购数量
    /// </summary>
    public readonly int objToplimit;
    /// <summary>
    /// 出售道具
    /// </summary>
    public readonly string[] ObjGoods;
    /// <summary>
    /// 组
    /// </summary>
    public readonly int group;


    public const int __ID__ = 1372406268;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "PurchaseId:" + PurchaseId + ","
        + "AdId:" + AdId + ","
        + "Price:" + Luban.StringUtil.CollectionToString(Price) + ","
        + "ObjName:" + ObjName + ","
        + "objToplimit:" + objToplimit + ","
        + "ObjGoods:" + Luban.StringUtil.CollectionToString(ObjGoods) + ","
        + "group:" + group + ","
        + "}";
    }
}
}

