
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
public sealed partial class ActvGeneral_ActivitySign : Luban.BeanBase
{
    public ActvGeneral_ActivitySign(ByteBuf _buf) 
    {
        id = _buf.ReadInt();
        SignID = _buf.ReadInt();
        Day = _buf.ReadInt();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);SignReward = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); SignReward[__index0] = __e0;}}
    }

    public static ActvGeneral_ActivitySign DeserializeActvGeneral_ActivitySign(ByteBuf _buf)
    {
        return new ActvGeneral_ActivitySign(_buf);
    }

    /// <summary>
    /// 编号
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 编号
    /// </summary>
    public readonly int SignID;
    /// <summary>
    /// 天数
    /// </summary>
    public readonly int Day;
    /// <summary>
    /// 签到奖励
    /// </summary>
    public readonly string[] SignReward;
   
    public const int __ID__ = -760935449;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "SignID:" + SignID + ","
        + "Day:" + Day + ","
        + "SignReward:" + Luban.StringUtil.CollectionToString(SignReward) + ","
        + "}";
    }
}

}

