
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class ArtHover_hoverText : Luban.BeanBase
{
    public ArtHover_hoverText(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        id = (int)_obj.GetValue("id");
        textId = (string)_obj.GetValue("textId");
        atlasId = (int)_obj.GetValue("atlasId");
        iconName = (string)_obj.GetValue("iconName");
    }

    public static ArtHover_hoverText DeserializeArtHover_hoverText(JToken _buf)
    {
        return new ArtHover_hoverText(_buf);
    }

    /// <summary>
    /// 内容ID
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 多语言Id
    /// </summary>
    public readonly string textId;
    /// <summary>
    /// 图集Id
    /// </summary>
    public readonly int atlasId;
    /// <summary>
    /// iconName
    /// </summary>
    public readonly string iconName;


    public const int __ID__ = -1986890621;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "textId:" + textId + ","
        + "atlasId:" + atlasId + ","
        + "iconName:" + iconName + ","
        + "}";
    }
}
}

