
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
public sealed partial class Artifact_artifactStage : Luban.BeanBase
{
    public Artifact_artifactStage(ByteBuf _buf) 
    {
        id = _buf.ReadInt();
        stage = _buf.ReadInt();
        model = _buf.ReadInt();
        itemId = _buf.ReadInt();
        attribute = _buf.ReadString();
        advanceUnlock = _buf.ReadInt();
        itemUnlock = _buf.ReadString();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);power = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); power[__index0] = __e0;}}
    }

    public static Artifact_artifactStage DeserializeArtifact_artifactStage(ByteBuf _buf)
    {
        return new Artifact_artifactStage(_buf);
    }

    /// <summary>
    /// 内容ID
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 阶数
    /// </summary>
    public readonly int stage;
    /// <summary>
    /// 模型
    /// </summary>
    public readonly int model;
    /// <summary>
    /// item表id<br/>（用于读取名称、icon等基础信息）
    /// </summary>
    public readonly int itemId;
    /// <summary>
    /// 升阶属性
    /// </summary>
    public readonly string attribute;
    /// <summary>
    /// 幻化解锁
    /// </summary>
    public readonly int advanceUnlock;
    /// <summary>
    /// 解锁后获得道具
    /// </summary>
    public readonly string itemUnlock;
    /// <summary>
    /// 层数2万分比战力<br/>层数3万分比战力<br/>（拥有增加战力）
    /// </summary>
    public readonly int[] power;
   
    public const int __ID__ = -524055361;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "stage:" + stage + ","
        + "model:" + model + ","
        + "itemId:" + itemId + ","
        + "attribute:" + attribute + ","
        + "advanceUnlock:" + advanceUnlock + ","
        + "itemUnlock:" + itemUnlock + ","
        + "power:" + Luban.StringUtil.CollectionToString(power) + ","
        + "}";
    }
}

}

