
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class AutoProcess_skill : Luban.BeanBase
{
    public AutoProcess_skill(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        id = (int)_obj.GetValue("id");
        SkillType = (int)_obj.GetValue("SkillType");
        SuitID = (int)_obj.GetValue("SuitID");
        SuitSkillID = (int)_obj.GetValue("SuitSkillID");
        { var __json0 = _obj.GetValue("skills"); int _n0 = (__json0 as JArray).Count; skills = new int[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  skills[__index0++] = __v0; }   }
    }

    public static AutoProcess_skill DeserializeAutoProcess_skill(JToken _buf)
    {
        return new AutoProcess_skill(_buf);
    }

    /// <summary>
    /// 必须有的ID
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 技能类型<br/>1.普通技能<br/>10.突破技能
    /// </summary>
    public readonly int SkillType;
    /// <summary>
    /// 套装id
    /// </summary>
    public readonly int SuitID;
    /// <summary>
    /// 套装技能id
    /// </summary>
    public readonly int SuitSkillID;
    /// <summary>
    /// 技能组
    /// </summary>
    public readonly int[] skills;


    public const int __ID__ = -868809998;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "SkillType:" + SkillType + ","
        + "SuitID:" + SuitID + ","
        + "SuitSkillID:" + SuitSkillID + ","
        + "skills:" + Luban.StringUtil.CollectionToString(skills) + ","
        + "}";
    }
}
}

