
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class BattleMain_chapter : Luban.BeanBase
{
    public BattleMain_chapter(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ID = (int)_obj.GetValue("ID");
        waveStartId = (int)_obj.GetValue("waveStartId");
        waveCount = (int)_obj.GetValue("waveCount");
    }

    public static BattleMain_chapter DeserializeBattleMain_chapter(JToken _buf)
    {
        return new BattleMain_chapter(_buf);
    }

    /// <summary>
    /// 关卡id
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 波数开始id
    /// </summary>
    public readonly int waveStartId;
    /// <summary>
    /// 波数
    /// </summary>
    public readonly int waveCount;


    public const int __ID__ = -369464129;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "waveStartId:" + waveStartId + ","
        + "waveCount:" + waveCount + ","
        + "}";
    }
}
}

