
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class BattleMain_skill : Luban.BeanBase
{
    public BattleMain_skill(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ID = (int)_obj.GetValue("ID");
        skillType = (int)_obj.GetValue("skillType");
        { var __json0 = _obj.GetValue("skillList"); int _n0 = (__json0 as JArray).Count; skillList = new int[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  skillList[__index0++] = __v0; }   }
        breakSkillId = (int)_obj.GetValue("breakSkillId");
    }

    public static BattleMain_skill DeserializeBattleMain_skill(JToken _buf)
    {
        return new BattleMain_skill(_buf);
    }

    /// <summary>
    /// 技能id
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 技能类型<br/>1：普通技能<br/>2：传奇技能
    /// </summary>
    public readonly int skillType;
    /// <summary>
    /// 技能id列表<br/>指向GameSkill_skill表格
    /// </summary>
    public readonly int[] skillList;
    /// <summary>
    /// 突破技能id<br/>指向GameSkill_skill表格
    /// </summary>
    public readonly int breakSkillId;


    public const int __ID__ = 1136275267;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "skillType:" + skillType + ","
        + "skillList:" + Luban.StringUtil.CollectionToString(skillList) + ","
        + "breakSkillId:" + breakSkillId + ","
        + "}";
    }
}
}

