
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class ChainPacks_ChainPacks : Luban.BeanBase
{
    public ChainPacks_ChainPacks(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        id = (int)_obj.GetValue("id");
        group = (int)_obj.GetValue("group");
        condition = (int)_obj.GetValue("condition");
        PurchaseId = (int)_obj.GetValue("PurchaseId");
        { var __json0 = _obj.GetValue("rewards"); int _n0 = (__json0 as JArray).Count; rewards = new string[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  rewards[__index0++] = __v0; }   }
    }

    public static ChainPacks_ChainPacks DeserializeChainPacks_ChainPacks(JToken _buf)
    {
        return new ChainPacks_ChainPacks(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 礼包组<br/>(0没有组）
    /// </summary>
    public readonly int group;
    /// <summary>
    /// 前置条件
    /// </summary>
    public readonly int condition;
    /// <summary>
    /// 支付ID<br/>不配则直接领取
    /// </summary>
    public readonly int PurchaseId;
    /// <summary>
    /// 当即奖励<br/>itemid,count,showCount|itemid,count,,showCount
    /// </summary>
    public readonly string[] rewards;


    public const int __ID__ = -551128065;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "group:" + group + ","
        + "condition:" + condition + ","
        + "PurchaseId:" + PurchaseId + ","
        + "rewards:" + Luban.StringUtil.CollectionToString(rewards) + ","
        + "}";
    }
}
}

