
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class ChapterHard_eventRes : Luban.BeanBase
{
    public ChapterHard_eventRes(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        id = (int)_obj.GetValue("id");
        type = (int)_obj.GetValue("type");
        weight = (int)_obj.GetValue("weight");
        eventPointId = (int)_obj.GetValue("eventPointId");
        memberId = (int)_obj.GetValue("memberId");
        buildId = (int)_obj.GetValue("buildId");
    }

    public static ChapterHard_eventRes DeserializeChapterHard_eventRes(JToken _buf)
    {
        return new ChapterHard_eventRes(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly int type;
    /// <summary>
    /// 权重
    /// </summary>
    public readonly int weight;
    /// <summary>
    /// 资源事件ID
    /// </summary>
    public readonly int eventPointId;
    /// <summary>
    /// member表id（ui用）
    /// </summary>
    public readonly int memberId;
    /// <summary>
    /// 技能池id
    /// </summary>
    public readonly int buildId;


    public const int __ID__ = 4318541;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "type:" + type + ","
        + "weight:" + weight + ","
        + "eventPointId:" + eventPointId + ","
        + "memberId:" + memberId + ","
        + "buildId:" + buildId + ","
        + "}";
    }
}
}

