
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class ChapterHard_eventType : Luban.BeanBase
{
    public ChapterHard_eventType(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        id = (int)_obj.GetValue("id");
        gameEventType = (int)_obj.GetValue("gameEventType");
        { var __json0 = _obj.GetValue("events"); int _n0 = (__json0 as JArray).Count; events = new int[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  events[__index0++] = __v0; }   }
    }

    public static ChapterHard_eventType DeserializeChapterHard_eventType(JToken _buf)
    {
        return new ChapterHard_eventType(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 事件类型<br/>1-战斗 2-事件
    /// </summary>
    public readonly int gameEventType;
    /// <summary>
    /// 对应eventRes表id<br/>1-对阵ID、2-事件ID
    /// </summary>
    public readonly int[] events;


    public const int __ID__ = 133953581;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "gameEventType:" + gameEventType + ","
        + "events:" + Luban.StringUtil.CollectionToString(events) + ","
        + "}";
    }
}
}

