
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
public sealed partial class ChapterActivity_ChapterActivity : Luban.BeanBase
{
    public ChapterActivity_ChapterActivity(ByteBuf _buf) 
    {
        id = _buf.ReadInt();
        name = _buf.ReadString();
        type = _buf.ReadInt();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);parameter = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); parameter[__index0] = __e0;}}
        atlasID = _buf.ReadInt();
        itemIcon = _buf.ReadString();
        itemNameId = _buf.ReadString();
        banner = _buf.ReadString();
        openTime = _buf.ReadString();
        endTime = _buf.ReadString();
        group = _buf.ReadInt();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);rewardShow = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); rewardShow[__index0] = __e0;}}
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);modelShow = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); modelShow[__index0] = __e0;}}
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);scoreShow = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); scoreShow[__index0] = __e0;}}
    }

    public static ChapterActivity_ChapterActivity DeserializeChapterActivity_ChapterActivity(ByteBuf _buf)
    {
        return new ChapterActivity_ChapterActivity(_buf);
    }

    /// <summary>
    /// 编号
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 活动名称多语言
    /// </summary>
    public readonly string name;
    /// <summary>
    /// 活动类型<br/>1-新增事件<br/>2-现有事件<br/>3-指定事件对应结果
    /// </summary>
    public readonly int type;
    /// <summary>
    /// 活动事件参数
    /// </summary>
    public readonly string[] parameter;
    /// <summary>
    /// 图集名称
    /// </summary>
    public readonly int atlasID;
    /// <summary>
    /// 活动道具图标
    /// </summary>
    public readonly string itemIcon;
    /// <summary>
    /// 活动道具多语言ID
    /// </summary>
    public readonly string itemNameId;
    /// <summary>
    /// 活动banner图
    /// </summary>
    public readonly string banner;
    /// <summary>
    /// 开始时间
    /// </summary>
    public readonly string openTime;
    /// <summary>
    /// 结束时间
    /// </summary>
    public readonly string endTime;
    /// <summary>
    /// 对应条目组
    /// </summary>
    public readonly int group;
    /// <summary>
    /// 大奖预览<br/>客户端用
    /// </summary>
    public readonly string[] rewardShow;
    /// <summary>
    /// 展示模型<br/>model表id
    /// </summary>
    public readonly int[] modelShow;
    /// <summary>
    /// 展示积分
    /// </summary>
    public readonly int[] scoreShow;
   
    public const int __ID__ = -1429276039;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "name:" + name + ","
        + "type:" + type + ","
        + "parameter:" + Luban.StringUtil.CollectionToString(parameter) + ","
        + "atlasID:" + atlasID + ","
        + "itemIcon:" + itemIcon + ","
        + "itemNameId:" + itemNameId + ","
        + "banner:" + banner + ","
        + "openTime:" + openTime + ","
        + "endTime:" + endTime + ","
        + "group:" + group + ","
        + "rewardShow:" + Luban.StringUtil.CollectionToString(rewardShow) + ","
        + "modelShow:" + Luban.StringUtil.CollectionToString(modelShow) + ","
        + "scoreShow:" + Luban.StringUtil.CollectionToString(scoreShow) + ","
        + "}";
    }
}

}

