
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class ChapterMiniGame_slotBase : Luban.BeanBase
{
    public ChapterMiniGame_slotBase(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        id = (int)_obj.GetValue("id");
        { var __json0 = _obj.GetValue("slotIds"); int _n0 = (__json0 as JArray).Count; slotIds = new int[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  slotIds[__index0++] = __v0; }   }
        spinTimes = (int)_obj.GetValue("spinTimes");
        weight0 = (int)_obj.GetValue("weight0");
    }

    public static ChapterMiniGame_slotBase DeserializeChapterMiniGame_slotBase(JToken _buf)
    {
        return new ChapterMiniGame_slotBase(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int id;
    /// <summary>
    /// slotIds
    /// </summary>
    public readonly int[] slotIds;
    /// <summary>
    /// 老虎机次数
    /// </summary>
    public readonly int spinTimes;
    /// <summary>
    /// 空奖励权重
    /// </summary>
    public readonly int weight0;


    public const int __ID__ = -630265896;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "slotIds:" + Luban.StringUtil.CollectionToString(slotIds) + ","
        + "spinTimes:" + spinTimes + ","
        + "weight0:" + weight0 + ","
        + "}";
    }
}
}

