
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
public sealed partial class Chapter_attributeBuild : Luban.BeanBase
{
    public Chapter_attributeBuild(ByteBuf _buf) 
    {
        id = _buf.ReadInt();
        atlasId = _buf.ReadInt();
        icon = _buf.ReadString();
        attributes = _buf.ReadString();
        weight = _buf.ReadInt();
    }

    public static Chapter_attributeBuild DeserializeChapter_attributeBuild(ByteBuf _buf)
    {
        return new Chapter_attributeBuild(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 图集id
    /// </summary>
    public readonly int atlasId;
    /// <summary>
    /// 图标
    /// </summary>
    public readonly string icon;
    /// <summary>
    /// 属性加成
    /// </summary>
    public readonly string attributes;
    /// <summary>
    /// 权重
    /// </summary>
    public readonly int weight;
   
    public const int __ID__ = 1275086724;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "atlasId:" + atlasId + ","
        + "icon:" + icon + ","
        + "attributes:" + attributes + ","
        + "weight:" + weight + ","
        + "}";
    }
}

}

