
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
public sealed partial class ChapterMiniGame_cardFlippingBase : Luban.BeanBase
{
    public ChapterMiniGame_cardFlippingBase(ByteBuf _buf) 
    {
        id = _buf.ReadInt();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);reward1 = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); reward1[__index0] = __e0;}}
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);iconRes1 = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); iconRes1[__index0] = __e0;}}
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);iconFrameRes1 = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); iconFrameRes1[__index0] = __e0;}}
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);reward2 = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); reward2[__index0] = __e0;}}
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);iconRes2 = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); iconRes2[__index0] = __e0;}}
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);iconFrameRes2 = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); iconFrameRes2[__index0] = __e0;}}
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);reward3 = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); reward3[__index0] = __e0;}}
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);iconRes3 = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); iconRes3[__index0] = __e0;}}
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);iconFrameRes3 = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); iconFrameRes3[__index0] = __e0;}}
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);weights = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); weights[__index0] = __e0;}}
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);rewardTextIds = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); rewardTextIds[__index0] = __e0;}}
        languageId = _buf.ReadString();
    }

    public static ChapterMiniGame_cardFlippingBase DeserializeChapterMiniGame_cardFlippingBase(ByteBuf _buf)
    {
        return new ChapterMiniGame_cardFlippingBase(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int id;
    /// <summary>
    /// (小奖)类型|参数
    /// </summary>
    public readonly string[] reward1;
    /// <summary>
    /// icon资源信息
    /// </summary>
    public readonly string[] iconRes1;
    /// <summary>
    /// 底框资源信息
    /// </summary>
    public readonly string[] iconFrameRes1;
    /// <summary>
    /// (中奖)类型|参数
    /// </summary>
    public readonly string[] reward2;
    /// <summary>
    /// icon资源信息
    /// </summary>
    public readonly string[] iconRes2;
    /// <summary>
    /// 底框资源信息
    /// </summary>
    public readonly string[] iconFrameRes2;
    /// <summary>
    /// (大奖)类型|参数
    /// </summary>
    public readonly string[] reward3;
    /// <summary>
    /// icon资源信息
    /// </summary>
    public readonly string[] iconRes3;
    /// <summary>
    /// 底框资源信息
    /// </summary>
    public readonly string[] iconFrameRes3;
    /// <summary>
    /// 权重
    /// </summary>
    public readonly int[] weights;
    /// <summary>
    /// 多语言
    /// </summary>
    public readonly string[] rewardTextIds;
    /// <summary>
    /// 事件多语言
    /// </summary>
    public readonly string languageId;
   
    public const int __ID__ = 1834067689;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "reward1:" + Luban.StringUtil.CollectionToString(reward1) + ","
        + "iconRes1:" + Luban.StringUtil.CollectionToString(iconRes1) + ","
        + "iconFrameRes1:" + Luban.StringUtil.CollectionToString(iconFrameRes1) + ","
        + "reward2:" + Luban.StringUtil.CollectionToString(reward2) + ","
        + "iconRes2:" + Luban.StringUtil.CollectionToString(iconRes2) + ","
        + "iconFrameRes2:" + Luban.StringUtil.CollectionToString(iconFrameRes2) + ","
        + "reward3:" + Luban.StringUtil.CollectionToString(reward3) + ","
        + "iconRes3:" + Luban.StringUtil.CollectionToString(iconRes3) + ","
        + "iconFrameRes3:" + Luban.StringUtil.CollectionToString(iconFrameRes3) + ","
        + "weights:" + Luban.StringUtil.CollectionToString(weights) + ","
        + "rewardTextIds:" + Luban.StringUtil.CollectionToString(rewardTextIds) + ","
        + "languageId:" + languageId + ","
        + "}";
    }
}

}

