
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
public sealed partial class ChristmasBoss_ChristmasBoss : Luban.BeanBase
{
    public ChristmasBoss_ChristmasBoss(ByteBuf _buf) 
    {
        id = _buf.ReadInt();
        monsterCfg = _buf.ReadInt();
        mapID = _buf.ReadInt();
        bgm = _buf.ReadInt();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);buffData = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); buffData[__index0] = __e0;}}
        bossId = _buf.ReadInt();
        uiScale = _buf.ReadFloat();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);offsetPos = new float[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { float __e0;__e0 = _buf.ReadFloat(); offsetPos[__index0] = __e0;}}
        speedAdd = _buf.ReadInt();
    }

    public static ChristmasBoss_ChristmasBoss DeserializeChristmasBoss_ChristmasBoss(ByteBuf _buf)
    {
        return new ChristmasBoss_ChristmasBoss(_buf);
    }

    /// <summary>
    /// BOSS iD
    /// </summary>
    public readonly int id;
    /// <summary>
    /// boss对阵ID
    /// </summary>
    public readonly int monsterCfg;
    /// <summary>
    /// 地图ID
    /// </summary>
    public readonly int mapID;
    /// <summary>
    /// bgm
    /// </summary>
    public readonly int bgm;
    /// <summary>
    /// 怪物信息<br/>攻击增益|防御增益|生命值增益
    /// </summary>
    public readonly string[] buffData;
    /// <summary>
    /// member表Id
    /// </summary>
    public readonly int bossId;
    /// <summary>
    /// UI模型缩放比例
    /// </summary>
    public readonly float uiScale;
    /// <summary>
    /// 偏移坐标(x,y)
    /// </summary>
    public readonly float[] offsetPos;
    /// <summary>
    /// 速度加成(万分比)
    /// </summary>
    public readonly int speedAdd;
   
    public const int __ID__ = -564033633;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "monsterCfg:" + monsterCfg + ","
        + "mapID:" + mapID + ","
        + "bgm:" + bgm + ","
        + "buffData:" + Luban.StringUtil.CollectionToString(buffData) + ","
        + "bossId:" + bossId + ","
        + "uiScale:" + uiScale + ","
        + "offsetPos:" + Luban.StringUtil.CollectionToString(offsetPos) + ","
        + "speedAdd:" + speedAdd + ","
        + "}";
    }
}

}

