
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
public sealed partial class Collection_collectionSuit : Luban.BeanBase
{
    public Collection_collectionSuit(ByteBuf _buf) 
    {
        id = _buf.ReadInt();
        suitId = _buf.ReadInt();
        suitNameId = _buf.ReadString();
        conditionType = _buf.ReadInt();
        conditionParam = _buf.ReadInt();
        conditonPrifixTextId = _buf.ReadString();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);collectionId = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); collectionId[__index0] = __e0;}}
        attributes = _buf.ReadString();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);power = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); power[__index0] = __e0;}}
    }

    public static Collection_collectionSuit DeserializeCollection_collectionSuit(ByteBuf _buf)
    {
        return new Collection_collectionSuit(_buf);
    }

    /// <summary>
    /// 套装id
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 套装id
    /// </summary>
    public readonly int suitId;
    /// <summary>
    /// 套装名称
    /// </summary>
    public readonly string suitNameId;
    /// <summary>
    /// 解锁类型<br/>1-星级解锁<br/>2-觉醒解锁
    /// </summary>
    public readonly int conditionType;
    /// <summary>
    /// 解锁参数
    /// </summary>
    public readonly int conditionParam;
    /// <summary>
    /// 套装属性前置多语言拼接
    /// </summary>
    public readonly string conditonPrifixTextId;
    /// <summary>
    /// 藏品ID
    /// </summary>
    public readonly int[] collectionId;
    /// <summary>
    /// 属性加成(增量值)
    /// </summary>
    public readonly string attributes;
    /// <summary>
    /// 层数2万分比战力<br/>层数3万分比战力<br/>（拥有增加战力）
    /// </summary>
    public readonly int[] power;
   
    public const int __ID__ = -1729429908;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "suitId:" + suitId + ","
        + "suitNameId:" + suitNameId + ","
        + "conditionType:" + conditionType + ","
        + "conditionParam:" + conditionParam + ","
        + "conditonPrifixTextId:" + conditonPrifixTextId + ","
        + "collectionId:" + Luban.StringUtil.CollectionToString(collectionId) + ","
        + "attributes:" + attributes + ","
        + "power:" + Luban.StringUtil.CollectionToString(power) + ","
        + "}";
    }
}

}

