
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class CommonActivity_DropObj : Luban.BeanBase
{
    public CommonActivity_DropObj(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("Id");
        ObjName = (string)_obj.GetValue("ObjName");
        ObjPrice1 = (int)_obj.GetValue("ObjPrice1");
        ObjPrice2 = (int)_obj.GetValue("ObjPrice2");
        { var __json0 = _obj.GetValue("ObjGoods"); int _n0 = (__json0 as JArray).Count; ObjGoods = new string[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  ObjGoods[__index0++] = __v0; }   }
    }

    public static CommonActivity_DropObj DeserializeCommonActivity_DropObj(JToken _buf)
    {
        return new CommonActivity_DropObj(_buf);
    }

    /// <summary>
    /// 编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 目标名称（多语言）
    /// </summary>
    public readonly string ObjName;
    /// <summary>
    /// 购买货币
    /// </summary>
    public readonly int ObjPrice1;
    /// <summary>
    /// 购买价格
    /// </summary>
    public readonly int ObjPrice2;
    /// <summary>
    /// 出售道具
    /// </summary>
    public readonly string[] ObjGoods;


    public const int __ID__ = -1190886813;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "ObjName:" + ObjName + ","
        + "ObjPrice1:" + ObjPrice1 + ","
        + "ObjPrice2:" + ObjPrice2 + ","
        + "ObjGoods:" + Luban.StringUtil.CollectionToString(ObjGoods) + ","
        + "}";
    }
}
}

