
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class CrossArena_CrossArenaLevel : Luban.BeanBase
{
    public CrossArena_CrossArenaLevel(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Level = (int)_obj.GetValue("Level");
        name = (string)_obj.GetValue("name");
        Notes = (string)_obj.GetValue("Notes");
        attributes = (string)_obj.GetValue("attributes");
        { var __json0 = _obj.GetValue("attributesNew"); int _n0 = (__json0 as JArray).Count; attributesNew = new string[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  attributesNew[__index0++] = __v0; }   }
        serverNum = (int)_obj.GetValue("serverNum");
        playerNum = (int)_obj.GetValue("playerNum");
        upPro = (int)_obj.GetValue("upPro");
        downPro = (int)_obj.GetValue("downPro");
        serverRange = (int)_obj.GetValue("serverRange");
    }

    public static CrossArena_CrossArenaLevel DeserializeCrossArena_CrossArenaLevel(JToken _buf)
    {
        return new CrossArena_CrossArenaLevel(_buf);
    }

    /// <summary>
    /// 段位id
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 多语言id
    /// </summary>
    public readonly string name;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Notes;
    /// <summary>
    /// 竞技场战斗额外附加属性
    /// </summary>
    public readonly string attributes;
    /// <summary>
    /// 竞技场战斗额外附加属性
    /// </summary>
    public readonly string[] attributesNew;
    /// <summary>
    /// 分服间隔
    /// </summary>
    public readonly int serverNum;
    /// <summary>
    /// 组内玩家人数
    /// </summary>
    public readonly int playerNum;
    /// <summary>
    /// 组内升级玩家比例<br/>以实际玩家数为基数
    /// </summary>
    public readonly int upPro;
    /// <summary>
    /// 组内降级玩家比例
    /// </summary>
    public readonly int downPro;
    /// <summary>
    /// 跨服范围列<br/><br/>serverList-serverRange -pveRange序号
    /// </summary>
    public readonly int serverRange;


    public const int __ID__ = -485836923;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Level:" + Level + ","
        + "name:" + name + ","
        + "Notes:" + Notes + ","
        + "attributes:" + attributes + ","
        + "attributesNew:" + Luban.StringUtil.CollectionToString(attributesNew) + ","
        + "serverNum:" + serverNum + ","
        + "playerNum:" + playerNum + ","
        + "upPro:" + upPro + ","
        + "downPro:" + downPro + ","
        + "serverRange:" + serverRange + ","
        + "}";
    }
}
}

