
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class CrossArena_CrossArena : Luban.BeanBase
{
    public CrossArena_CrossArena(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        id = (int)_obj.GetValue("id");
        ranktop = (int)_obj.GetValue("ranktop");
        rankbuttom = (int)_obj.GetValue("rankbuttom");
        baseWinScore = (int)_obj.GetValue("baseWinScore");
        baseLoseScore = (int)_obj.GetValue("baseLoseScore");
        addition = (float)_obj.GetValue("addition");
        { var __json0 = _obj.GetValue("winScoreSection"); int _n0 = (__json0 as JArray).Count; winScoreSection = new int[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  winScoreSection[__index0++] = __v0; }   }
        { var __json0 = _obj.GetValue("loseScoreSection"); int _n0 = (__json0 as JArray).Count; loseScoreSection = new int[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  loseScoreSection[__index0++] = __v0; }   }
        { var __json0 = _obj.GetValue("dailyRewards"); int _n0 = (__json0 as JArray).Count; dailyRewards = new string[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  dailyRewards[__index0++] = __v0; }   }
        { var __json0 = _obj.GetValue("seasonRewards"); int _n0 = (__json0 as JArray).Count; seasonRewards = new string[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  seasonRewards[__index0++] = __v0; }   }
    }

    public static CrossArena_CrossArena DeserializeCrossArena_CrossArena(JToken _buf)
    {
        return new CrossArena_CrossArena(_buf);
    }

    /// <summary>
    /// 内容ID
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 名次上限（含）
    /// </summary>
    public readonly int ranktop;
    /// <summary>
    /// 名次下限（含）
    /// </summary>
    public readonly int rankbuttom;
    /// <summary>
    /// 战胜基础加分
    /// </summary>
    public readonly int baseWinScore;
    /// <summary>
    /// 战败基础扣分
    /// </summary>
    public readonly int baseLoseScore;
    /// <summary>
    /// 双方分差加成比例
    /// </summary>
    public readonly float addition;
    /// <summary>
    /// 战胜加分区间
    /// </summary>
    public readonly int[] winScoreSection;
    /// <summary>
    /// 战败扣分区间
    /// </summary>
    public readonly int[] loseScoreSection;
    /// <summary>
    /// 日常奖励
    /// </summary>
    public readonly string[] dailyRewards;
    /// <summary>
    /// 赛季奖励
    /// </summary>
    public readonly string[] seasonRewards;


    public const int __ID__ = -1034738881;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "ranktop:" + ranktop + ","
        + "rankbuttom:" + rankbuttom + ","
        + "baseWinScore:" + baseWinScore + ","
        + "baseLoseScore:" + baseLoseScore + ","
        + "addition:" + addition + ","
        + "winScoreSection:" + Luban.StringUtil.CollectionToString(winScoreSection) + ","
        + "loseScoreSection:" + Luban.StringUtil.CollectionToString(loseScoreSection) + ","
        + "dailyRewards:" + Luban.StringUtil.CollectionToString(dailyRewards) + ","
        + "seasonRewards:" + Luban.StringUtil.CollectionToString(seasonRewards) + ","
        + "}";
    }
}
}

