
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class DailyLevel_dailyLevelConfig : Luban.BeanBase
{
    public DailyLevel_dailyLevelConfig(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        id = (int)_obj.GetValue("id");
        randGroup = (int)_obj.GetValue("randGroup");
        turntableID = (int)_obj.GetValue("turntableID");
        difficultyType = (int)_obj.GetValue("difficultyType");
        difficultyPara = (int)_obj.GetValue("difficultyPara");
        { var __json0 = _obj.GetValue("rewardStage"); int _n0 = (__json0 as JArray).Count; rewardStage = new int[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  rewardStage[__index0++] = __v0; }   }
        { var __json0 = _obj.GetValue("dropID"); int _n0 = (__json0 as JArray).Count; dropID = new int[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  dropID[__index0++] = __v0; }   }
        attributes = (string)_obj.GetValue("attributes");
        normalBattleAttr = (string)_obj.GetValue("normalBattleAttr");
        eliteBattleAttr = (string)_obj.GetValue("eliteBattleAttr");
        bossBattleAttr = (string)_obj.GetValue("bossBattleAttr");
        speedAdd = (int)_obj.GetValue("speedAdd");
    }

    public static DailyLevel_dailyLevelConfig DeserializeDailyLevel_dailyLevelConfig(JToken _buf)
    {
        return new DailyLevel_dailyLevelConfig(_buf);
    }

    /// <summary>
    /// 难度
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 排行榜组
    /// </summary>
    public readonly int randGroup;
    /// <summary>
    /// 转盘ID
    /// </summary>
    public readonly int turntableID;
    /// <summary>
    /// 1、天赋等级<br/>2、传承等级<br/>3、关卡进度
    /// </summary>
    public readonly int difficultyType;
    /// <summary>
    /// &gt;=天赋等级,传承等级<br/>&gt;=关卡进度
    /// </summary>
    public readonly int difficultyPara;
    /// <summary>
    /// 层数奖励
    /// </summary>
    public readonly int[] rewardStage;
    /// <summary>
    /// 奖励（对应奖励表）
    /// </summary>
    public readonly int[] dropID;
    /// <summary>
    /// 基础属性加成<br/>与章节的乘算
    /// </summary>
    public readonly string attributes;
    /// <summary>
    /// 普通三围战斗属性加成
    /// </summary>
    public readonly string normalBattleAttr;
    /// <summary>
    /// 精英三围战斗属性加成
    /// </summary>
    public readonly string eliteBattleAttr;
    /// <summary>
    /// boss三围战属性加成
    /// </summary>
    public readonly string bossBattleAttr;
    /// <summary>
    /// 速度加成(万分比)
    /// </summary>
    public readonly int speedAdd;


    public const int __ID__ = -174706495;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "randGroup:" + randGroup + ","
        + "turntableID:" + turntableID + ","
        + "difficultyType:" + difficultyType + ","
        + "difficultyPara:" + difficultyPara + ","
        + "rewardStage:" + Luban.StringUtil.CollectionToString(rewardStage) + ","
        + "dropID:" + Luban.StringUtil.CollectionToString(dropID) + ","
        + "attributes:" + attributes + ","
        + "normalBattleAttr:" + normalBattleAttr + ","
        + "eliteBattleAttr:" + eliteBattleAttr + ","
        + "bossBattleAttr:" + bossBattleAttr + ","
        + "speedAdd:" + speedAdd + ","
        + "}";
    }
}
}

