
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class DailyLevel_monsterEntry : Luban.BeanBase
{
    public DailyLevel_monsterEntry(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        id = (int)_obj.GetValue("id");
        weight = (int)_obj.GetValue("weight");
        type = (int)_obj.GetValue("type");
        actionType = (int)_obj.GetValue("actionType");
        entryParam = (string)_obj.GetValue("entryParam");
        nameId = (string)_obj.GetValue("nameId");
        desId = (string)_obj.GetValue("desId");
        atlasId = (int)_obj.GetValue("atlasId");
        icon = (string)_obj.GetValue("icon");
    }

    public static DailyLevel_monsterEntry DeserializeDailyLevel_monsterEntry(JToken _buf)
    {
        return new DailyLevel_monsterEntry(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 权重
    /// </summary>
    public readonly int weight;
    /// <summary>
    /// 词条分类<br/>1、增益<br/>2、减益
    /// </summary>
    public readonly int type;
    /// <summary>
    /// 词条类型<br/>1-技能<br/>2-技能数量-1
    /// </summary>
    public readonly int actionType;
    /// <summary>
    /// 词条参数<br/>type=1，技能id| 数组<br/>type=2，空
    /// </summary>
    public readonly string entryParam;
    /// <summary>
    /// 词条名
    /// </summary>
    public readonly string nameId;
    /// <summary>
    /// 词条描述
    /// </summary>
    public readonly string desId;
    /// <summary>
    /// icon图集
    /// </summary>
    public readonly int atlasId;
    /// <summary>
    /// icon
    /// </summary>
    public readonly string icon;


    public const int __ID__ = 1295305580;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "weight:" + weight + ","
        + "type:" + type + ","
        + "actionType:" + actionType + ","
        + "entryParam:" + entryParam + ","
        + "nameId:" + nameId + ","
        + "desId:" + desId + ","
        + "atlasId:" + atlasId + ","
        + "icon:" + icon + ","
        + "}";
    }
}
}

