
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
public sealed partial class Emoji_Emoji : Luban.BeanBase
{
    public Emoji_Emoji(ByteBuf _buf) 
    {
        id = _buf.ReadInt();
        notes = _buf.ReadString();
        group = _buf.ReadInt();
        languageid = _buf.ReadInt();
        path = _buf.ReadString();
        atlasId = _buf.ReadInt();
        icon = _buf.ReadString();
    }

    public static Emoji_Emoji DeserializeEmoji_Emoji(ByteBuf _buf)
    {
        return new Emoji_Emoji(_buf);
    }

    /// <summary>
    /// 内容ID
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 注释
    /// </summary>
    public readonly string notes;
    /// <summary>
    /// 多语言
    /// </summary>
    public readonly int group;
    /// <summary>
    /// 多语言
    /// </summary>
    public readonly int languageid;
    /// <summary>
    /// prefab路径
    /// </summary>
    public readonly string path;
    /// <summary>
    /// 缩略图图片图集
    /// </summary>
    public readonly int atlasId;
    /// <summary>
    /// 缩略图图片Icon
    /// </summary>
    public readonly string icon;
   
    public const int __ID__ = -899920179;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "notes:" + notes + ","
        + "group:" + group + ","
        + "languageid:" + languageid + ","
        + "path:" + path + ","
        + "atlasId:" + atlasId + ","
        + "icon:" + icon + ","
        + "}";
    }
}

}

