
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class EventDive_DiveSpeical : Luban.BeanBase
{
    public EventDive_DiveSpeical(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ID = (int)_obj.GetValue("ID");
        { var __json0 = _obj.GetValue("Parameter"); int _n0 = (__json0 as JArray).Count; Parameter = new string[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  Parameter[__index0++] = __v0; }   }
        { var __json0 = _obj.GetValue("reward"); int _n0 = (__json0 as JArray).Count; reward = new string[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  reward[__index0++] = __v0; }   }
        number = (int)_obj.GetValue("number");
    }

    public static EventDive_DiveSpeical DeserializeEventDive_DiveSpeical(JToken _buf)
    {
        return new EventDive_DiveSpeical(_buf);
    }

    /// <summary>
    /// ID<br/>1-水母道具<br/>2-手电筒道具<br/>3-炸弹道具<br/>4-连续奖励格<br/>5-海藻格子<br/>6-鲨鱼格子<br/>7-贝壳A<br/>8-贝壳B<br/>9-特殊奖励1
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 参数<br/>4连续奖励格：几个奖励，权重|<br/>5海藻格：几个奖励，权重|<br/>6鲨鱼格：鲨鱼血量
    /// </summary>
    public readonly string[] Parameter;
    /// <summary>
    /// 奖励池<br/>道具ID,道具数量,权重|…
    /// </summary>
    public readonly string[] reward;
    /// <summary>
    /// 权重
    /// </summary>
    public readonly int number;


    public const int __ID__ = 638512264;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Parameter:" + Luban.StringUtil.CollectionToString(Parameter) + ","
        + "reward:" + Luban.StringUtil.CollectionToString(reward) + ","
        + "number:" + number + ","
        + "}";
    }
}
}

