
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class FestivalTurntable_FestivalTurntable : Luban.BeanBase
{
    public FestivalTurntable_FestivalTurntable(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        id = (int)_obj.GetValue("id");
        openTime = (string)_obj.GetValue("openTime");
        endTime = (string)_obj.GetValue("endTime");
        openTimeCN = (string)_obj.GetValue("openTimeCN");
        endTimeCN = (string)_obj.GetValue("endTimeCN");
        shopGroup = (int)_obj.GetValue("shopGroup");
        payGroup = (int)_obj.GetValue("payGroup");
        { var __json0 = _obj.GetValue("gridType"); int _n0 = (__json0 as JArray).Count; gridType = new string[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  gridType[__index0++] = __v0; }   }
        atlasId = (int)_obj.GetValue("atlasId");
        priceId = (int)_obj.GetValue("priceId");
        singlePrice = (int)_obj.GetValue("singlePrice");
        tenPrice = (int)_obj.GetValue("tenPrice");
        { var __json0 = _obj.GetValue("poolTimes"); int _n0 = (__json0 as JArray).Count; poolTimes = new string[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  poolTimes[__index0++] = __v0; }   }
        { var __json0 = _obj.GetValue("pool"); int _n0 = (__json0 as JArray).Count; pool = new string[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  pool[__index0++] = __v0; }   }
        { var __json0 = _obj.GetValue("rate"); int _n0 = (__json0 as JArray).Count; rate = new string[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  rate[__index0++] = __v0; }   }
        { var __json0 = _obj.GetValue("showRate"); int _n0 = (__json0 as JArray).Count; showRate = new string[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  showRate[__index0++] = __v0; }   }
        { var __json0 = _obj.GetValue("showRateBig"); int _n0 = (__json0 as JArray).Count; showRateBig = new string[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  showRateBig[__index0++] = __v0; }   }
        miniPityCount = (int)_obj.GetValue("miniPityCount");
        miniPityRate = (int)_obj.GetValue("miniPityRate");
        { var __json0 = _obj.GetValue("limitItems"); int _n0 = (__json0 as JArray).Count; limitItems = new string[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  limitItems[__index0++] = __v0; }   }
        bigPityCount = (int)_obj.GetValue("bigPityCount");
        timesRewardID = (int)_obj.GetValue("timesRewardID");
        { var __json0 = _obj.GetValue("delItems"); int _n0 = (__json0 as JArray).Count; delItems = new string[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  delItems[__index0++] = __v0; }   }
        ProdMailTempId = (string)_obj.GetValue("ProdMailTempId");
        HasExchangeShop = (int)_obj.GetValue("HasExchangeShop");
        { var __json0 = _obj.GetValue("ShopRes"); int _n0 = (__json0 as JArray).Count; ShopRes = new int[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  ShopRes[__index0++] = __v0; }   }
        ShopObjBg = (string)_obj.GetValue("ShopObjBg");
        ShopTitleNameId = (string)_obj.GetValue("ShopTitleNameId");
        GiftBanner = (string)_obj.GetValue("GiftBanner");
        GameplayEndTime = (int)_obj.GetValue("GameplayEndTime");
    }

    public static FestivalTurntable_FestivalTurntable DeserializeFestivalTurntable_FestivalTurntable(JToken _buf)
    {
        return new FestivalTurntable_FestivalTurntable(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 开始时间
    /// </summary>
    public readonly string openTime;
    /// <summary>
    /// 结束时间
    /// </summary>
    public readonly string endTime;
    /// <summary>
    /// 开始时间
    /// </summary>
    public readonly string openTimeCN;
    /// <summary>
    /// 结束时间
    /// </summary>
    public readonly string endTimeCN;
    /// <summary>
    /// 商店组<br/>不配则无商店兑换
    /// </summary>
    public readonly int shopGroup;
    /// <summary>
    /// 礼包组<br/>不配则无商店兑换
    /// </summary>
    public readonly int payGroup;
    /// <summary>
    /// 格子类型<br/>0:普通<br/>1:小奖<br/>3:终极<br/>，前面类型<br/>，后面格子index<br/>
    /// </summary>
    public readonly string[] gridType;
    /// <summary>
    /// 图集id
    /// </summary>
    public readonly int atlasId;
    /// <summary>
    /// 消耗物品Id
    /// </summary>
    public readonly int priceId;
    /// <summary>
    /// 单抽消耗<br/>物品数量
    /// </summary>
    public readonly int singlePrice;
    /// <summary>
    /// 十连消耗<br/>物品数量
    /// </summary>
    public readonly int tenPrice;
    /// <summary>
    /// 抽取多少次切换池子
    /// </summary>
    public readonly string[] poolTimes;
    /// <summary>
    /// 池子
    /// </summary>
    public readonly string[] pool;
    /// <summary>
    /// 概率
    /// </summary>
    public readonly string[] rate;
    /// <summary>
    /// 展示概率(万分比)
    /// </summary>
    public readonly string[] showRate;
    /// <summary>
    /// 展示概率(万分比)
    /// </summary>
    public readonly string[] showRateBig;
    /// <summary>
    /// 小保底次数
    /// </summary>
    public readonly int miniPityCount;
    /// <summary>
    /// 小保底抽卡池|小保底重置池
    /// </summary>
    public readonly int miniPityRate;
    /// <summary>
    /// 小保底限定物品|限定次数
    /// </summary>
    public readonly string[] limitItems;
    /// <summary>
    /// 大保底次数
    /// </summary>
    public readonly int bigPityCount;
    /// <summary>
    /// 次数奖励ID
    /// </summary>
    public readonly int timesRewardID;
    /// <summary>
    /// 活动结束时，以下这些道具兑换为金币<br/>道具ID，金币数量|
    /// </summary>
    public readonly string[] delItems;
    /// <summary>
    /// 正式服奖励邮件
    /// </summary>
    public readonly string ProdMailTempId;
    /// <summary>
    /// 是否拥有兑换商店
    /// </summary>
    public readonly int HasExchangeShop;
    /// <summary>
    /// 商店组上展示的道具id列表
    /// </summary>
    public readonly int[] ShopRes;
    /// <summary>
    /// 商品背景图
    /// </summary>
    public readonly string ShopObjBg;
    /// <summary>
    /// 商店组名字Id
    /// </summary>
    public readonly string ShopTitleNameId;
    /// <summary>
    /// 礼包Banner图
    /// </summary>
    public readonly string GiftBanner;
    /// <summary>
    /// 服务器结束时间-几天为结束
    /// </summary>
    public readonly int GameplayEndTime;


    public const int __ID__ = -1341871437;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "openTime:" + openTime + ","
        + "endTime:" + endTime + ","
        + "openTimeCN:" + openTimeCN + ","
        + "endTimeCN:" + endTimeCN + ","
        + "shopGroup:" + shopGroup + ","
        + "payGroup:" + payGroup + ","
        + "gridType:" + Luban.StringUtil.CollectionToString(gridType) + ","
        + "atlasId:" + atlasId + ","
        + "priceId:" + priceId + ","
        + "singlePrice:" + singlePrice + ","
        + "tenPrice:" + tenPrice + ","
        + "poolTimes:" + Luban.StringUtil.CollectionToString(poolTimes) + ","
        + "pool:" + Luban.StringUtil.CollectionToString(pool) + ","
        + "rate:" + Luban.StringUtil.CollectionToString(rate) + ","
        + "showRate:" + Luban.StringUtil.CollectionToString(showRate) + ","
        + "showRateBig:" + Luban.StringUtil.CollectionToString(showRateBig) + ","
        + "miniPityCount:" + miniPityCount + ","
        + "miniPityRate:" + miniPityRate + ","
        + "limitItems:" + Luban.StringUtil.CollectionToString(limitItems) + ","
        + "bigPityCount:" + bigPityCount + ","
        + "timesRewardID:" + timesRewardID + ","
        + "delItems:" + Luban.StringUtil.CollectionToString(delItems) + ","
        + "ProdMailTempId:" + ProdMailTempId + ","
        + "HasExchangeShop:" + HasExchangeShop + ","
        + "ShopRes:" + Luban.StringUtil.CollectionToString(ShopRes) + ","
        + "ShopObjBg:" + ShopObjBg + ","
        + "ShopTitleNameId:" + ShopTitleNameId + ","
        + "GiftBanner:" + GiftBanner + ","
        + "GameplayEndTime:" + GameplayEndTime + ","
        + "}";
    }
}
}

