
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class FestivalTurntable_FestivalTurntableQuest : Luban.BeanBase
{
    public FestivalTurntable_FestivalTurntableQuest(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ID = (int)_obj.GetValue("ID");
        TaskType = (int)_obj.GetValue("TaskType");
        StatisticsType = (int)_obj.GetValue("StatisticsType");
        Need = (int)_obj.GetValue("Need");
        NeedOld = (int)_obj.GetValue("NeedOld");
        Describe = (string)_obj.GetValue("Describe");
        { var __json0 = _obj.GetValue("Reward"); int _n0 = (__json0 as JArray).Count; Reward = new string[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  Reward[__index0++] = __v0; }   }
        Jump = (int)_obj.GetValue("Jump");
    }

    public static FestivalTurntable_FestivalTurntableQuest DeserializeFestivalTurntable_FestivalTurntableQuest(JToken _buf)
    {
        return new FestivalTurntable_FestivalTurntableQuest(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 1,进行关卡挑战<br/>2.关卡进度达到XX<br/>3,进行一次装备合成<br/>6.进行一次装备强化<br/>7,挑战爬塔<br/>8，登录游戏<br/>9.爬塔通过XX塔<br/>10.战力达到XX<br/>11.参与竞技场<br/>12.竞技场结算时在前3名<br/>13.竞技场结算时排第1<br/>20;//黑市购买<br/>21;//开启宝箱<br/>22;//充值<br/>23;//抽宠物<br/>24;//宠物升星<br/>25;//藏品升星<br/>26;//抽装备<br/>27;打副本1 28;打副本2<br/>29;打副本3 30;打副本4<br/>31;//消耗体力<br/>32.宠物升级1次<br/>33:爬塔或地牢1次
    /// </summary>
    public readonly int TaskType;
    /// <summary>
    /// 统计类型<br/>0,非累加<br/>1,累加
    /// </summary>
    public readonly int StatisticsType;
    /// <summary>
    /// 完成要求
    /// </summary>
    public readonly int Need;
    /// <summary>
    /// 完成要求<br/>老版本<br/>11.5日之前的版本用
    /// </summary>
    public readonly int NeedOld;
    /// <summary>
    /// 多语言ID
    /// </summary>
    public readonly string Describe;
    /// <summary>
    /// 奖励领取
    /// </summary>
    public readonly string[] Reward;
    /// <summary>
    /// 1.主页<br/>2.装备页<br/>3.商店页<br/>5.爬塔<br/>6.竞技场<br/>10.主城工会<br/>20;黑市购买<br/>21;宝箱界面<br/>22;商店-每日礼包界面<br/>23;抽宠物界面<br/>24.宠物列表界面<br/>25;藏品界面<br/>26;商店-抽装备界面<br/>27;副本界面<br/>28.天赋界面
    /// </summary>
    public readonly int Jump;


    public const int __ID__ = 7681519;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "TaskType:" + TaskType + ","
        + "StatisticsType:" + StatisticsType + ","
        + "Need:" + Need + ","
        + "NeedOld:" + NeedOld + ","
        + "Describe:" + Describe + ","
        + "Reward:" + Luban.StringUtil.CollectionToString(Reward) + ","
        + "Jump:" + Jump + ","
        + "}";
    }
}
}

