
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
public sealed partial class GameMember_monsterMount : Luban.BeanBase
{
    public GameMember_monsterMount(ByteBuf _buf) 
    {
        id = _buf.ReadInt();
        modelID = _buf.ReadInt();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);addSkills = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); addSkills[__index0] = __e0;}}
        shareHpPercent = _buf.ReadInt();
        mountScale = _buf.ReadFloat();
    }

    public static GameMember_monsterMount DeserializeGameMember_monsterMount(ByteBuf _buf)
    {
        return new GameMember_monsterMount(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 坐骑模型ID
    /// </summary>
    public readonly int modelID;
    /// <summary>
    /// 技能数组
    /// </summary>
    public readonly int[] addSkills;
    /// <summary>
    /// 共享血量百分比
    /// </summary>
    public readonly int shareHpPercent;
    /// <summary>
    /// 模型大小
    /// </summary>
    public readonly float mountScale;
   
    public const int __ID__ = 323248242;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "modelID:" + modelID + ","
        + "addSkills:" + Luban.StringUtil.CollectionToString(addSkills) + ","
        + "shareHpPercent:" + shareHpPercent + ","
        + "mountScale:" + mountScale + ","
        + "}";
    }
}

}

