
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
public sealed partial class GameSkill_skillType : Luban.BeanBase
{
    public GameSkill_skillType(ByteBuf _buf) 
    {
        id = _buf.ReadInt();
        sClassName = _buf.ReadString();
        cClassName = _buf.ReadString();
    }

    public static GameSkill_skillType DeserializeGameSkill_skillType(ByteBuf _buf)
    {
        return new GameSkill_skillType(_buf);
    }

    /// <summary>
    /// 内容ID
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 服务器技能class
    /// </summary>
    public readonly string sClassName;
    /// <summary>
    /// 客户端技能class
    /// </summary>
    public readonly string cClassName;
   
    public const int __ID__ = 1733927499;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "sClassName:" + sClassName + ","
        + "cClassName:" + cClassName + ","
        + "}";
    }
}

}

