
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class GameSkill_fireBullet : Luban.BeanBase
{
    public GameSkill_fireBullet(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        id = (int)_obj.GetValue("id");
        skillBulletNameID = (int)_obj.GetValue("skillBulletNameID");
        bulletID = (int)_obj.GetValue("bulletID");
        showTpye = (int)_obj.GetValue("showTpye");
        bulletStartPosID = (int)_obj.GetValue("bulletStartPosID");
        bulletEndPosID = (int)_obj.GetValue("bulletEndPosID");
        bulletStartPrefabID = (int)_obj.GetValue("bulletStartPrefabID");
        bulletEndPrefabID = (int)_obj.GetValue("bulletEndPrefabID");
        bulletEndTargetPosPrefabID = (int)_obj.GetValue("bulletEndTargetPosPrefabID");
        bulletStartSoundID = (int)_obj.GetValue("bulletStartSoundID");
        bulletHitSoundID = (int)_obj.GetValue("bulletHitSoundID");
        { var __json0 = _obj.GetValue("hitPrefabIDs"); int _n0 = (__json0 as JArray).Count; hitPrefabIDs = new int[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  hitPrefabIDs[__index0++] = __v0; }   }
        hitPosID = (string)_obj.GetValue("hitPosID");
        hitEffectID = (int)_obj.GetValue("hitEffectID");
        hitStopType = (int)_obj.GetValue("hitStopType");
        hitStopDuration = (float)_obj.GetValue("hitStopDuration");
        hitStopDistance = (float)_obj.GetValue("hitStopDistance");
        hitStopSpeedParam = (float)_obj.GetValue("hitStopSpeedParam");
    }

    public static GameSkill_fireBullet DeserializeGameSkill_fireBullet(JToken _buf)
    {
        return new GameSkill_fireBullet(_buf);
    }

    /// <summary>
    /// 内容ID
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 子弹名字id
    /// </summary>
    public readonly int skillBulletNameID;
    /// <summary>
    /// 子弹ID（bullet表）
    /// </summary>
    public readonly int bulletID;
    /// <summary>
    /// 0:显示所有目标子弹<br/>1:只显示第一个目标子弹
    /// </summary>
    public readonly int showTpye;
    /// <summary>
    /// 子弹发射挂点
    /// </summary>
    public readonly int bulletStartPosID;
    /// <summary>
    /// 子弹命中挂点
    /// </summary>
    public readonly int bulletEndPosID;
    /// <summary>
    /// 子弹释放时prefabID（引自skillPrefab）<br/>填0则不生效
    /// </summary>
    public readonly int bulletStartPrefabID;
    /// <summary>
    /// 子弹击中目标位置prefabID,子弹射击方向（引自skillPrefab）<br/>填0则不生效
    /// </summary>
    public readonly int bulletEndPrefabID;
    /// <summary>
    /// 子弹击中目标脚下位置的prefabID,正方向（引自skillEffectPrefab）<br/>填0则不生效
    /// </summary>
    public readonly int bulletEndTargetPosPrefabID;
    /// <summary>
    /// 子弹创建音效
    /// </summary>
    public readonly int bulletStartSoundID;
    /// <summary>
    /// 子弹击中音效
    /// </summary>
    public readonly int bulletHitSoundID;
    /// <summary>
    /// 受击prefabID（引自ArtHit）<br/>填0则不生效<br/>石头|果冻|植物|骷髅
    /// </summary>
    public readonly int[] hitPrefabIDs;
    /// <summary>
    /// 受击发射挂点ID（看note表）<br/>0脚底<br/>1盆骨<br/>2中心<br/>3左手<br/>4右手<br/>5头<br/>6血条<br/>7头顶正上方<br/><br/>朝向：<br/>0、父级<br/>1、目标<br/>2、世界<br/>3、目标半径散射<br/><br/>以谁的朝向为标准<br/>0、受击者<br/>1、子弹<br/>2、攻击者
    /// </summary>
    public readonly string hitPosID;
    /// <summary>
    /// hitEffect表ID
    /// </summary>
    public readonly int hitEffectID;
    /// <summary>
    /// 子弹顿帧类型<br/>0 自己<br/>1 全局<br/>2 命中时
    /// </summary>
    public readonly int hitStopType;
    /// <summary>
    /// 子弹顿帧持续时间<br/>(秒）
    /// </summary>
    public readonly float hitStopDuration;
    /// <summary>
    /// 子弹顿帧开始距离
    /// </summary>
    public readonly float hitStopDistance;
    /// <summary>
    /// 子弹顿帧速度参数
    /// </summary>
    public readonly float hitStopSpeedParam;


    public const int __ID__ = -497711688;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "skillBulletNameID:" + skillBulletNameID + ","
        + "bulletID:" + bulletID + ","
        + "showTpye:" + showTpye + ","
        + "bulletStartPosID:" + bulletStartPosID + ","
        + "bulletEndPosID:" + bulletEndPosID + ","
        + "bulletStartPrefabID:" + bulletStartPrefabID + ","
        + "bulletEndPrefabID:" + bulletEndPrefabID + ","
        + "bulletEndTargetPosPrefabID:" + bulletEndTargetPosPrefabID + ","
        + "bulletStartSoundID:" + bulletStartSoundID + ","
        + "bulletHitSoundID:" + bulletHitSoundID + ","
        + "hitPrefabIDs:" + Luban.StringUtil.CollectionToString(hitPrefabIDs) + ","
        + "hitPosID:" + hitPosID + ","
        + "hitEffectID:" + hitEffectID + ","
        + "hitStopType:" + hitStopType + ","
        + "hitStopDuration:" + hitStopDuration + ","
        + "hitStopDistance:" + hitStopDistance + ","
        + "hitStopSpeedParam:" + hitStopSpeedParam + ","
        + "}";
    }
}
}

