
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class GameMember_aiType : Luban.BeanBase
{
    public GameMember_aiType(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        id = (int)_obj.GetValue("id");
        sClassName = (string)_obj.GetValue("sClassName");
        cClassName = (string)_obj.GetValue("cClassName");
    }

    public static GameMember_aiType DeserializeGameMember_aiType(JToken _buf)
    {
        return new GameMember_aiType(_buf);
    }

    /// <summary>
    /// 内容ID
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 服务器ai基类名称
    /// </summary>
    public readonly string sClassName;
    /// <summary>
    /// 客户端ai基类名称
    /// </summary>
    public readonly string cClassName;


    public const int __ID__ = -193558059;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "sClassName:" + sClassName + ","
        + "cClassName:" + cClassName + ","
        + "}";
    }
}
}

