
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class GameMember_monsterMount : Luban.BeanBase
{
    public GameMember_monsterMount(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        id = (int)_obj.GetValue("id");
        modelID = (int)_obj.GetValue("modelID");
        { var __json0 = _obj.GetValue("addSkills"); int _n0 = (__json0 as JArray).Count; addSkills = new int[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  addSkills[__index0++] = __v0; }   }
        shareHpPercent = (int)_obj.GetValue("shareHpPercent");
        mountScale = (float)_obj.GetValue("mountScale");
    }

    public static GameMember_monsterMount DeserializeGameMember_monsterMount(JToken _buf)
    {
        return new GameMember_monsterMount(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 坐骑模型ID
    /// </summary>
    public readonly int modelID;
    /// <summary>
    /// 技能数组
    /// </summary>
    public readonly int[] addSkills;
    /// <summary>
    /// 共享血量百分比
    /// </summary>
    public readonly int shareHpPercent;
    /// <summary>
    /// 模型大小
    /// </summary>
    public readonly float mountScale;


    public const int __ID__ = 323248242;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "modelID:" + modelID + ","
        + "addSkills:" + Luban.StringUtil.CollectionToString(addSkills) + ","
        + "shareHpPercent:" + shareHpPercent + ","
        + "mountScale:" + mountScale + ","
        + "}";
    }
}
}

