
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
public sealed partial class GameSkillProbability_probability : Luban.BeanBase
{
    public GameSkillProbability_probability(ByteBuf _buf) 
    {
        id = _buf.ReadString();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);values = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); values[__index0] = __e0;}}
    }

    public static GameSkillProbability_probability DeserializeGameSkillProbability_probability(ByteBuf _buf)
    {
        return new GameSkillProbability_probability(_buf);
    }

    /// <summary>
    /// 属性Key
    /// </summary>
    public readonly string id;
    /// <summary>
    /// 概率数组
    /// </summary>
    public readonly int[] values;
   
    public const int __ID__ = 1255132876;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "values:" + Luban.StringUtil.CollectionToString(values) + ","
        + "}";
    }
}

}

