
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class Guild_guilddairy : Luban.BeanBase
{
    public Guild_guilddairy(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        dairy_id = (int)_obj.GetValue("dairy_id");
        language = (string)_obj.GetValue("language");
    }

    public static Guild_guilddairy DeserializeGuild_guilddairy(JToken _buf)
    {
        return new Guild_guilddairy(_buf);
    }

    /// <summary>
    /// 日志类型id
    /// </summary>
    public readonly int dairy_id;
    /// <summary>
    /// 多语言id
    /// </summary>
    public readonly string language;


    public const int __ID__ = -807363924;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "dairy_id:" + dairy_id + ","
        + "language:" + language + ","
        + "}";
    }
}
}

