
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class GuildBOSS_rankRewards : Luban.BeanBase
{
    public GuildBOSS_rankRewards(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ID = (int)_obj.GetValue("ID");
        BossId = (int)_obj.GetValue("BossId");
        { var __json0 = _obj.GetValue("RankRange"); int _n0 = (__json0 as JArray).Count; RankRange = new int[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  RankRange[__index0++] = __v0; }   }
        { var __json0 = _obj.GetValue("Reward"); int _n0 = (__json0 as JArray).Count; Reward = new string[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  Reward[__index0++] = __v0; }   }
    }

    public static GuildBOSS_rankRewards DeserializeGuildBOSS_rankRewards(JToken _buf)
    {
        return new GuildBOSS_rankRewards(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// BossId
    /// </summary>
    public readonly int BossId;
    /// <summary>
    /// 排名范围
    /// </summary>
    public readonly int[] RankRange;
    /// <summary>
    /// 宝箱奖励奖励
    /// </summary>
    public readonly string[] Reward;


    public const int __ID__ = 365966681;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "BossId:" + BossId + ","
        + "RankRange:" + Luban.StringUtil.CollectionToString(RankRange) + ","
        + "Reward:" + Luban.StringUtil.CollectionToString(Reward) + ","
        + "}";
    }
}
}

