
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class Guild_guildSignIn : Luban.BeanBase
{
    public Guild_guildSignIn(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ID = (int)_obj.GetValue("ID");
        NeedItemId = (int)_obj.GetValue("NeedItemId");
        NeedItemCount = (int)_obj.GetValue("NeedItemCount");
        { var __json0 = _obj.GetValue("Reward"); int _n0 = (__json0 as JArray).Count; Reward = new string[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  Reward[__index0++] = __v0; }   }
        { var __json0 = _obj.GetValue("OtherReward"); int _n0 = (__json0 as JArray).Count; OtherReward = new string[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  OtherReward[__index0++] = __v0; }   }
    }

    public static Guild_guildSignIn DeserializeGuild_guildSignIn(JToken _buf)
    {
        return new Guild_guildSignIn(_buf);
    }

    /// <summary>
    /// 次数
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 消耗的道具ID<br/>0代表免费
    /// </summary>
    public readonly int NeedItemId;
    /// <summary>
    /// 消耗的道具数量
    /// </summary>
    public readonly int NeedItemCount;
    /// <summary>
    /// 奖励
    /// </summary>
    public readonly string[] Reward;
    /// <summary>
    /// 其他奖励<br/>客户端不需要展示（必须填道具，不需要就填道具+数量0）
    /// </summary>
    public readonly string[] OtherReward;


    public const int __ID__ = 262149929;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "NeedItemId:" + NeedItemId + ","
        + "NeedItemCount:" + NeedItemCount + ","
        + "Reward:" + Luban.StringUtil.CollectionToString(Reward) + ","
        + "OtherReward:" + Luban.StringUtil.CollectionToString(OtherReward) + ","
        + "}";
    }
}
}

