
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class GuildWar_GuildRankPre : Luban.BeanBase
{
    public GuildWar_GuildRankPre(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        id = (int)_obj.GetValue("id");
        { var __json0 = _obj.GetValue("guildNum"); int _n0 = (__json0 as JArray).Count; guildNum = new string[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  guildNum[__index0++] = __v0; }   }
        guildRank = (int)_obj.GetValue("guildRank");
    }

    public static GuildWar_GuildRankPre DeserializeGuildWar_GuildRankPre(JToken _buf)
    {
        return new GuildWar_GuildRankPre(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 本服公会战排名
    /// </summary>
    public readonly string[] guildNum;
    /// <summary>
    /// 公会定级段位
    /// </summary>
    public readonly int guildRank;


    public const int __ID__ = 294091118;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "guildNum:" + Luban.StringUtil.CollectionToString(guildNum) + ","
        + "guildRank:" + guildRank + ","
        + "}";
    }
}
}

