
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
public sealed partial class Guild_guildSignIn : Luban.BeanBase
{
    public Guild_guildSignIn(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        NeedItemId = _buf.ReadInt();
        NeedItemCount = _buf.ReadInt();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Reward = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); Reward[__index0] = __e0;}}
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);OtherReward = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); OtherReward[__index0] = __e0;}}
    }

    public static Guild_guildSignIn DeserializeGuild_guildSignIn(ByteBuf _buf)
    {
        return new Guild_guildSignIn(_buf);
    }

    /// <summary>
    /// 次数
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 消耗的道具ID<br/>0代表免费
    /// </summary>
    public readonly int NeedItemId;
    /// <summary>
    /// 消耗的道具数量
    /// </summary>
    public readonly int NeedItemCount;
    /// <summary>
    /// 奖励
    /// </summary>
    public readonly string[] Reward;
    /// <summary>
    /// 其他奖励<br/>客户端不需要展示（必须填道具，不需要就填道具+数量0）
    /// </summary>
    public readonly string[] OtherReward;
   
    public const int __ID__ = 262149929;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "NeedItemId:" + NeedItemId + ","
        + "NeedItemCount:" + NeedItemCount + ","
        + "Reward:" + Luban.StringUtil.CollectionToString(Reward) + ","
        + "OtherReward:" + Luban.StringUtil.CollectionToString(OtherReward) + ","
        + "}";
    }
}

}

