
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class Guild_guildGiftLevel : Luban.BeanBase
{
    public Guild_guildGiftLevel(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ID = (int)_obj.GetValue("ID");
        NeedExp = (int)_obj.GetValue("NeedExp");
        NeedKey = (int)_obj.GetValue("NeedKey");
        { var __json0 = _obj.GetValue("Reward"); int _n0 = (__json0 as JArray).Count; Reward = new string[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  Reward[__index0++] = __v0; }   }
    }

    public static Guild_guildGiftLevel DeserializeGuild_guildGiftLevel(JToken _buf)
    {
        return new Guild_guildGiftLevel(_buf);
    }

    /// <summary>
    /// 等级
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 升级所需经验
    /// </summary>
    public readonly int NeedExp;
    /// <summary>
    /// 大宝藏所需钥匙数
    /// </summary>
    public readonly int NeedKey;
    /// <summary>
    /// 大宝箱奖励
    /// </summary>
    public readonly string[] Reward;


    public const int __ID__ = 959498093;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "NeedExp:" + NeedExp + ","
        + "NeedKey:" + NeedKey + ","
        + "Reward:" + Luban.StringUtil.CollectionToString(Reward) + ","
        + "}";
    }
}
}

