
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
public sealed partial class Guild_guildLevel : Luban.BeanBase
{
    public Guild_guildLevel(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        Exp = _buf.ReadInt();
        MaxMemberCount = _buf.ReadInt();
        MaxContribute = _buf.ReadInt();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);MaxPositionCount = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); MaxPositionCount[__index0] = __e0;}}
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);ShopItemCount = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); ShopItemCount[__index0] = __e0;}}
        TaskCount = _buf.ReadInt();
        GuildBossOpen = _buf.ReadInt();
    }

    public static Guild_guildLevel DeserializeGuild_guildLevel(ByteBuf _buf)
    {
        return new Guild_guildLevel(_buf);
    }

    /// <summary>
    /// 等级
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 升到下一级需要的经验
    /// </summary>
    public readonly int Exp;
    /// <summary>
    /// 最大人数
    /// </summary>
    public readonly int MaxMemberCount;
    /// <summary>
    /// 公会每日最大捐献次数
    /// </summary>
    public readonly int MaxContribute;
    /// <summary>
    /// 职位最大人数<br/>副会长|管理者
    /// </summary>
    public readonly int[] MaxPositionCount;
    /// <summary>
    /// 商店出售货物数量<br/>每日|每周
    /// </summary>
    public readonly int[] ShopItemCount;
    /// <summary>
    /// 公会任务数量
    /// </summary>
    public readonly int TaskCount;
    /// <summary>
    /// 是否开启公会boss
    /// </summary>
    public readonly int GuildBossOpen;
   
    public const int __ID__ = -829397187;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Exp:" + Exp + ","
        + "MaxMemberCount:" + MaxMemberCount + ","
        + "MaxContribute:" + MaxContribute + ","
        + "MaxPositionCount:" + Luban.StringUtil.CollectionToString(MaxPositionCount) + ","
        + "ShopItemCount:" + Luban.StringUtil.CollectionToString(ShopItemCount) + ","
        + "TaskCount:" + TaskCount + ","
        + "GuildBossOpen:" + GuildBossOpen + ","
        + "}";
    }
}

}

