
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
public sealed partial class Guild_guildStyle : Luban.BeanBase
{
    public Guild_guildStyle(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        Style = _buf.ReadInt();
        AtlasID = _buf.ReadInt();
        Icon = _buf.ReadString();
    }

    public static Guild_guildStyle DeserializeGuild_guildStyle(ByteBuf _buf)
    {
        return new Guild_guildStyle(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// style类型：1,2<br/>1：背景<br/>2：Icon
    /// </summary>
    public readonly int Style;
    /// <summary>
    /// 图标
    /// </summary>
    public readonly int AtlasID;
    /// <summary>
    /// 图标
    /// </summary>
    public readonly string Icon;
   
    public const int __ID__ = -822482582;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Style:" + Style + ","
        + "AtlasID:" + AtlasID + ","
        + "Icon:" + Icon + ","
        + "}";
    }
}

}

