
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class IAP_ChapterPacks : Luban.BeanBase
{
    public IAP_ChapterPacks(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        id = (int)_obj.GetValue("id");
        chapterId = (int)_obj.GetValue("chapterId");
        orderId = (int)_obj.GetValue("orderId");
        { var __json0 = _obj.GetValue("products"); int _n0 = (__json0 as JArray).Count; products = new string[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  products[__index0++] = __v0; }   }
        nameId = (string)_obj.GetValue("nameId");
        descId = (string)_obj.GetValue("descId");
        descColor = (string)_obj.GetValue("descColor");
        originPriceColor = (string)_obj.GetValue("originPriceColor");
        bannerBgType = (int)_obj.GetValue("bannerBgType");
    }

    public static IAP_ChapterPacks DeserializeIAP_ChapterPacks(JToken _buf)
    {
        return new IAP_ChapterPacks(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 关卡Id
    /// </summary>
    public readonly int chapterId;
    /// <summary>
    /// 值越小优先级越高
    /// </summary>
    public readonly int orderId;
    /// <summary>
    /// 当即奖励<br/>itemid,count|itemid,count
    /// </summary>
    public readonly string[] products;
    /// <summary>
    /// 名称多语言
    /// </summary>
    public readonly string nameId;
    /// <summary>
    /// 描述多语言
    /// </summary>
    public readonly string descId;
    /// <summary>
    /// 描述文本颜色
    /// </summary>
    public readonly string descColor;
    /// <summary>
    /// 原件文本颜色
    /// </summary>
    public readonly string originPriceColor;
    /// <summary>
    /// 背景图
    /// </summary>
    public readonly int bannerBgType;


    public const int __ID__ = -513598476;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "chapterId:" + chapterId + ","
        + "orderId:" + orderId + ","
        + "products:" + Luban.StringUtil.CollectionToString(products) + ","
        + "nameId:" + nameId + ","
        + "descId:" + descId + ","
        + "descColor:" + descColor + ","
        + "originPriceColor:" + originPriceColor + ","
        + "bannerBgType:" + bannerBgType + ","
        + "}";
    }
}
}

