
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class IAP_LevelFundReward : Luban.BeanBase
{
    public IAP_LevelFundReward(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        id = (int)_obj.GetValue("id");
        groupId = (int)_obj.GetValue("groupId");
        param = (string)_obj.GetValue("param");
        { var __json0 = _obj.GetValue("freeReward"); int _n0 = (__json0 as JArray).Count; freeReward = new string[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  freeReward[__index0++] = __v0; }   }
        { var __json0 = _obj.GetValue("fundReward"); int _n0 = (__json0 as JArray).Count; fundReward = new string[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  fundReward[__index0++] = __v0; }   }
        prodReparationMail = (string)_obj.GetValue("prodReparationMail");
        testReparationMail = (string)_obj.GetValue("testReparationMail");
        { var __json0 = _obj.GetValue("reparationReward"); int _n0 = (__json0 as JArray).Count; reparationReward = new string[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  reparationReward[__index0++] = __v0; }   }
    }

    public static IAP_LevelFundReward DeserializeIAP_LevelFundReward(JToken _buf)
    {
        return new IAP_LevelFundReward(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 基金奖励组id
    /// </summary>
    public readonly int groupId;
    /// <summary>
    /// 解锁参数<br/>(天赋等级、<br/>塔LevelID）
    /// </summary>
    public readonly string param;
    /// <summary>
    /// 免费奖励
    /// </summary>
    public readonly string[] freeReward;
    /// <summary>
    /// 基金奖励
    /// </summary>
    public readonly string[] fundReward;
    /// <summary>
    /// 正式服补偿邮件
    /// </summary>
    public readonly string prodReparationMail;
    /// <summary>
    /// 测试服补偿邮件
    /// </summary>
    public readonly string testReparationMail;
    /// <summary>
    /// 补偿奖励
    /// </summary>
    public readonly string[] reparationReward;


    public const int __ID__ = 2050101457;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "groupId:" + groupId + ","
        + "param:" + param + ","
        + "freeReward:" + Luban.StringUtil.CollectionToString(freeReward) + ","
        + "fundReward:" + Luban.StringUtil.CollectionToString(fundReward) + ","
        + "prodReparationMail:" + prodReparationMail + ","
        + "testReparationMail:" + testReparationMail + ","
        + "reparationReward:" + Luban.StringUtil.CollectionToString(reparationReward) + ","
        + "}";
    }
}
}

