
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class ItemResources_itemget : Luban.BeanBase
{
    public ItemResources_itemget(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        id = (int)_obj.GetValue("id");
        { var __json0 = _obj.GetValue("itemGet"); int _n0 = (__json0 as JArray).Count; itemGet = new string[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  itemGet[__index0++] = __v0; }   }
    }

    public static ItemResources_itemget DeserializeItemResources_itemget(JToken _buf)
    {
        return new ItemResources_itemget(_buf);
    }

    /// <summary>
    /// 道具id
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 获取途径（itemresource）
    /// </summary>
    public readonly string[] itemGet;


    public const int __ID__ = -1898806186;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "itemGet:" + Luban.StringUtil.CollectionToString(itemGet) + ","
        + "}";
    }
}
}

