
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class LanguageCN_languagetable : Luban.BeanBase
{
    public LanguageCN_languagetable(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        id = (string)_obj.GetValue("id");
        chinesesimplified = (string)_obj.GetValue("chinesesimplified");
    }

    public static LanguageCN_languagetable DeserializeLanguageCN_languagetable(JToken _buf)
    {
        return new LanguageCN_languagetable(_buf);
    }

    /// <summary>
    /// 内容ID<br/>
    /// </summary>
    public readonly string id;
    /// <summary>
    /// 中国简化
    /// </summary>
    public readonly string chinesesimplified;


    public const int __ID__ = -1537193446;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "chinesesimplified:" + chinesesimplified + ","
        + "}";
    }
}
}

