
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
public sealed partial class LocalAds_LocalAdsCfg : Luban.BeanBase
{
    public LocalAds_LocalAdsCfg(ByteBuf _buf) 
    {
        id = _buf.ReadInt();
        platform = _buf.ReadInt();
        name = _buf.ReadString();
        imageName = _buf.ReadString();
        tomarket = _buf.ReadInt();
        jumpLink = _buf.ReadString();
    }

    public static LocalAds_LocalAdsCfg DeserializeLocalAds_LocalAdsCfg(ByteBuf _buf)
    {
        return new LocalAds_LocalAdsCfg(_buf);
    }

    /// <summary>
    /// 功能Id
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 渠道Id
    /// </summary>
    public readonly int platform;
    /// <summary>
    /// 功能名称
    /// </summary>
    public readonly string name;
    /// <summary>
    /// 图片名
    /// </summary>
    public readonly string imageName;
    /// <summary>
    /// 网页还是商店， 1是商店
    /// </summary>
    public readonly int tomarket;
    /// <summary>
    /// 跳转链接
    /// </summary>
    public readonly string jumpLink;
   
    public const int __ID__ = 1386660069;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "platform:" + platform + ","
        + "name:" + name + ","
        + "imageName:" + imageName + ","
        + "tomarket:" + tomarket + ","
        + "jumpLink:" + jumpLink + ","
        + "}";
    }
}

}

