
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class MainLevelReward_AFKreward : Luban.BeanBase
{
    public MainLevelReward_AFKreward(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ID = (int)_obj.GetValue("ID");
        RewardLevel = (int)_obj.GetValue("RewardLevel");
        RequiredLevel = (int)_obj.GetValue("RequiredLevel");
        HangGold = (int)_obj.GetValue("HangGold");
        HangDust = (int)_obj.GetValue("HangDust");
        HangHeroExp = (int)_obj.GetValue("HangHeroExp");
    }

    public static MainLevelReward_AFKreward DeserializeMainLevelReward_AFKreward(JToken _buf)
    {
        return new MainLevelReward_AFKreward(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 奖励等级
    /// </summary>
    public readonly int RewardLevel;
    /// <summary>
    /// 要求的关卡
    /// </summary>
    public readonly int RequiredLevel;
    /// <summary>
    /// 挂机金币奖励
    /// </summary>
    public readonly int HangGold;
    /// <summary>
    /// 挂机粉尘奖励
    /// </summary>
    public readonly int HangDust;
    /// <summary>
    /// 挂机英雄经验奖励
    /// </summary>
    public readonly int HangHeroExp;


    public const int __ID__ = -1587578448;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "RewardLevel:" + RewardLevel + ","
        + "RequiredLevel:" + RequiredLevel + ","
        + "HangGold:" + HangGold + ","
        + "HangDust:" + HangDust + ","
        + "HangHeroExp:" + HangHeroExp + ","
        + "}";
    }
}
}

