
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class Module_moduleInfo : Luban.BeanBase
{
    public Module_moduleInfo(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        id = (int)_obj.GetValue("id");
        nameId = (string)_obj.GetValue("nameId");
        infoId = (string)_obj.GetValue("infoId");
    }

    public static Module_moduleInfo DeserializeModule_moduleInfo(JToken _buf)
    {
        return new Module_moduleInfo(_buf);
    }

    /// <summary>
    /// 必须有的ID
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 模块名
    /// </summary>
    public readonly string nameId;
    /// <summary>
    /// 模块Tips说明
    /// </summary>
    public readonly string infoId;


    public const int __ID__ = 448945357;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "nameId:" + nameId + ","
        + "infoId:" + infoId + ","
        + "}";
    }
}
}

