
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class MonsterCfg_monsterCfg : Luban.BeanBase
{
    public MonsterCfg_monsterCfg(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        id = (int)_obj.GetValue("id");
        group = (int)_obj.GetValue("group");
        battleType = (int)_obj.GetValue("battleType");
        difficult = (int)_obj.GetValue("difficult");
        pos1 = (int)_obj.GetValue("pos1");
        { var __json0 = _obj.GetValue("pos1Mounts"); int _n0 = (__json0 as JArray).Count; pos1Mounts = new int[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  pos1Mounts[__index0++] = __v0; }   }
        pos2 = (int)_obj.GetValue("pos2");
        { var __json0 = _obj.GetValue("pos2Mounts"); int _n0 = (__json0 as JArray).Count; pos2Mounts = new int[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  pos2Mounts[__index0++] = __v0; }   }
        pos3 = (int)_obj.GetValue("pos3");
        { var __json0 = _obj.GetValue("pos3Mounts"); int _n0 = (__json0 as JArray).Count; pos3Mounts = new int[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  pos3Mounts[__index0++] = __v0; }   }
        pos4 = (int)_obj.GetValue("pos4");
        { var __json0 = _obj.GetValue("pos4Mounts"); int _n0 = (__json0 as JArray).Count; pos4Mounts = new int[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  pos4Mounts[__index0++] = __v0; }   }
        pos5 = (int)_obj.GetValue("pos5");
        { var __json0 = _obj.GetValue("pos5Mounts"); int _n0 = (__json0 as JArray).Count; pos5Mounts = new int[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  pos5Mounts[__index0++] = __v0; }   }
        pos6 = (int)_obj.GetValue("pos6");
        { var __json0 = _obj.GetValue("pos6Mounts"); int _n0 = (__json0 as JArray).Count; pos6Mounts = new int[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  pos6Mounts[__index0++] = __v0; }   }
        pos7 = (int)_obj.GetValue("pos7");
        { var __json0 = _obj.GetValue("pos7Mounts"); int _n0 = (__json0 as JArray).Count; pos7Mounts = new int[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  pos7Mounts[__index0++] = __v0; }   }
        pos8 = (int)_obj.GetValue("pos8");
        { var __json0 = _obj.GetValue("pos8Mounts"); int _n0 = (__json0 as JArray).Count; pos8Mounts = new int[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  pos8Mounts[__index0++] = __v0; }   }
        pos9 = (int)_obj.GetValue("pos9");
        { var __json0 = _obj.GetValue("pos9Mounts"); int _n0 = (__json0 as JArray).Count; pos9Mounts = new int[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  pos9Mounts[__index0++] = __v0; }   }
        pos10 = (int)_obj.GetValue("pos10");
        { var __json0 = _obj.GetValue("pos10Mounts"); int _n0 = (__json0 as JArray).Count; pos10Mounts = new int[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  pos10Mounts[__index0++] = __v0; }   }
        pos11 = (int)_obj.GetValue("pos11");
        { var __json0 = _obj.GetValue("pos11Mounts"); int _n0 = (__json0 as JArray).Count; pos11Mounts = new int[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  pos11Mounts[__index0++] = __v0; }   }
        pos12 = (int)_obj.GetValue("pos12");
        { var __json0 = _obj.GetValue("pos12Mounts"); int _n0 = (__json0 as JArray).Count; pos12Mounts = new int[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  pos12Mounts[__index0++] = __v0; }   }
        pos13 = (int)_obj.GetValue("pos13");
        { var __json0 = _obj.GetValue("pos13Mounts"); int _n0 = (__json0 as JArray).Count; pos13Mounts = new int[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  pos13Mounts[__index0++] = __v0; }   }
        pos14 = (int)_obj.GetValue("pos14");
        { var __json0 = _obj.GetValue("pos14Mounts"); int _n0 = (__json0 as JArray).Count; pos14Mounts = new int[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  pos14Mounts[__index0++] = __v0; }   }
        pos15 = (int)_obj.GetValue("pos15");
        { var __json0 = _obj.GetValue("pos15Mounts"); int _n0 = (__json0 as JArray).Count; pos15Mounts = new int[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  pos15Mounts[__index0++] = __v0; }   }
        enterBattleMode = (int)_obj.GetValue("enterBattleMode");
        ride = (int)_obj.GetValue("ride");
        isDropBox = (int)_obj.GetValue("isDropBox");
        baseSpeed = (int)_obj.GetValue("baseSpeed");
        mythicProgress = (int)_obj.GetValue("mythicProgress");
    }

    public static MonsterCfg_monsterCfg DeserializeMonsterCfg_monsterCfg(JToken _buf)
    {
        return new MonsterCfg_monsterCfg(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 对阵组
    /// </summary>
    public readonly int group;
    /// <summary>
    /// 战斗类型
    /// </summary>
    public readonly int battleType;
    /// <summary>
    /// 难度
    /// </summary>
    public readonly int difficult;
    /// <summary>
    /// 位置1
    /// </summary>
    public readonly int pos1;
    /// <summary>
    /// 坐骑位置1<br/>读取GameMember_monsterMount表
    /// </summary>
    public readonly int[] pos1Mounts;
    /// <summary>
    /// 位置2
    /// </summary>
    public readonly int pos2;
    /// <summary>
    /// 坐骑位置2<br/>读取GameMember_monsterMount表
    /// </summary>
    public readonly int[] pos2Mounts;
    /// <summary>
    /// 位置3
    /// </summary>
    public readonly int pos3;
    /// <summary>
    /// 坐骑位置3<br/>读取GameMember_monsterMount表
    /// </summary>
    public readonly int[] pos3Mounts;
    /// <summary>
    /// 位置4
    /// </summary>
    public readonly int pos4;
    /// <summary>
    /// 坐骑位置4<br/>读取GameMember_monsterMount表
    /// </summary>
    public readonly int[] pos4Mounts;
    /// <summary>
    /// 位置5
    /// </summary>
    public readonly int pos5;
    /// <summary>
    /// 坐骑位置5<br/>读取GameMember_monsterMount表
    /// </summary>
    public readonly int[] pos5Mounts;
    /// <summary>
    /// 位置6
    /// </summary>
    public readonly int pos6;
    /// <summary>
    /// 坐骑位置6<br/>读取GameMember_monsterMount表
    /// </summary>
    public readonly int[] pos6Mounts;
    /// <summary>
    /// 位置7
    /// </summary>
    public readonly int pos7;
    /// <summary>
    /// 坐骑位置7<br/>读取GameMember_monsterMount表
    /// </summary>
    public readonly int[] pos7Mounts;
    /// <summary>
    /// 位置8
    /// </summary>
    public readonly int pos8;
    /// <summary>
    /// 坐骑位置8<br/>读取GameMember_monsterMount表
    /// </summary>
    public readonly int[] pos8Mounts;
    /// <summary>
    /// 位置9
    /// </summary>
    public readonly int pos9;
    /// <summary>
    /// 坐骑位置9<br/>读取GameMember_monsterMount表
    /// </summary>
    public readonly int[] pos9Mounts;
    /// <summary>
    /// 位置10
    /// </summary>
    public readonly int pos10;
    /// <summary>
    /// 坐骑位置10<br/>读取GameMember_monsterMount表
    /// </summary>
    public readonly int[] pos10Mounts;
    /// <summary>
    /// 位置11
    /// </summary>
    public readonly int pos11;
    /// <summary>
    /// 坐骑位置11<br/>读取GameMember_monsterMount表
    /// </summary>
    public readonly int[] pos11Mounts;
    /// <summary>
    /// 位置12
    /// </summary>
    public readonly int pos12;
    /// <summary>
    /// 坐骑位置12<br/>读取GameMember_monsterMount表
    /// </summary>
    public readonly int[] pos12Mounts;
    /// <summary>
    /// 位置13
    /// </summary>
    public readonly int pos13;
    /// <summary>
    /// 坐骑位置13<br/>读取GameMember_monsterMount表
    /// </summary>
    public readonly int[] pos13Mounts;
    /// <summary>
    /// 位置14
    /// </summary>
    public readonly int pos14;
    /// <summary>
    /// 坐骑位置14<br/>读取GameMember_monsterMount表
    /// </summary>
    public readonly int[] pos14Mounts;
    /// <summary>
    /// 位置15
    /// </summary>
    public readonly int pos15;
    /// <summary>
    /// 坐骑位置15<br/>读取GameMember_monsterMount表
    /// </summary>
    public readonly int[] pos15Mounts;
    /// <summary>
    /// 战斗入场方式
    /// </summary>
    public readonly int enterBattleMode;
    /// <summary>
    /// 载具
    /// </summary>
    public readonly int ride;
    /// <summary>
    /// 是否掉落宝箱
    /// </summary>
    public readonly int isDropBox;
    /// <summary>
    /// 基础速度
    /// </summary>
    public readonly int baseSpeed;
    /// <summary>
    /// 进度值
    /// </summary>
    public readonly int mythicProgress;


    public const int __ID__ = 1922336575;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "group:" + group + ","
        + "battleType:" + battleType + ","
        + "difficult:" + difficult + ","
        + "pos1:" + pos1 + ","
        + "pos1Mounts:" + Luban.StringUtil.CollectionToString(pos1Mounts) + ","
        + "pos2:" + pos2 + ","
        + "pos2Mounts:" + Luban.StringUtil.CollectionToString(pos2Mounts) + ","
        + "pos3:" + pos3 + ","
        + "pos3Mounts:" + Luban.StringUtil.CollectionToString(pos3Mounts) + ","
        + "pos4:" + pos4 + ","
        + "pos4Mounts:" + Luban.StringUtil.CollectionToString(pos4Mounts) + ","
        + "pos5:" + pos5 + ","
        + "pos5Mounts:" + Luban.StringUtil.CollectionToString(pos5Mounts) + ","
        + "pos6:" + pos6 + ","
        + "pos6Mounts:" + Luban.StringUtil.CollectionToString(pos6Mounts) + ","
        + "pos7:" + pos7 + ","
        + "pos7Mounts:" + Luban.StringUtil.CollectionToString(pos7Mounts) + ","
        + "pos8:" + pos8 + ","
        + "pos8Mounts:" + Luban.StringUtil.CollectionToString(pos8Mounts) + ","
        + "pos9:" + pos9 + ","
        + "pos9Mounts:" + Luban.StringUtil.CollectionToString(pos9Mounts) + ","
        + "pos10:" + pos10 + ","
        + "pos10Mounts:" + Luban.StringUtil.CollectionToString(pos10Mounts) + ","
        + "pos11:" + pos11 + ","
        + "pos11Mounts:" + Luban.StringUtil.CollectionToString(pos11Mounts) + ","
        + "pos12:" + pos12 + ","
        + "pos12Mounts:" + Luban.StringUtil.CollectionToString(pos12Mounts) + ","
        + "pos13:" + pos13 + ","
        + "pos13Mounts:" + Luban.StringUtil.CollectionToString(pos13Mounts) + ","
        + "pos14:" + pos14 + ","
        + "pos14Mounts:" + Luban.StringUtil.CollectionToString(pos14Mounts) + ","
        + "pos15:" + pos15 + ","
        + "pos15Mounts:" + Luban.StringUtil.CollectionToString(pos15Mounts) + ","
        + "enterBattleMode:" + enterBattleMode + ","
        + "ride:" + ride + ","
        + "isDropBox:" + isDropBox + ","
        + "baseSpeed:" + baseSpeed + ","
        + "mythicProgress:" + mythicProgress + ","
        + "}";
    }
}
}

