
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class Pet_petLevelEffect : Luban.BeanBase
{
    public Pet_petLevelEffect(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        id = (int)_obj.GetValue("id");
        type = (int)_obj.GetValue("type");
        level = (int)_obj.GetValue("level");
        levelupDesc = (string)_obj.GetValue("levelupDesc");
        { var __json0 = _obj.GetValue("playerAttr"); int _n0 = (__json0 as JArray).Count; playerAttr = new string[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  playerAttr[__index0++] = __v0; }   }
        { var __json0 = _obj.GetValue("petAttr"); int _n0 = (__json0 as JArray).Count; petAttr = new string[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  petAttr[__index0++] = __v0; }   }
        petSkillLevel = (int)_obj.GetValue("petSkillLevel");
    }

    public static Pet_petLevelEffect DeserializePet_petLevelEffect(JToken _buf)
    {
        return new Pet_petLevelEffect(_buf);
    }

    /// <summary>
    /// 内容ID
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 宠物品质<br/>获得ID时可以通过宠物品质*1000+等级
    /// </summary>
    public readonly int type;
    /// <summary>
    /// 等级
    /// </summary>
    public readonly int level;
    /// <summary>
    /// 升级效果描述
    /// </summary>
    public readonly string levelupDesc;
    /// <summary>
    /// 主角属性增加（最终值）
    /// </summary>
    public readonly string[] playerAttr;
    /// <summary>
    /// 宠物属性增加（最终值）
    /// </summary>
    public readonly string[] petAttr;
    /// <summary>
    /// 宠物技能等级（最终值）
    /// </summary>
    public readonly int petSkillLevel;


    public const int __ID__ = -347725098;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "type:" + type + ","
        + "level:" + level + ","
        + "levelupDesc:" + levelupDesc + ","
        + "playerAttr:" + Luban.StringUtil.CollectionToString(playerAttr) + ","
        + "petAttr:" + Luban.StringUtil.CollectionToString(petAttr) + ","
        + "petSkillLevel:" + petSkillLevel + ","
        + "}";
    }
}
}

