
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class Pet_PetEntry : Luban.BeanBase
{
    public Pet_PetEntry(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        id = (int)_obj.GetValue("id");
        languageName = (string)_obj.GetValue("languageName");
        languageID = (string)_obj.GetValue("languageID");
        quality = (int)_obj.GetValue("quality");
        entryType = (int)_obj.GetValue("entryType");
        actionType = (int)_obj.GetValue("actionType");
        action = (string)_obj.GetValue("action");
        { var __json0 = _obj.GetValue("actionSpecial"); int _n0 = (__json0 as JArray).Count; actionSpecial = new string[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  actionSpecial[__index0++] = __v0; }   }
        { var __json0 = _obj.GetValue("attrRange"); int _n0 = (__json0 as JArray).Count; attrRange = new int[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  attrRange[__index0++] = __v0; }   }
        weight = (int)_obj.GetValue("weight");
        packVersion = (string)_obj.GetValue("packVersion");
        { var __json0 = _obj.GetValue("activePower"); int _n0 = (__json0 as JArray).Count; activePower = new int[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  activePower[__index0++] = __v0; }   }
    }

    public static Pet_PetEntry DeserializePet_PetEntry(JToken _buf)
    {
        return new Pet_PetEntry(_buf);
    }

    /// <summary>
    /// 内容ID
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 标题
    /// </summary>
    public readonly string languageName;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string languageID;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly int quality;
    /// <summary>
    /// 类型<br/>1、普通词条<br/>2、特殊词条
    /// </summary>
    public readonly int entryType;
    /// <summary>
    /// 作用效果类型<br/>1、属性<br/>2、技能<br/>3、本体属性
    /// </summary>
    public readonly int actionType;
    /// <summary>
    /// 作用效果
    /// </summary>
    public readonly string action;
    /// <summary>
    /// 特殊效果<br/>1变头像框
    /// </summary>
    public readonly string[] actionSpecial;
    /// <summary>
    /// 属性百分比区间
    /// </summary>
    public readonly int[] attrRange;
    /// <summary>
    /// 权重
    /// </summary>
    public readonly int weight;
    /// <summary>
    /// 此版本后才能刷出<br/>不配无限制
    /// </summary>
    public readonly string packVersion;
    /// <summary>
    /// 层数2万分比战力<br/>层数3万分比战力<br/>（上阵增加战力）
    /// </summary>
    public readonly int[] activePower;


    public const int __ID__ = -74428941;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "languageName:" + languageName + ","
        + "languageID:" + languageID + ","
        + "quality:" + quality + ","
        + "entryType:" + entryType + ","
        + "actionType:" + actionType + ","
        + "action:" + action + ","
        + "actionSpecial:" + Luban.StringUtil.CollectionToString(actionSpecial) + ","
        + "attrRange:" + Luban.StringUtil.CollectionToString(attrRange) + ","
        + "weight:" + weight + ","
        + "packVersion:" + packVersion + ","
        + "activePower:" + Luban.StringUtil.CollectionToString(activePower) + ","
        + "}";
    }
}
}

