
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class Pet_PetTraining : Luban.BeanBase
{
    public Pet_PetTraining(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        id = (int)_obj.GetValue("id");
        level = (int)_obj.GetValue("level");
        isSpecial = (int)_obj.GetValue("isSpecial");
    }

    public static Pet_PetTraining DeserializePet_PetTraining(JToken _buf)
    {
        return new Pet_PetTraining(_buf);
    }

    /// <summary>
    /// 培育槽位
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 所需培育等级
    /// </summary>
    public readonly int level;
    /// <summary>
    /// 是否包含特殊词条
    /// </summary>
    public readonly int isSpecial;


    public const int __ID__ = -2034546759;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "level:" + level + ","
        + "isSpecial:" + isSpecial + ","
        + "}";
    }
}
}

