
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class Plinko_PlinkoSpecialRewards : Luban.BeanBase
{
    public Plinko_PlinkoSpecialRewards(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ID = (int)_obj.GetValue("ID");
        { var __json0 = _obj.GetValue("Rewards"); int _n0 = (__json0 as JArray).Count; Rewards = new string[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  Rewards[__index0++] = __v0; }   }
    }

    public static Plinko_PlinkoSpecialRewards DeserializePlinko_PlinkoSpecialRewards(JToken _buf)
    {
        return new Plinko_PlinkoSpecialRewards(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 道具ID，道具数量，该组内有多少个该道具，该道具奖励的价值<br/>用完后重置个数
    /// </summary>
    public readonly string[] Rewards;


    public const int __ID__ = -335695990;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Rewards:" + Luban.StringUtil.CollectionToString(Rewards) + ","
        + "}";
    }
}
}

