
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
public sealed partial class Plinko_PlinkoSpecialRewardNum : Luban.BeanBase
{
    public Plinko_PlinkoSpecialRewardNum(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);BallNum = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); BallNum[__index0] = __e0;}}
    }

    public static Plinko_PlinkoSpecialRewardNum DeserializePlinko_PlinkoSpecialRewardNum(ByteBuf _buf)
    {
        return new Plinko_PlinkoSpecialRewardNum(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 中奖个数，该组内该中奖个数包含多少个
    /// </summary>
    public readonly string[] BallNum;
   
    public const int __ID__ = -481331011;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "BallNum:" + Luban.StringUtil.CollectionToString(BallNum) + ","
        + "}";
    }
}

}

