
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
public sealed partial class Plinko_PlinkoSpecialRewards : Luban.BeanBase
{
    public Plinko_PlinkoSpecialRewards(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Rewards = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); Rewards[__index0] = __e0;}}
    }

    public static Plinko_PlinkoSpecialRewards DeserializePlinko_PlinkoSpecialRewards(ByteBuf _buf)
    {
        return new Plinko_PlinkoSpecialRewards(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 道具ID，道具数量，该组内有多少个该道具，该道具奖励的价值<br/>用完后重置个数
    /// </summary>
    public readonly string[] Rewards;
   
    public const int __ID__ = -335695990;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Rewards:" + Luban.StringUtil.CollectionToString(Rewards) + ","
        + "}";
    }
}

}

