
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class Plinko_PlinkoGuildReward : Luban.BeanBase
{
    public Plinko_PlinkoGuildReward(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ID = (int)_obj.GetValue("ID");
        ConnectActivityId = (int)_obj.GetValue("ConnectActivityId");
        PlinkoCostItemNeed = (int)_obj.GetValue("PlinkoCostItemNeed");
        { var __json0 = _obj.GetValue("Rewards"); int _n0 = (__json0 as JArray).Count; Rewards = new string[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  Rewards[__index0++] = __v0; }   }
        LanguageID = (int)_obj.GetValue("LanguageID");
    }

    public static Plinko_PlinkoGuildReward DeserializePlinko_PlinkoGuildReward(JToken _buf)
    {
        return new Plinko_PlinkoGuildReward(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 关联的活动ID<br/>EventOpenTime表ID
    /// </summary>
    public readonly int ConnectActivityId;
    /// <summary>
    /// 公会数量要求
    /// </summary>
    public readonly int PlinkoCostItemNeed;
    /// <summary>
    /// 奖励
    /// </summary>
    public readonly string[] Rewards;
    /// <summary>
    /// 多语言
    /// </summary>
    public readonly int LanguageID;


    public const int __ID__ = -1324681725;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "ConnectActivityId:" + ConnectActivityId + ","
        + "PlinkoCostItemNeed:" + PlinkoCostItemNeed + ","
        + "Rewards:" + Luban.StringUtil.CollectionToString(Rewards) + ","
        + "LanguageID:" + LanguageID + ","
        + "}";
    }
}
}

