
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class Quality_HeroQuality : Luban.BeanBase
{
    public Quality_HeroQuality(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        id = (int)_obj.GetValue("id");
        nameID = (string)_obj.GetValue("nameID");
        uiHeroBg = (string)_obj.GetValue("uiHeroBg");
        uiUnActiveBg = (string)_obj.GetValue("uiUnActiveBg");
        heroAtlasId = (int)_obj.GetValue("heroAtlasId");
        uiAttrBg = (string)_obj.GetValue("uiAttrBg");
        uiAttrBgTab = (string)_obj.GetValue("uiAttrBgTab");
        atlasId = (int)_obj.GetValue("atlasId");
        bgSpriteName = (string)_obj.GetValue("bgSpriteName");
        typeTxtBg = (string)_obj.GetValue("typeTxtBg");
        cardAtlasId = (int)_obj.GetValue("cardAtlasId");
        cardIcon = (string)_obj.GetValue("cardIcon");
        colorNum = (string)_obj.GetValue("colorNum");
        uiAttrTitleColor = (string)_obj.GetValue("uiAttrTitleColor");
        uiAttrItemBg = (string)_obj.GetValue("uiAttrItemBg");
        uiAttrBgTitleTabColor = (string)_obj.GetValue("uiAttrBgTitleTabColor");
        uiAttrFontColor = (string)_obj.GetValue("uiAttrFontColor");
        uiHeroSelectBgColor = (string)_obj.GetValue("uiHeroSelectBgColor");
        uiHeroBgLightColor = (string)_obj.GetValue("uiHeroBgLightColor");
        uiHeroBgIcon = (string)_obj.GetValue("uiHeroBgIcon");
    }

    public static Quality_HeroQuality DeserializeQuality_HeroQuality(JToken _buf)
    {
        return new Quality_HeroQuality(_buf);
    }

    /// <summary>
    /// qualityId
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 名称多语言<br/>（用于道具时）
    /// </summary>
    public readonly string nameID;
    /// <summary>
    /// 英雄界面背景
    /// </summary>
    public readonly string uiHeroBg;
    /// <summary>
    /// 连携技能未激活的背景
    /// </summary>
    public readonly string uiUnActiveBg;
    /// <summary>
    /// 英雄图集id
    /// </summary>
    public readonly int heroAtlasId;
    /// <summary>
    /// 属性背景
    /// </summary>
    public readonly string uiAttrBg;
    /// <summary>
    /// 属性背景页签
    /// </summary>
    public readonly string uiAttrBgTab;
    /// <summary>
    /// 背景图图集id
    /// </summary>
    public readonly int atlasId;
    /// <summary>
    /// 背景图切片名称
    /// </summary>
    public readonly string bgSpriteName;
    /// <summary>
    /// 装备类型文字底框
    /// </summary>
    public readonly string typeTxtBg;
    /// <summary>
    /// 卡片品质图集id
    /// </summary>
    public readonly int cardAtlasId;
    /// <summary>
    /// 卡片品质icon
    /// </summary>
    public readonly string cardIcon;
    /// <summary>
    /// 统一品质颜色
    /// </summary>
    public readonly string colorNum;
    /// <summary>
    /// 属性标题颜色
    /// </summary>
    public readonly string uiAttrTitleColor;
    /// <summary>
    /// 属性词条背景
    /// </summary>
    public readonly string uiAttrItemBg;
    /// <summary>
    /// 属性标题颜色
    /// </summary>
    public readonly string uiAttrBgTitleTabColor;
    /// <summary>
    /// 属性字的颜色
    /// </summary>
    public readonly string uiAttrFontColor;
    /// <summary>
    /// 选中英雄的背景颜色
    /// </summary>
    public readonly string uiHeroSelectBgColor;
    /// <summary>
    /// 英雄背景光的颜色
    /// </summary>
    public readonly string uiHeroBgLightColor;
    /// <summary>
    /// 英雄背景图案颜色
    /// </summary>
    public readonly string uiHeroBgIcon;


    public const int __ID__ = 1246069797;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "nameID:" + nameID + ","
        + "uiHeroBg:" + uiHeroBg + ","
        + "uiUnActiveBg:" + uiUnActiveBg + ","
        + "heroAtlasId:" + heroAtlasId + ","
        + "uiAttrBg:" + uiAttrBg + ","
        + "uiAttrBgTab:" + uiAttrBgTab + ","
        + "atlasId:" + atlasId + ","
        + "bgSpriteName:" + bgSpriteName + ","
        + "typeTxtBg:" + typeTxtBg + ","
        + "cardAtlasId:" + cardAtlasId + ","
        + "cardIcon:" + cardIcon + ","
        + "colorNum:" + colorNum + ","
        + "uiAttrTitleColor:" + uiAttrTitleColor + ","
        + "uiAttrItemBg:" + uiAttrItemBg + ","
        + "uiAttrBgTitleTabColor:" + uiAttrBgTitleTabColor + ","
        + "uiAttrFontColor:" + uiAttrFontColor + ","
        + "uiHeroSelectBgColor:" + uiHeroSelectBgColor + ","
        + "uiHeroBgLightColor:" + uiHeroBgLightColor + ","
        + "uiHeroBgIcon:" + uiHeroBgIcon + ","
        + "}";
    }
}
}

