
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
public sealed partial class Quality_LegacySkillQuality : Luban.BeanBase
{
    public Quality_LegacySkillQuality(ByteBuf _buf) 
    {
        id = _buf.ReadInt();
        nameID = _buf.ReadString();
        itemSixBgAtlasId = _buf.ReadInt();
        itemSixBgSpriteName = _buf.ReadString();
        equipAniBackName = _buf.ReadString();
        equipAniFrontName = _buf.ReadString();
        passiveAtlasId = _buf.ReadInt();
        passiveItemBg = _buf.ReadString();
        atlasId = _buf.ReadInt();
        cardBg = _buf.ReadString();
        typeAtlasId = _buf.ReadInt();
        typeTxtBg = _buf.ReadString();
        colorNum = _buf.ReadString();
        effectItemColor = _buf.ReadString();
    }

    public static Quality_LegacySkillQuality DeserializeQuality_LegacySkillQuality(ByteBuf _buf)
    {
        return new Quality_LegacySkillQuality(_buf);
    }

    /// <summary>
    /// qualityId
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 名称多语言<br/>（用于道具时）
    /// </summary>
    public readonly string nameID;
    /// <summary>
    /// 道具六边形背景图集Id
    /// </summary>
    public readonly int itemSixBgAtlasId;
    /// <summary>
    /// 道具六边形背景图图片名
    /// </summary>
    public readonly string itemSixBgSpriteName;
    /// <summary>
    /// 上阵动画后面特效名字
    /// </summary>
    public readonly string equipAniBackName;
    /// <summary>
    /// 上阵动画前面特效名字
    /// </summary>
    public readonly string equipAniFrontName;
    /// <summary>
    /// 被动技能背景框图集id
    /// </summary>
    public readonly int passiveAtlasId;
    /// <summary>
    /// 被动技能物品框
    /// </summary>
    public readonly string passiveItemBg;
    /// <summary>
    /// 背景图图集id
    /// </summary>
    public readonly int atlasId;
    /// <summary>
    /// 技能卡底框
    /// </summary>
    public readonly string cardBg;
    /// <summary>
    /// 类型文字底框
    /// </summary>
    public readonly int typeAtlasId;
    /// <summary>
    /// 类型文字底框
    /// </summary>
    public readonly string typeTxtBg;
    /// <summary>
    /// 统一品质颜色
    /// </summary>
    public readonly string colorNum;
    /// <summary>
    /// 技能词条颜色
    /// </summary>
    public readonly string effectItemColor;
   
    public const int __ID__ = 1615579991;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "nameID:" + nameID + ","
        + "itemSixBgAtlasId:" + itemSixBgAtlasId + ","
        + "itemSixBgSpriteName:" + itemSixBgSpriteName + ","
        + "equipAniBackName:" + equipAniBackName + ","
        + "equipAniFrontName:" + equipAniFrontName + ","
        + "passiveAtlasId:" + passiveAtlasId + ","
        + "passiveItemBg:" + passiveItemBg + ","
        + "atlasId:" + atlasId + ","
        + "cardBg:" + cardBg + ","
        + "typeAtlasId:" + typeAtlasId + ","
        + "typeTxtBg:" + typeTxtBg + ","
        + "colorNum:" + colorNum + ","
        + "effectItemColor:" + effectItemColor + ","
        + "}";
    }
}

}

