
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
public sealed partial class Relic_updateLevel : Luban.BeanBase
{
    public Relic_updateLevel(ByteBuf _buf) 
    {
        id = _buf.ReadInt();
        TypeId = _buf.ReadInt();
        level = _buf.ReadInt();
        nextID = _buf.ReadInt();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);levelupCost = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); levelupCost[__index0] = __e0;}}
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Attributes = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); Attributes[__index0] = __e0;}}
    }

    public static Relic_updateLevel DeserializeRelic_updateLevel(ByteBuf _buf)
    {
        return new Relic_updateLevel(_buf);
    }

    /// <summary>
    /// 内容ID
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 强化类型ID
    /// </summary>
    public readonly int TypeId;
    /// <summary>
    /// 等级
    /// </summary>
    public readonly int level;
    /// <summary>
    /// 下一等级ID 满级为0
    /// </summary>
    public readonly int nextID;
    /// <summary>
    /// 升至下一级的消耗
    /// </summary>
    public readonly string[] levelupCost;
    /// <summary>
    /// 当前等级的属性
    /// </summary>
    public readonly string[] Attributes;
   
    public const int __ID__ = 1440060751;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "TypeId:" + TypeId + ","
        + "level:" + level + ","
        + "nextID:" + nextID + ","
        + "levelupCost:" + Luban.StringUtil.CollectionToString(levelupCost) + ","
        + "Attributes:" + Luban.StringUtil.CollectionToString(Attributes) + ","
        + "}";
    }
}

}

