
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
public sealed partial class SevenDay_SevenDayPay : Luban.BeanBase
{
    public SevenDay_SevenDayPay(ByteBuf _buf) 
    {
        id = _buf.ReadInt();
        groupId = _buf.ReadInt();
        PurchaseId = _buf.ReadInt();
        Day = _buf.ReadInt();
        ObjName = _buf.ReadString();
        objToplimit = _buf.ReadInt();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);ObjGoods = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); ObjGoods[__index0] = __e0;}}
    }

    public static SevenDay_SevenDayPay DeserializeSevenDay_SevenDayPay(ByteBuf _buf)
    {
        return new SevenDay_SevenDayPay(_buf);
    }

    /// <summary>
    /// 编号
    /// </summary>
    public readonly int id;
    /// <summary>
    /// groupId
    /// </summary>
    public readonly int groupId;
    /// <summary>
    /// 支付ID<br/>不配则直接领取
    /// </summary>
    public readonly int PurchaseId;
    /// <summary>
    /// 第几天
    /// </summary>
    public readonly int Day;
    /// <summary>
    /// 目标名称（多语言）
    /// </summary>
    public readonly string ObjName;
    /// <summary>
    /// 限购数量
    /// </summary>
    public readonly int objToplimit;
    /// <summary>
    /// 出售道具
    /// </summary>
    public readonly string[] ObjGoods;
   
    public const int __ID__ = -774578711;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "groupId:" + groupId + ","
        + "PurchaseId:" + PurchaseId + ","
        + "Day:" + Day + ","
        + "ObjName:" + ObjName + ","
        + "objToplimit:" + objToplimit + ","
        + "ObjGoods:" + Luban.StringUtil.CollectionToString(ObjGoods) + ","
        + "}";
    }
}

}

