
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class SevenDay_SevenDayPay : Luban.BeanBase
{
    public SevenDay_SevenDayPay(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        id = (int)_obj.GetValue("id");
        groupId = (int)_obj.GetValue("groupId");
        PurchaseId = (int)_obj.GetValue("PurchaseId");
        Day = (int)_obj.GetValue("Day");
        ObjName = (string)_obj.GetValue("ObjName");
        objToplimit = (int)_obj.GetValue("objToplimit");
        { var __json0 = _obj.GetValue("ObjGoods"); int _n0 = (__json0 as JArray).Count; ObjGoods = new string[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  ObjGoods[__index0++] = __v0; }   }
    }

    public static SevenDay_SevenDayPay DeserializeSevenDay_SevenDayPay(JToken _buf)
    {
        return new SevenDay_SevenDayPay(_buf);
    }

    /// <summary>
    /// 编号
    /// </summary>
    public readonly int id;
    /// <summary>
    /// groupId
    /// </summary>
    public readonly int groupId;
    /// <summary>
    /// 支付ID<br/>不配则直接领取
    /// </summary>
    public readonly int PurchaseId;
    /// <summary>
    /// 第几天
    /// </summary>
    public readonly int Day;
    /// <summary>
    /// 目标名称（多语言）
    /// </summary>
    public readonly string ObjName;
    /// <summary>
    /// 限购数量
    /// </summary>
    public readonly int objToplimit;
    /// <summary>
    /// 出售道具
    /// </summary>
    public readonly string[] ObjGoods;


    public const int __ID__ = -774578711;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "groupId:" + groupId + ","
        + "PurchaseId:" + PurchaseId + ","
        + "Day:" + Day + ","
        + "ObjName:" + ObjName + ","
        + "objToplimit:" + objToplimit + ","
        + "ObjGoods:" + Luban.StringUtil.CollectionToString(ObjGoods) + ","
        + "}";
    }
}
}

