
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class Shop_PigBank : Luban.BeanBase
{
    public Shop_PigBank(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ID = (int)_obj.GetValue("ID");
        ActivityId = (int)_obj.GetValue("ActivityId");
        Type = (int)_obj.GetValue("Type");
        ShopId = (int)_obj.GetValue("ShopId");
        BaseValue = (int)_obj.GetValue("BaseValue");
        InitValue = (int)_obj.GetValue("InitValue");
        MaxValue = (int)_obj.GetValue("MaxValue");
        LayerAdd = (int)_obj.GetValue("LayerAdd");
        TimeLimit = (int)_obj.GetValue("TimeLimit");
        TitleId = (string)_obj.GetValue("TitleId");
        { var __json0 = _obj.GetValue("DescId"); int _n0 = (__json0 as JArray).Count; DescId = new string[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  DescId[__index0++] = __v0; }   }
        { var __json0 = _obj.GetValue("ResId"); int _n0 = (__json0 as JArray).Count; ResId = new string[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  ResId[__index0++] = __v0; }   }
    }

    public static Shop_PigBank DeserializeShop_PigBank(JToken _buf)
    {
        return new Shop_PigBank(_buf);
    }

    /// <summary>
    /// 档位ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 活动表ActivityDan-&gt;ID<br/>(0:新号初始活动)
    /// </summary>
    public readonly int ActivityId;
    /// <summary>
    /// 储钱罐类型<br/>1.单次出现<br/>2.重复出现（活动期间）
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// IAP的purchase的ID
    /// </summary>
    public readonly int ShopId;
    /// <summary>
    /// 价值倍率展示
    /// </summary>
    public readonly int BaseValue;
    /// <summary>
    /// 初始奖励
    /// </summary>
    public readonly int InitValue;
    /// <summary>
    /// 最高奖励
    /// </summary>
    public readonly int MaxValue;
    /// <summary>
    /// 每消耗1点体力增长多少钻石额度
    /// </summary>
    public readonly int LayerAdd;
    /// <summary>
    /// 限时(小时)
    /// </summary>
    public readonly int TimeLimit;
    /// <summary>
    /// 标题多语言ID
    /// </summary>
    public readonly string TitleId;
    /// <summary>
    /// 各个描述多语言ID<br/>金猪描述|金猪升级描述|金猪解锁描述|金猪满描述
    /// </summary>
    public readonly string[] DescId;
    /// <summary>
    /// 金猪对应资源ID<br/>主界面icon|活动面板图标
    /// </summary>
    public readonly string[] ResId;


    public const int __ID__ = -1832661855;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "ActivityId:" + ActivityId + ","
        + "Type:" + Type + ","
        + "ShopId:" + ShopId + ","
        + "BaseValue:" + BaseValue + ","
        + "InitValue:" + InitValue + ","
        + "MaxValue:" + MaxValue + ","
        + "LayerAdd:" + LayerAdd + ","
        + "TimeLimit:" + TimeLimit + ","
        + "TitleId:" + TitleId + ","
        + "DescId:" + Luban.StringUtil.CollectionToString(DescId) + ","
        + "ResId:" + Luban.StringUtil.CollectionToString(ResId) + ","
        + "}";
    }
}
}

