
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class Shop_Ad : Luban.BeanBase
{
    public Shop_Ad(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        id = (int)_obj.GetValue("id");
        adTimes = (int)_obj.GetValue("adTimes");
        adCountDown = (int)_obj.GetValue("adCountDown");
        languageId = (string)_obj.GetValue("languageId");
    }

    public static Shop_Ad DeserializeShop_Ad(JToken _buf)
    {
        return new Shop_Ad(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 广告可观看次数
    /// </summary>
    public readonly int adTimes;
    /// <summary>
    /// 广告免费领取倒计时(秒)
    /// </summary>
    public readonly int adCountDown;
    /// <summary>
    /// 描述id
    /// </summary>
    public readonly string languageId;


    public const int __ID__ = -563233268;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "adTimes:" + adTimes + ","
        + "adCountDown:" + adCountDown + ","
        + "languageId:" + languageId + ","
        + "}";
    }
}
}

