
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class Sound_sound : Luban.BeanBase
{
    public Sound_sound(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ID = (int)_obj.GetValue("ID");
        path = (string)_obj.GetValue("path");
        volume = (float)_obj.GetValue("volume");
    }

    public static Sound_sound DeserializeSound_sound(JToken _buf)
    {
        return new Sound_sound(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 音效路径
    /// </summary>
    public readonly string path;
    /// <summary>
    /// 音量
    /// </summary>
    public readonly float volume;


    public const int __ID__ = -358984257;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "path:" + path + ","
        + "volume:" + volume + ","
        + "}";
    }
}
}

