
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class Sprite_Sprite : Luban.BeanBase
{
    public Sprite_Sprite(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        id = (int)_obj.GetValue("id");
        path = (string)_obj.GetValue("path");
    }

    public static Sprite_Sprite DeserializeSprite_Sprite(JToken _buf)
    {
        return new Sprite_Sprite(_buf);
    }

    /// <summary>
    /// 内容ID
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 图片路径
    /// </summary>
    public readonly string path;


    public const int __ID__ = -1837801089;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "path:" + path + ","
        + "}";
    }
}
}

