
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace HotFix.Cfg
{

public sealed partial class TalentLegacy_career : Luban.BeanBase
{
    public TalentLegacy_career(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        id = (int)_obj.GetValue("id");
        nameID = (string)_obj.GetValue("nameID");
        isOpen = (int)_obj.GetValue("isOpen");
        condition = (string)_obj.GetValue("condition");
        previewIconId = (int)_obj.GetValue("previewIconId");
        previewIcon = (string)_obj.GetValue("previewIcon");
        unLockTips = (string)_obj.GetValue("unLockTips");
    }

    public static TalentLegacy_career DeserializeTalentLegacy_career(JToken _buf)
    {
        return new TalentLegacy_career(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 名字多语言
    /// </summary>
    public readonly string nameID;
    /// <summary>
    /// 是否开启
    /// </summary>
    public readonly int isOpen;
    /// <summary>
    /// 解锁条件
    /// </summary>
    public readonly string condition;
    /// <summary>
    /// 预览图图集
    /// </summary>
    public readonly int previewIconId;
    /// <summary>
    /// 预览图
    /// </summary>
    public readonly string previewIcon;
    /// <summary>
    /// 解锁描述
    /// </summary>
    public readonly string unLockTips;


    public const int __ID__ = 30479112;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "nameID:" + nameID + ","
        + "isOpen:" + isOpen + ","
        + "condition:" + condition + ","
        + "previewIconId:" + previewIconId + ","
        + "previewIcon:" + previewIcon + ","
        + "unLockTips:" + unLockTips + ","
        + "}";
    }
}
}

