
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace HotFix.Cfg
{

/// <summary>
/// Generated from ActivityHolidayFeast.xlsx sheet Act
/// </summary>
public partial class TbActivityHolidayFeast_Act
{
    private readonly System.Collections.Generic.Dictionary<int, ActivityHolidayFeast_Act> _dataMap;
    private readonly System.Collections.Generic.List<ActivityHolidayFeast_Act> _dataList;
    
    public TbActivityHolidayFeast_Act(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ActivityHolidayFeast_Act>();
        _dataList = new System.Collections.Generic.List<ActivityHolidayFeast_Act>();
        
        foreach(JObject _ele in _buf)
        {
            ActivityHolidayFeast_Act _v;
            _v = global::HotFix.Cfg.ActivityHolidayFeast_Act.DeserializeActivityHolidayFeast_Act(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, ActivityHolidayFeast_Act> DataMap => _dataMap;
    public System.Collections.Generic.List<ActivityHolidayFeast_Act> DataList => _dataList;

    public ActivityHolidayFeast_Act GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ActivityHolidayFeast_Act Get(int key) => _dataMap[key];
    public ActivityHolidayFeast_Act this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

