
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace HotFix.Cfg
{

/// <summary>
/// Generated from ArtMember.xlsx sheet morph
/// </summary>
public partial class TbArtMember_morph
{
    private readonly System.Collections.Generic.Dictionary<int, ArtMember_morph> _dataMap;
    private readonly System.Collections.Generic.List<ArtMember_morph> _dataList;
    
    public TbArtMember_morph(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ArtMember_morph>();
        _dataList = new System.Collections.Generic.List<ArtMember_morph>();
        
        foreach(JObject _ele in _buf)
        {
            ArtMember_morph _v;
            _v = global::HotFix.Cfg.ArtMember_morph.DeserializeArtMember_morph(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, ArtMember_morph> DataMap => _dataMap;
    public System.Collections.Generic.List<ArtMember_morph> DataList => _dataList;

    public ArtMember_morph GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ArtMember_morph Get(int key) => _dataMap[key];
    public ArtMember_morph this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

