
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
/// <summary>
/// Generated from Artifact.xlsx sheet artifactStage
/// </summary>
public partial class TbArtifact_artifactStage
{
    private readonly System.Collections.Generic.Dictionary<int, Artifact_artifactStage> _dataMap;
    private readonly System.Collections.Generic.List<Artifact_artifactStage> _dataList;
    
    public TbArtifact_artifactStage(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Artifact_artifactStage>();
        _dataList = new System.Collections.Generic.List<Artifact_artifactStage>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Artifact_artifactStage _v;
            _v = global::HotFix.Cfg.Artifact_artifactStage.DeserializeArtifact_artifactStage(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Artifact_artifactStage> DataMap => _dataMap;
    public System.Collections.Generic.List<Artifact_artifactStage> DataList => _dataList;

    public Artifact_artifactStage GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Artifact_artifactStage Get(int key) => _dataMap[key];
    public Artifact_artifactStage this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

