
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
/// <summary>
/// Generated from ArtSagecraft.xlsx sheet Sagecraft
/// </summary>
public partial class TbArtSagecraft_Sagecraft
{
    private readonly System.Collections.Generic.Dictionary<int, ArtSagecraft_Sagecraft> _dataMap;
    private readonly System.Collections.Generic.List<ArtSagecraft_Sagecraft> _dataList;
    
    public TbArtSagecraft_Sagecraft(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ArtSagecraft_Sagecraft>();
        _dataList = new System.Collections.Generic.List<ArtSagecraft_Sagecraft>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            ArtSagecraft_Sagecraft _v;
            _v = global::HotFix.Cfg.ArtSagecraft_Sagecraft.DeserializeArtSagecraft_Sagecraft(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ArtSagecraft_Sagecraft> DataMap => _dataMap;
    public System.Collections.Generic.List<ArtSagecraft_Sagecraft> DataList => _dataList;

    public ArtSagecraft_Sagecraft GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ArtSagecraft_Sagecraft Get(int key) => _dataMap[key];
    public ArtSagecraft_Sagecraft this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

