
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace HotFix.Cfg
{

/// <summary>
/// Generated from Artifact.xlsx sheet advanceArtifact
/// </summary>
public partial class TbArtifact_advanceArtifact
{
    private readonly System.Collections.Generic.Dictionary<int, Artifact_advanceArtifact> _dataMap;
    private readonly System.Collections.Generic.List<Artifact_advanceArtifact> _dataList;
    
    public TbArtifact_advanceArtifact(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Artifact_advanceArtifact>();
        _dataList = new System.Collections.Generic.List<Artifact_advanceArtifact>();
        
        foreach(JObject _ele in _buf)
        {
            Artifact_advanceArtifact _v;
            _v = global::HotFix.Cfg.Artifact_advanceArtifact.DeserializeArtifact_advanceArtifact(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, Artifact_advanceArtifact> DataMap => _dataMap;
    public System.Collections.Generic.List<Artifact_advanceArtifact> DataList => _dataList;

    public Artifact_advanceArtifact GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Artifact_advanceArtifact Get(int key) => _dataMap[key];
    public Artifact_advanceArtifact this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

