
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace HotFix.Cfg
{

/// <summary>
/// Generated from BattleMain.xlsx sheet chapter
/// </summary>
public partial class TbBattleMain_chapter
{
    private readonly System.Collections.Generic.Dictionary<int, BattleMain_chapter> _dataMap;
    private readonly System.Collections.Generic.List<BattleMain_chapter> _dataList;
    
    public TbBattleMain_chapter(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, BattleMain_chapter>();
        _dataList = new System.Collections.Generic.List<BattleMain_chapter>();
        
        foreach(JObject _ele in _buf)
        {
            BattleMain_chapter _v;
            _v = global::HotFix.Cfg.BattleMain_chapter.DeserializeBattleMain_chapter(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, BattleMain_chapter> DataMap => _dataMap;
    public System.Collections.Generic.List<BattleMain_chapter> DataList => _dataList;

    public BattleMain_chapter GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public BattleMain_chapter Get(int key) => _dataMap[key];
    public BattleMain_chapter this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

