
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace HotFix.Cfg
{

/// <summary>
/// Generated from Bingo.xlsx sheet Shop
/// </summary>
public partial class TbBingo_Shop
{
    private readonly System.Collections.Generic.Dictionary<int, Bingo_Shop> _dataMap;
    private readonly System.Collections.Generic.List<Bingo_Shop> _dataList;
    
    public TbBingo_Shop(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Bingo_Shop>();
        _dataList = new System.Collections.Generic.List<Bingo_Shop>();
        
        foreach(JObject _ele in _buf)
        {
            Bingo_Shop _v;
            _v = global::HotFix.Cfg.Bingo_Shop.DeserializeBingo_Shop(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, Bingo_Shop> DataMap => _dataMap;
    public System.Collections.Generic.List<Bingo_Shop> DataList => _dataList;

    public Bingo_Shop GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Bingo_Shop Get(int key) => _dataMap[key];
    public Bingo_Shop this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

