
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace HotFix.Cfg
{

/// <summary>
/// Generated from Chapter.xlsx sheet starReward
/// </summary>
public partial class TbChapter_starReward
{
    private readonly System.Collections.Generic.Dictionary<int, Chapter_starReward> _dataMap;
    private readonly System.Collections.Generic.List<Chapter_starReward> _dataList;
    
    public TbChapter_starReward(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Chapter_starReward>();
        _dataList = new System.Collections.Generic.List<Chapter_starReward>();
        
        foreach(JObject _ele in _buf)
        {
            Chapter_starReward _v;
            _v = global::HotFix.Cfg.Chapter_starReward.DeserializeChapter_starReward(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, Chapter_starReward> DataMap => _dataMap;
    public System.Collections.Generic.List<Chapter_starReward> DataList => _dataList;

    public Chapter_starReward GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Chapter_starReward Get(int key) => _dataMap[key];
    public Chapter_starReward this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

