
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace HotFix.Cfg
{

/// <summary>
/// Generated from ChapterHard.xlsx sheet chapterHardShop
/// </summary>
public partial class TbChapterHard_chapterHardShop
{
    private readonly System.Collections.Generic.Dictionary<int, ChapterHard_chapterHardShop> _dataMap;
    private readonly System.Collections.Generic.List<ChapterHard_chapterHardShop> _dataList;
    
    public TbChapterHard_chapterHardShop(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ChapterHard_chapterHardShop>();
        _dataList = new System.Collections.Generic.List<ChapterHard_chapterHardShop>();
        
        foreach(JObject _ele in _buf)
        {
            ChapterHard_chapterHardShop _v;
            _v = global::HotFix.Cfg.ChapterHard_chapterHardShop.DeserializeChapterHard_chapterHardShop(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, ChapterHard_chapterHardShop> DataMap => _dataMap;
    public System.Collections.Generic.List<ChapterHard_chapterHardShop> DataList => _dataList;

    public ChapterHard_chapterHardShop GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ChapterHard_chapterHardShop Get(int key) => _dataMap[key];
    public ChapterHard_chapterHardShop this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

