
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace HotFix.Cfg
{

/// <summary>
/// Generated from ChapterMiniGame.xlsx sheet slotReward
/// </summary>
public partial class TbChapterMiniGame_slotReward
{
    private readonly System.Collections.Generic.Dictionary<int, ChapterMiniGame_slotReward> _dataMap;
    private readonly System.Collections.Generic.List<ChapterMiniGame_slotReward> _dataList;
    
    public TbChapterMiniGame_slotReward(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ChapterMiniGame_slotReward>();
        _dataList = new System.Collections.Generic.List<ChapterMiniGame_slotReward>();
        
        foreach(JObject _ele in _buf)
        {
            ChapterMiniGame_slotReward _v;
            _v = global::HotFix.Cfg.ChapterMiniGame_slotReward.DeserializeChapterMiniGame_slotReward(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, ChapterMiniGame_slotReward> DataMap => _dataMap;
    public System.Collections.Generic.List<ChapterMiniGame_slotReward> DataList => _dataList;

    public ChapterMiniGame_slotReward GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ChapterMiniGame_slotReward Get(int key) => _dataMap[key];
    public ChapterMiniGame_slotReward this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

