
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace HotFix.Cfg
{

/// <summary>
/// Generated from ChapterHard.xlsx sheet eventRes
/// </summary>
public partial class TbChapterHard_eventRes
{
    private readonly System.Collections.Generic.Dictionary<int, ChapterHard_eventRes> _dataMap;
    private readonly System.Collections.Generic.List<ChapterHard_eventRes> _dataList;
    
    public TbChapterHard_eventRes(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ChapterHard_eventRes>();
        _dataList = new System.Collections.Generic.List<ChapterHard_eventRes>();
        
        foreach(JObject _ele in _buf)
        {
            ChapterHard_eventRes _v;
            _v = global::HotFix.Cfg.ChapterHard_eventRes.DeserializeChapterHard_eventRes(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, ChapterHard_eventRes> DataMap => _dataMap;
    public System.Collections.Generic.List<ChapterHard_eventRes> DataList => _dataList;

    public ChapterHard_eventRes GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ChapterHard_eventRes Get(int key) => _dataMap[key];
    public ChapterHard_eventRes this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

