
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace HotFix.Cfg
{

/// <summary>
/// Generated from CrossArena.xlsx sheet CrossArenaLevel
/// </summary>
public partial class TbCrossArena_CrossArenaLevel
{
    private readonly System.Collections.Generic.Dictionary<int, CrossArena_CrossArenaLevel> _dataMap;
    private readonly System.Collections.Generic.List<CrossArena_CrossArenaLevel> _dataList;
    
    public TbCrossArena_CrossArenaLevel(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, CrossArena_CrossArenaLevel>();
        _dataList = new System.Collections.Generic.List<CrossArena_CrossArenaLevel>();
        
        foreach(JObject _ele in _buf)
        {
            CrossArena_CrossArenaLevel _v;
            _v = global::HotFix.Cfg.CrossArena_CrossArenaLevel.DeserializeCrossArena_CrossArenaLevel(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Level, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, CrossArena_CrossArenaLevel> DataMap => _dataMap;
    public System.Collections.Generic.List<CrossArena_CrossArenaLevel> DataList => _dataList;

    public CrossArena_CrossArenaLevel GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public CrossArena_CrossArenaLevel Get(int key) => _dataMap[key];
    public CrossArena_CrossArenaLevel this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

