
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
/// <summary>
/// Generated from DailyLevel.xlsx sheet dailyLevelRank
/// </summary>
public partial class TbDailyLevel_dailyLevelRank
{
    private readonly System.Collections.Generic.Dictionary<int, DailyLevel_dailyLevelRank> _dataMap;
    private readonly System.Collections.Generic.List<DailyLevel_dailyLevelRank> _dataList;
    
    public TbDailyLevel_dailyLevelRank(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, DailyLevel_dailyLevelRank>();
        _dataList = new System.Collections.Generic.List<DailyLevel_dailyLevelRank>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            DailyLevel_dailyLevelRank _v;
            _v = global::HotFix.Cfg.DailyLevel_dailyLevelRank.DeserializeDailyLevel_dailyLevelRank(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DailyLevel_dailyLevelRank> DataMap => _dataMap;
    public System.Collections.Generic.List<DailyLevel_dailyLevelRank> DataList => _dataList;

    public DailyLevel_dailyLevelRank GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DailyLevel_dailyLevelRank Get(int key) => _dataMap[key];
    public DailyLevel_dailyLevelRank this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

