
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
/// <summary>
/// Generated from DailyLevel.xlsx sheet dailyLevelBase
/// </summary>
public partial class TbDailyLevel_dailyLevelBase
{
    private readonly System.Collections.Generic.Dictionary<int, DailyLevel_dailyLevelBase> _dataMap;
    private readonly System.Collections.Generic.List<DailyLevel_dailyLevelBase> _dataList;
    
    public TbDailyLevel_dailyLevelBase(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, DailyLevel_dailyLevelBase>();
        _dataList = new System.Collections.Generic.List<DailyLevel_dailyLevelBase>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            DailyLevel_dailyLevelBase _v;
            _v = global::HotFix.Cfg.DailyLevel_dailyLevelBase.DeserializeDailyLevel_dailyLevelBase(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DailyLevel_dailyLevelBase> DataMap => _dataMap;
    public System.Collections.Generic.List<DailyLevel_dailyLevelBase> DataList => _dataList;

    public DailyLevel_dailyLevelBase GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DailyLevel_dailyLevelBase Get(int key) => _dataMap[key];
    public DailyLevel_dailyLevelBase this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

