
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
/// <summary>
/// Generated from Dungeon.xlsx sheet DungeonLevel
/// </summary>
public partial class TbDungeon_DungeonLevel
{
    private readonly System.Collections.Generic.Dictionary<int, Dungeon_DungeonLevel> _dataMap;
    private readonly System.Collections.Generic.List<Dungeon_DungeonLevel> _dataList;
    
    public TbDungeon_DungeonLevel(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Dungeon_DungeonLevel>();
        _dataList = new System.Collections.Generic.List<Dungeon_DungeonLevel>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Dungeon_DungeonLevel _v;
            _v = global::HotFix.Cfg.Dungeon_DungeonLevel.DeserializeDungeon_DungeonLevel(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Dungeon_DungeonLevel> DataMap => _dataMap;
    public System.Collections.Generic.List<Dungeon_DungeonLevel> DataList => _dataList;

    public Dungeon_DungeonLevel GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Dungeon_DungeonLevel Get(int key) => _dataMap[key];
    public Dungeon_DungeonLevel this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

