
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace HotFix.Cfg
{

/// <summary>
/// Generated from Equip.xlsx sheet equip
/// </summary>
public partial class TbEquip_equip
{
    private readonly System.Collections.Generic.Dictionary<int, Equip_equip> _dataMap;
    private readonly System.Collections.Generic.List<Equip_equip> _dataList;
    
    public TbEquip_equip(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Equip_equip>();
        _dataList = new System.Collections.Generic.List<Equip_equip>();
        
        foreach(JObject _ele in _buf)
        {
            Equip_equip _v;
            _v = global::HotFix.Cfg.Equip_equip.DeserializeEquip_equip(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, Equip_equip> DataMap => _dataMap;
    public System.Collections.Generic.List<Equip_equip> DataList => _dataList;

    public Equip_equip GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Equip_equip Get(int key) => _dataMap[key];
    public Equip_equip this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

