
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
/// <summary>
/// Generated from FestivalTurntable.xlsx sheet FestivalTurntableReward
/// </summary>
public partial class TbFestivalTurntable_FestivalTurntableReward
{
    private readonly System.Collections.Generic.Dictionary<int, FestivalTurntable_FestivalTurntableReward> _dataMap;
    private readonly System.Collections.Generic.List<FestivalTurntable_FestivalTurntableReward> _dataList;
    
    public TbFestivalTurntable_FestivalTurntableReward(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, FestivalTurntable_FestivalTurntableReward>();
        _dataList = new System.Collections.Generic.List<FestivalTurntable_FestivalTurntableReward>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            FestivalTurntable_FestivalTurntableReward _v;
            _v = global::HotFix.Cfg.FestivalTurntable_FestivalTurntableReward.DeserializeFestivalTurntable_FestivalTurntableReward(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, FestivalTurntable_FestivalTurntableReward> DataMap => _dataMap;
    public System.Collections.Generic.List<FestivalTurntable_FestivalTurntableReward> DataList => _dataList;

    public FestivalTurntable_FestivalTurntableReward GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public FestivalTurntable_FestivalTurntableReward Get(int key) => _dataMap[key];
    public FestivalTurntable_FestivalTurntableReward this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

