
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
/// <summary>
/// Generated from Fishing.xlsx sheet area
/// </summary>
public partial class TbFishing_area
{
    private readonly System.Collections.Generic.Dictionary<int, Fishing_area> _dataMap;
    private readonly System.Collections.Generic.List<Fishing_area> _dataList;
    
    public TbFishing_area(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Fishing_area>();
        _dataList = new System.Collections.Generic.List<Fishing_area>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Fishing_area _v;
            _v = global::HotFix.Cfg.Fishing_area.DeserializeFishing_area(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Fishing_area> DataMap => _dataMap;
    public System.Collections.Generic.List<Fishing_area> DataList => _dataList;

    public Fishing_area GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Fishing_area Get(int key) => _dataMap[key];
    public Fishing_area this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

