
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace HotFix.Cfg
{

/// <summary>
/// Generated from GameMember.xlsx sheet npcFunction
/// </summary>
public partial class TbGameMember_npcFunction
{
    private readonly System.Collections.Generic.Dictionary<int, GameMember_npcFunction> _dataMap;
    private readonly System.Collections.Generic.List<GameMember_npcFunction> _dataList;
    
    public TbGameMember_npcFunction(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, GameMember_npcFunction>();
        _dataList = new System.Collections.Generic.List<GameMember_npcFunction>();
        
        foreach(JObject _ele in _buf)
        {
            GameMember_npcFunction _v;
            _v = global::HotFix.Cfg.GameMember_npcFunction.DeserializeGameMember_npcFunction(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, GameMember_npcFunction> DataMap => _dataMap;
    public System.Collections.Generic.List<GameMember_npcFunction> DataList => _dataList;

    public GameMember_npcFunction GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GameMember_npcFunction Get(int key) => _dataMap[key];
    public GameMember_npcFunction this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

