
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace HotFix.Cfg
{

/// <summary>
/// Generated from GameMember.xlsx sheet aiType
/// </summary>
public partial class TbGameMember_aiType
{
    private readonly System.Collections.Generic.Dictionary<int, GameMember_aiType> _dataMap;
    private readonly System.Collections.Generic.List<GameMember_aiType> _dataList;
    
    public TbGameMember_aiType(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, GameMember_aiType>();
        _dataList = new System.Collections.Generic.List<GameMember_aiType>();
        
        foreach(JObject _ele in _buf)
        {
            GameMember_aiType _v;
            _v = global::HotFix.Cfg.GameMember_aiType.DeserializeGameMember_aiType(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, GameMember_aiType> DataMap => _dataMap;
    public System.Collections.Generic.List<GameMember_aiType> DataList => _dataList;

    public GameMember_aiType GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GameMember_aiType Get(int key) => _dataMap[key];
    public GameMember_aiType this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

