
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
/// <summary>
/// Generated from GameSkillBuild.xlsx sheet skillRandom
/// </summary>
public partial class TbGameSkillBuild_skillRandom
{
    private readonly System.Collections.Generic.Dictionary<int, GameSkillBuild_skillRandom> _dataMap;
    private readonly System.Collections.Generic.List<GameSkillBuild_skillRandom> _dataList;
    
    public TbGameSkillBuild_skillRandom(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, GameSkillBuild_skillRandom>();
        _dataList = new System.Collections.Generic.List<GameSkillBuild_skillRandom>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            GameSkillBuild_skillRandom _v;
            _v = global::HotFix.Cfg.GameSkillBuild_skillRandom.DeserializeGameSkillBuild_skillRandom(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, GameSkillBuild_skillRandom> DataMap => _dataMap;
    public System.Collections.Generic.List<GameSkillBuild_skillRandom> DataList => _dataList;

    public GameSkillBuild_skillRandom GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GameSkillBuild_skillRandom Get(int key) => _dataMap[key];
    public GameSkillBuild_skillRandom this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

