
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace HotFix.Cfg
{

/// <summary>
/// Generated from GameConfigCN.xlsx sheet Config
/// </summary>
public partial class TbGameConfigCN_Config
{
    private readonly System.Collections.Generic.Dictionary<int, GameConfigCN_Config> _dataMap;
    private readonly System.Collections.Generic.List<GameConfigCN_Config> _dataList;
    
    public TbGameConfigCN_Config(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, GameConfigCN_Config>();
        _dataList = new System.Collections.Generic.List<GameConfigCN_Config>();
        
        foreach(JObject _ele in _buf)
        {
            GameConfigCN_Config _v;
            _v = global::HotFix.Cfg.GameConfigCN_Config.DeserializeGameConfigCN_Config(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, GameConfigCN_Config> DataMap => _dataMap;
    public System.Collections.Generic.List<GameConfigCN_Config> DataList => _dataList;

    public GameConfigCN_Config GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GameConfigCN_Config Get(int key) => _dataMap[key];
    public GameConfigCN_Config this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

