
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace HotFix.Cfg
{

/// <summary>
/// Generated from Gem.xlsx sheet GemEffect
/// </summary>
public partial class TbGem_GemEffect
{
    private readonly System.Collections.Generic.Dictionary<int, Gem_GemEffect> _dataMap;
    private readonly System.Collections.Generic.List<Gem_GemEffect> _dataList;
    
    public TbGem_GemEffect(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Gem_GemEffect>();
        _dataList = new System.Collections.Generic.List<Gem_GemEffect>();
        
        foreach(JObject _ele in _buf)
        {
            Gem_GemEffect _v;
            _v = global::HotFix.Cfg.Gem_GemEffect.DeserializeGem_GemEffect(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, Gem_GemEffect> DataMap => _dataMap;
    public System.Collections.Generic.List<Gem_GemEffect> DataList => _dataList;

    public Gem_GemEffect GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Gem_GemEffect Get(int key) => _dataMap[key];
    public Gem_GemEffect this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

