
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace HotFix.Cfg
{

/// <summary>
/// Generated from Guild.xlsx sheet guildConst
/// </summary>
public partial class TbGuild_guildConst
{
    private readonly System.Collections.Generic.Dictionary<int, Guild_guildConst> _dataMap;
    private readonly System.Collections.Generic.List<Guild_guildConst> _dataList;
    
    public TbGuild_guildConst(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Guild_guildConst>();
        _dataList = new System.Collections.Generic.List<Guild_guildConst>();
        
        foreach(JObject _ele in _buf)
        {
            Guild_guildConst _v;
            _v = global::HotFix.Cfg.Guild_guildConst.DeserializeGuild_guildConst(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, Guild_guildConst> DataMap => _dataMap;
    public System.Collections.Generic.List<Guild_guildConst> DataList => _dataList;

    public Guild_guildConst GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Guild_guildConst Get(int key) => _dataMap[key];
    public Guild_guildConst this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

