
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
/// <summary>
/// Generated from GuildWar.xlsx sheet GuildRank
/// </summary>
public partial class TbGuildWar_GuildRank
{
    private readonly System.Collections.Generic.Dictionary<int, GuildWar_GuildRank> _dataMap;
    private readonly System.Collections.Generic.List<GuildWar_GuildRank> _dataList;
    
    public TbGuildWar_GuildRank(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, GuildWar_GuildRank>();
        _dataList = new System.Collections.Generic.List<GuildWar_GuildRank>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            GuildWar_GuildRank _v;
            _v = global::HotFix.Cfg.GuildWar_GuildRank.DeserializeGuildWar_GuildRank(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, GuildWar_GuildRank> DataMap => _dataMap;
    public System.Collections.Generic.List<GuildWar_GuildRank> DataList => _dataList;

    public GuildWar_GuildRank GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GuildWar_GuildRank Get(int key) => _dataMap[key];
    public GuildWar_GuildRank this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

