
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace HotFix.Cfg
{

/// <summary>
/// Generated from GuildWar.xlsx sheet GuildRankPre
/// </summary>
public partial class TbGuildWar_GuildRankPre
{
    private readonly System.Collections.Generic.Dictionary<int, GuildWar_GuildRankPre> _dataMap;
    private readonly System.Collections.Generic.List<GuildWar_GuildRankPre> _dataList;
    
    public TbGuildWar_GuildRankPre(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, GuildWar_GuildRankPre>();
        _dataList = new System.Collections.Generic.List<GuildWar_GuildRankPre>();
        
        foreach(JObject _ele in _buf)
        {
            GuildWar_GuildRankPre _v;
            _v = global::HotFix.Cfg.GuildWar_GuildRankPre.DeserializeGuildWar_GuildRankPre(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, GuildWar_GuildRankPre> DataMap => _dataMap;
    public System.Collections.Generic.List<GuildWar_GuildRankPre> DataList => _dataList;

    public GuildWar_GuildRankPre GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GuildWar_GuildRankPre Get(int key) => _dataMap[key];
    public GuildWar_GuildRankPre this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

