
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace HotFix.Cfg
{

/// <summary>
/// Generated from GuildBOSS.xlsx sheet guildBossMonster
/// </summary>
public partial class TbGuildBOSS_guildBossMonster
{
    private readonly System.Collections.Generic.Dictionary<int, GuildBOSS_guildBossMonster> _dataMap;
    private readonly System.Collections.Generic.List<GuildBOSS_guildBossMonster> _dataList;
    
    public TbGuildBOSS_guildBossMonster(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, GuildBOSS_guildBossMonster>();
        _dataList = new System.Collections.Generic.List<GuildBOSS_guildBossMonster>();
        
        foreach(JObject _ele in _buf)
        {
            GuildBOSS_guildBossMonster _v;
            _v = global::HotFix.Cfg.GuildBOSS_guildBossMonster.DeserializeGuildBOSS_guildBossMonster(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, GuildBOSS_guildBossMonster> DataMap => _dataMap;
    public System.Collections.Generic.List<GuildBOSS_guildBossMonster> DataList => _dataList;

    public GuildBOSS_guildBossMonster GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GuildBOSS_guildBossMonster Get(int key) => _dataMap[key];
    public GuildBOSS_guildBossMonster this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

