
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
/// <summary>
/// Generated from GuildWar.xlsx sheet GuildTower
/// </summary>
public partial class TbGuildWar_GuildTower
{
    private readonly System.Collections.Generic.Dictionary<int, GuildWar_GuildTower> _dataMap;
    private readonly System.Collections.Generic.List<GuildWar_GuildTower> _dataList;
    
    public TbGuildWar_GuildTower(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, GuildWar_GuildTower>();
        _dataList = new System.Collections.Generic.List<GuildWar_GuildTower>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            GuildWar_GuildTower _v;
            _v = global::HotFix.Cfg.GuildWar_GuildTower.DeserializeGuildWar_GuildTower(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, GuildWar_GuildTower> DataMap => _dataMap;
    public System.Collections.Generic.List<GuildWar_GuildTower> DataList => _dataList;

    public GuildWar_GuildTower GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GuildWar_GuildTower Get(int key) => _dataMap[key];
    public GuildWar_GuildTower this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

