
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace HotFix.Cfg
{

/// <summary>
/// Generated from GuildWar.xlsx sheet WarTime
/// </summary>
public partial class TbGuildWar_WarTime
{
    private readonly System.Collections.Generic.Dictionary<int, GuildWar_WarTime> _dataMap;
    private readonly System.Collections.Generic.List<GuildWar_WarTime> _dataList;
    
    public TbGuildWar_WarTime(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, GuildWar_WarTime>();
        _dataList = new System.Collections.Generic.List<GuildWar_WarTime>();
        
        foreach(JObject _ele in _buf)
        {
            GuildWar_WarTime _v;
            _v = global::HotFix.Cfg.GuildWar_WarTime.DeserializeGuildWar_WarTime(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, GuildWar_WarTime> DataMap => _dataMap;
    public System.Collections.Generic.List<GuildWar_WarTime> DataList => _dataList;

    public GuildWar_WarTime GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GuildWar_WarTime Get(int key) => _dataMap[key];
    public GuildWar_WarTime this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

