
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
/// <summary>
/// Generated from Guide.xlsx sheet guide
/// </summary>
public partial class TbGuide_guide
{
    private readonly System.Collections.Generic.Dictionary<int, Guide_guide> _dataMap;
    private readonly System.Collections.Generic.List<Guide_guide> _dataList;
    
    public TbGuide_guide(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Guide_guide>();
        _dataList = new System.Collections.Generic.List<Guide_guide>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Guide_guide _v;
            _v = global::HotFix.Cfg.Guide_guide.DeserializeGuide_guide(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Guide_guide> DataMap => _dataMap;
    public System.Collections.Generic.List<Guide_guide> DataList => _dataList;

    public Guide_guide GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Guide_guide Get(int key) => _dataMap[key];
    public Guide_guide this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

