
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace HotFix.Cfg
{

/// <summary>
/// Generated from IAP.xlsx sheet PaySignIn
/// </summary>
public partial class TbIAP_PaySignIn
{
    private readonly System.Collections.Generic.Dictionary<int, IAP_PaySignIn> _dataMap;
    private readonly System.Collections.Generic.List<IAP_PaySignIn> _dataList;
    
    public TbIAP_PaySignIn(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, IAP_PaySignIn>();
        _dataList = new System.Collections.Generic.List<IAP_PaySignIn>();
        
        foreach(JObject _ele in _buf)
        {
            IAP_PaySignIn _v;
            _v = global::HotFix.Cfg.IAP_PaySignIn.DeserializeIAP_PaySignIn(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, IAP_PaySignIn> DataMap => _dataMap;
    public System.Collections.Generic.List<IAP_PaySignIn> DataList => _dataList;

    public IAP_PaySignIn GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public IAP_PaySignIn Get(int key) => _dataMap[key];
    public IAP_PaySignIn this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

