
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace HotFix.Cfg
{

/// <summary>
/// Generated from NewWorld.xlsx sheet newWorldTask
/// </summary>
public partial class TbNewWorld_newWorldTask
{
    private readonly System.Collections.Generic.Dictionary<int, NewWorld_newWorldTask> _dataMap;
    private readonly System.Collections.Generic.List<NewWorld_newWorldTask> _dataList;
    
    public TbNewWorld_newWorldTask(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, NewWorld_newWorldTask>();
        _dataList = new System.Collections.Generic.List<NewWorld_newWorldTask>();
        
        foreach(JObject _ele in _buf)
        {
            NewWorld_newWorldTask _v;
            _v = global::HotFix.Cfg.NewWorld_newWorldTask.DeserializeNewWorld_newWorldTask(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, NewWorld_newWorldTask> DataMap => _dataMap;
    public System.Collections.Generic.List<NewWorld_newWorldTask> DataList => _dataList;

    public NewWorld_newWorldTask GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public NewWorld_newWorldTask Get(int key) => _dataMap[key];
    public NewWorld_newWorldTask this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

