
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace HotFix.Cfg
{

/// <summary>
/// Generated from Pet.xlsx sheet pet
/// </summary>
public partial class TbPet_pet
{
    private readonly System.Collections.Generic.Dictionary<int, Pet_pet> _dataMap;
    private readonly System.Collections.Generic.List<Pet_pet> _dataList;
    
    public TbPet_pet(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Pet_pet>();
        _dataList = new System.Collections.Generic.List<Pet_pet>();
        
        foreach(JObject _ele in _buf)
        {
            Pet_pet _v;
            _v = global::HotFix.Cfg.Pet_pet.DeserializePet_pet(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, Pet_pet> DataMap => _dataMap;
    public System.Collections.Generic.List<Pet_pet> DataList => _dataList;

    public Pet_pet GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Pet_pet Get(int key) => _dataMap[key];
    public Pet_pet this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

