
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace HotFix.Cfg
{

/// <summary>
/// Generated from Plinko.xlsx sheet PlinkoRewardSpecialProbability
/// </summary>
public partial class TbPlinko_PlinkoRewardSpecialProbability
{
    private readonly System.Collections.Generic.Dictionary<int, Plinko_PlinkoRewardSpecialProbability> _dataMap;
    private readonly System.Collections.Generic.List<Plinko_PlinkoRewardSpecialProbability> _dataList;
    
    public TbPlinko_PlinkoRewardSpecialProbability(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Plinko_PlinkoRewardSpecialProbability>();
        _dataList = new System.Collections.Generic.List<Plinko_PlinkoRewardSpecialProbability>();
        
        foreach(JObject _ele in _buf)
        {
            Plinko_PlinkoRewardSpecialProbability _v;
            _v = global::HotFix.Cfg.Plinko_PlinkoRewardSpecialProbability.DeserializePlinko_PlinkoRewardSpecialProbability(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, Plinko_PlinkoRewardSpecialProbability> DataMap => _dataMap;
    public System.Collections.Generic.List<Plinko_PlinkoRewardSpecialProbability> DataList => _dataList;

    public Plinko_PlinkoRewardSpecialProbability GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Plinko_PlinkoRewardSpecialProbability Get(int key) => _dataMap[key];
    public Plinko_PlinkoRewardSpecialProbability this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

