
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
/// <summary>
/// Generated from Quality.xlsx sheet collectionQuality
/// </summary>
public partial class TbQuality_collectionQuality
{
    private readonly System.Collections.Generic.Dictionary<int, Quality_collectionQuality> _dataMap;
    private readonly System.Collections.Generic.List<Quality_collectionQuality> _dataList;
    
    public TbQuality_collectionQuality(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Quality_collectionQuality>();
        _dataList = new System.Collections.Generic.List<Quality_collectionQuality>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Quality_collectionQuality _v;
            _v = global::HotFix.Cfg.Quality_collectionQuality.DeserializeQuality_collectionQuality(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Quality_collectionQuality> DataMap => _dataMap;
    public System.Collections.Generic.List<Quality_collectionQuality> DataList => _dataList;

    public Quality_collectionQuality GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Quality_collectionQuality Get(int key) => _dataMap[key];
    public Quality_collectionQuality this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

