
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace HotFix.Cfg
{

/// <summary>
/// Generated from Quality.xlsx sheet CannonQuality
/// </summary>
public partial class TbQuality_CannonQuality
{
    private readonly System.Collections.Generic.Dictionary<int, Quality_CannonQuality> _dataMap;
    private readonly System.Collections.Generic.List<Quality_CannonQuality> _dataList;
    
    public TbQuality_CannonQuality(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Quality_CannonQuality>();
        _dataList = new System.Collections.Generic.List<Quality_CannonQuality>();
        
        foreach(JObject _ele in _buf)
        {
            Quality_CannonQuality _v;
            _v = global::HotFix.Cfg.Quality_CannonQuality.DeserializeQuality_CannonQuality(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, Quality_CannonQuality> DataMap => _dataMap;
    public System.Collections.Generic.List<Quality_CannonQuality> DataList => _dataList;

    public Quality_CannonQuality GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Quality_CannonQuality Get(int key) => _dataMap[key];
    public Quality_CannonQuality this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

