
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace HotFix.Cfg
{

/// <summary>
/// Generated from Quality.xlsx sheet itemQuality
/// </summary>
public partial class TbQuality_itemQuality
{
    private readonly System.Collections.Generic.Dictionary<int, Quality_itemQuality> _dataMap;
    private readonly System.Collections.Generic.List<Quality_itemQuality> _dataList;
    
    public TbQuality_itemQuality(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Quality_itemQuality>();
        _dataList = new System.Collections.Generic.List<Quality_itemQuality>();
        
        foreach(JObject _ele in _buf)
        {
            Quality_itemQuality _v;
            _v = global::HotFix.Cfg.Quality_itemQuality.DeserializeQuality_itemQuality(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, Quality_itemQuality> DataMap => _dataMap;
    public System.Collections.Generic.List<Quality_itemQuality> DataList => _dataList;

    public Quality_itemQuality GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Quality_itemQuality Get(int key) => _dataMap[key];
    public Quality_itemQuality this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

