
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace HotFix.Cfg
{

/// <summary>
/// Generated from Quality.xlsx sheet GemQuality
/// </summary>
public partial class TbQuality_GemQuality
{
    private readonly System.Collections.Generic.Dictionary<int, Quality_GemQuality> _dataMap;
    private readonly System.Collections.Generic.List<Quality_GemQuality> _dataList;
    
    public TbQuality_GemQuality(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Quality_GemQuality>();
        _dataList = new System.Collections.Generic.List<Quality_GemQuality>();
        
        foreach(JObject _ele in _buf)
        {
            Quality_GemQuality _v;
            _v = global::HotFix.Cfg.Quality_GemQuality.DeserializeQuality_GemQuality(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, Quality_GemQuality> DataMap => _dataMap;
    public System.Collections.Generic.List<Quality_GemQuality> DataList => _dataList;

    public Quality_GemQuality GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Quality_GemQuality Get(int key) => _dataMap[key];
    public Quality_GemQuality this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

