
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace HotFix.Cfg
{

/// <summary>
/// Generated from ServerList.xlsx sheet serverGropMini
/// </summary>
public partial class TbServerList_serverGropMini
{
    private readonly System.Collections.Generic.Dictionary<int, ServerList_serverGropMini> _dataMap;
    private readonly System.Collections.Generic.List<ServerList_serverGropMini> _dataList;
    
    public TbServerList_serverGropMini(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ServerList_serverGropMini>();
        _dataList = new System.Collections.Generic.List<ServerList_serverGropMini>();
        
        foreach(JObject _ele in _buf)
        {
            ServerList_serverGropMini _v;
            _v = global::HotFix.Cfg.ServerList_serverGropMini.DeserializeServerList_serverGropMini(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, ServerList_serverGropMini> DataMap => _dataMap;
    public System.Collections.Generic.List<ServerList_serverGropMini> DataList => _dataList;

    public ServerList_serverGropMini GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ServerList_serverGropMini Get(int key) => _dataMap[key];
    public ServerList_serverGropMini this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

