
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace HotFix.Cfg
{

/// <summary>
/// Generated from Shop.xlsx sheet SummonPool
/// </summary>
public partial class TbShop_SummonPool
{
    private readonly System.Collections.Generic.Dictionary<int, Shop_SummonPool> _dataMap;
    private readonly System.Collections.Generic.List<Shop_SummonPool> _dataList;
    
    public TbShop_SummonPool(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Shop_SummonPool>();
        _dataList = new System.Collections.Generic.List<Shop_SummonPool>();
        
        foreach(JObject _ele in _buf)
        {
            Shop_SummonPool _v;
            _v = global::HotFix.Cfg.Shop_SummonPool.DeserializeShop_SummonPool(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, Shop_SummonPool> DataMap => _dataMap;
    public System.Collections.Generic.List<Shop_SummonPool> DataList => _dataList;

    public Shop_SummonPool GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Shop_SummonPool Get(int key) => _dataMap[key];
    public Shop_SummonPool this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

