
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
/// <summary>
/// Generated from TalentNew.xlsx sheet talentEvolution
/// </summary>
public partial class TbTalentNew_talentEvolution
{
    private readonly System.Collections.Generic.Dictionary<int, TalentNew_talentEvolution> _dataMap;
    private readonly System.Collections.Generic.List<TalentNew_talentEvolution> _dataList;
    
    public TbTalentNew_talentEvolution(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, TalentNew_talentEvolution>();
        _dataList = new System.Collections.Generic.List<TalentNew_talentEvolution>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            TalentNew_talentEvolution _v;
            _v = global::HotFix.Cfg.TalentNew_talentEvolution.DeserializeTalentNew_talentEvolution(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, TalentNew_talentEvolution> DataMap => _dataMap;
    public System.Collections.Generic.List<TalentNew_talentEvolution> DataList => _dataList;

    public TalentNew_talentEvolution GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TalentNew_talentEvolution Get(int key) => _dataMap[key];
    public TalentNew_talentEvolution this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

