
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace HotFix.Cfg
{

/// <summary>
/// Generated from TalentNew.xlsx sheet talentMegaStage
/// </summary>
public partial class TbTalentNew_talentMegaStage
{
    private readonly System.Collections.Generic.Dictionary<int, TalentNew_talentMegaStage> _dataMap;
    private readonly System.Collections.Generic.List<TalentNew_talentMegaStage> _dataList;
    
    public TbTalentNew_talentMegaStage(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, TalentNew_talentMegaStage>();
        _dataList = new System.Collections.Generic.List<TalentNew_talentMegaStage>();
        
        foreach(JObject _ele in _buf)
        {
            TalentNew_talentMegaStage _v;
            _v = global::HotFix.Cfg.TalentNew_talentMegaStage.DeserializeTalentNew_talentMegaStage(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, TalentNew_talentMegaStage> DataMap => _dataMap;
    public System.Collections.Generic.List<TalentNew_talentMegaStage> DataList => _dataList;

    public TalentNew_talentMegaStage GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TalentNew_talentMegaStage Get(int key) => _dataMap[key];
    public TalentNew_talentMegaStage this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

