
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace HotFix.Cfg
{

/// <summary>
/// Generated from TalentLegacy.xlsx sheet talentLegacyNode
/// </summary>
public partial class TbTalentLegacy_talentLegacyNode
{
    private readonly System.Collections.Generic.Dictionary<int, TalentLegacy_talentLegacyNode> _dataMap;
    private readonly System.Collections.Generic.List<TalentLegacy_talentLegacyNode> _dataList;
    
    public TbTalentLegacy_talentLegacyNode(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, TalentLegacy_talentLegacyNode>();
        _dataList = new System.Collections.Generic.List<TalentLegacy_talentLegacyNode>();
        
        foreach(JObject _ele in _buf)
        {
            TalentLegacy_talentLegacyNode _v;
            _v = global::HotFix.Cfg.TalentLegacy_talentLegacyNode.DeserializeTalentLegacy_talentLegacyNode(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, TalentLegacy_talentLegacyNode> DataMap => _dataMap;
    public System.Collections.Generic.List<TalentLegacy_talentLegacyNode> DataList => _dataList;

    public TalentLegacy_talentLegacyNode GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TalentLegacy_talentLegacyNode Get(int key) => _dataMap[key];
    public TalentLegacy_talentLegacyNode this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

