
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace HotFix.Cfg
{

/// <summary>
/// Generated from Vip.xlsx sheet vip
/// </summary>
public partial class TbVip_vip
{
    private readonly System.Collections.Generic.Dictionary<int, Vip_vip> _dataMap;
    private readonly System.Collections.Generic.List<Vip_vip> _dataList;
    
    public TbVip_vip(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Vip_vip>();
        _dataList = new System.Collections.Generic.List<Vip_vip>();
        
        foreach(JObject _ele in _buf)
        {
            Vip_vip _v;
            _v = global::HotFix.Cfg.Vip_vip.DeserializeVip_vip(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, Vip_vip> DataMap => _dataMap;
    public System.Collections.Generic.List<Vip_vip> DataList => _dataList;

    public Vip_vip GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Vip_vip Get(int key) => _dataMap[key];
    public Vip_vip this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

