
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace HotFix.Cfg
{
public sealed partial class Vip_data : Luban.BeanBase
{
    public Vip_data(ByteBuf _buf) 
    {
        id = _buf.ReadInt();
        ParamType = _buf.ReadInt();
        LangugaeID = _buf.ReadString();
        OtherParameter = _buf.ReadString();
    }

    public static Vip_data DeserializeVip_data(ByteBuf _buf)
    {
        return new Vip_data(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 参数类型
    /// </summary>
    public readonly int ParamType;
    /// <summary>
    /// 多语言ID
    /// </summary>
    public readonly string LangugaeID;
    /// <summary>
    /// 参数
    /// </summary>
    public readonly string OtherParameter;
   
    public const int __ID__ = 1553714860;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "ParamType:" + ParamType + ","
        + "LangugaeID:" + LangugaeID + ","
        + "OtherParameter:" + OtherParameter + ","
        + "}";
    }
}

}

